### ISSUE TITLE
Jitsi keeps crashing on Ubuntu 14.04.2

### ISSUE THREAD

**Issue by maraoz** [jitsi/jitsi#113]
I'm trying to keep Jitsi open, and it keeps crashing when I'm not looking (using another workspace).
Here are my logs: https://dl.dropboxusercontent.com/u/2851330/2015-04-27%4015.08.33-logs.zip

Great project, thanks for your awesome work

**Comment by rbecheras** [comment]
I confim the issue.
It seems jitsi crashes after a sleep or a terminal session (Ctrl+Alt+F1).
So it looks that it related to switching on X-server sessions...

**Comment by ingerling** [comment]
This may be related to this launchpad bug:
https://bugs.launchpad.net/ubuntu/+source/jitsi/+bug/1310561

**Comment by ibauersachs** [comment]
Is a /tmp/hs_err_* file generated when Jitsi crashes? If so, please create Gist and refer to it here.

**Comment by ingerling** [comment]
No, such a file is not generated. Anything else that could help?

Am 8. August 2015 14:40:03 MESZ, schrieb Ingo Bauersachs <notifications@github.com>:
>Is a /tmp/hs_err_* file generated when Jitsi crashes? If so, please
>create Gist and refer to it here.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jitsi/jitsi/issues/113#issuecomment-128973635

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ibauersachs** [comment]
@ingerling Well, a core dump from Java maybe. We need a stacktrace of the failing native code. If it really is related to the Ubuntu bug you linked, then it is something from PortAudio. You can try renaming/deleting /usr/share/jitsi/lib/native/libjnportaudio.so. This will render the audio system useless, but it would verify that this is the cause of the issue. If it is, it might be related to connected devices that rattle PortAudios hotplug system in an unexpected way.

**Comment by ingerling** [comment]
I did the following:
I started jitsi, renamed the file you mentioned to *.bak, and locked the screen.
 
The result was a crash. Then I started jitsi again and now it doesn't crash anymore, no matter how often I lock the screen. Even if I reverse the renaming. But a new jitsi instance (started after reversing the naming) again crashes.

So I think it is directly related to the file. 

Thank you for taking care! How can I help you further?

**Comment by ibauersachs** [comment]
@ingerling Okay, you just proved that in YOUR case it's PortAudio. If PulseAudio (as opposed to PortAudio) works for you as the audio system (Tools->Options->Audio), you can keep the file deleted. 

Except for finding other developers, there's not much we can do currently as we're lacking the resources to work on this.

**Comment by ingerling** [comment]
@ibauersachs Thanks! I'm using PulseAudio anyway, so this solves the issue for me :)
May be also for others, I will comment that on Launchpad as well.

**Comment by bmarsilio** [comment]
Hello people, for me two things apparently solved my problem.

First: Execute the command 'sudo rm /usr/share/jitsi/lib/native/libjnportaudio.so'
Second: Accept the certificate when Jitsi opens.

**Comment by MoriTanosuke** [comment]
Removing the file `/usr/share/jitsi/lib/native/libjnportaudio.so` does not solve the issue for me on Xubuntu 14.04 running 2.8.5426.

Are there any other fixes I can try?

**Comment by bmarsilio** [comment]
I did this, but doesn't solve the problem.
Now I'm using Zoiper softphone instead Jitsi, it really works well.


Bruno Marsilio
Desenvolvedor de Sistemas Web
+55 54 9967-1473

Date: Thu, 19 Nov 2015 02:45:10 -0800

**Comment by ibauersachs** [comment]
@MoriTanosuke Depends on what error you are actually encountering. Please create a Gist with the stacktrace you're getting and check if a hs_err_pid*.log file is created (also create a Gist with its contents).

**Comment by ibauersachs** [comment]
@bmarsilio First you say it works, now it doesn't? If you're still interested, also post your stacktrace, logs and hs_err_pid* files.

**Comment by bmarsilio** [comment]
It worked for sometime, now I'm not using Jitsi anymore


Bruno Marsilio
Desenvolvedor de Sistemas Web
+55 54 9967-1473

Date: Thu, 19 Nov 2015 03:19:35 -0800

**Comment by MoriTanosuke** [comment]
@ibauersachs I captured the output in https://gist.github.com/MoriTanosuke/39e44e2191904426ca12 There is no `/tmp/hs_err_pid*` file. I'm using PulseAudio.

**Comment by MoriTanosuke** [comment]
Forgot to mention, I have *openjdk-7* installed:

    $ dpkg --list|grep jdk
    ii  openjdk-7-jre:amd64                        7u85-2.6.1-5ubuntu0.14.04.1             amd64        OpenJDK Java runtime, using Hotspot JIT
    ii  openjdk-7-jre-headless:amd64               7u85-2.6.1-5ubuntu0.14.04.1             amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

**Comment by ibauersachs** [comment]
The crash isn't visible in this output. We need something like in the Ubuntu bug report (see link from comment 3). I'm not a Linux user, so I don't know how to obtain that.

**Comment by MoriTanosuke** [comment]
@ibauersachs added the most recent crash report to the gist https://gist.github.com/MoriTanosuke/39e44e2191904426ca12

**Comment by ibauersachs** [comment]
@MoriTanosuke are you sure you removed libjnportaudio.so? The log you posted crashes exactly there. Remember than any update/re-installation will bring this file back.

**Comment by MoriTanosuke** [comment]
@ibauersachs You are right, I did not remove the file after upgrading to 2.8.5426. Nevertheless, after `mv`ing the file, Jitsi still crashes when I unlock the screen. This time I don't have a crash report though.

**Comment by MoriTanosuke** [comment]
Hm, I just tried to run on Oracles jdk1.8.0_65 and Jitsi does no longer crash when I unlock the screen...

**Comment by bickelj** [comment]
FWIW tried to reproduce using 
jitsi (2.8.5426-1) on 
trisquel 7 using 
openjdk 7u85 (7u85-2.6.1-5ubuntu0.14.04.1), 
pulseaudio (1:4.0-0ubuntu11.1), 
but issue does not occur for me.

Switching to tty and back doesn't crash jitsi, locking screen and unlocking doesn't crash jitsi, switching workspaces doesn't crash it either. Does a call need to be in progress to reproduce the issue?

**Comment by Cyborgscode** [comment]
Jitsi stops/crashes on Fedora 23 with actual openjdk 1.8 everytime the system gets into disk suspend.
It has to be restarted after it comes back from the suspend.
