### ISSUE TITLE
Jitsi Accessibility

### ISSUE THREAD

**Issue by bjadel** [jitsi/jitsi#116]
Hey developers,

I can not use a braille display with Jitsi on Windows 7. Is Jitsi ready for this?

Java8u40 is ready for this: http://openjdk.java.net/jeps/204

Regards
Björn

**Comment by ibauersachs** [comment]
The article you're referencing is for JavaFX, but Jitsi uses Swing. I don't know anything about screenreaders and Swing's support for them, but if it isn't working for you then it obviously doesn't.

I'm closing this for the time being as we quite simply don't have the resources to investigate this or doing any development on it. Sorry.
