### ISSUE TITLE
Randomly audio pass from headphones to speakers on SIP

### ISSUE THREAD

**Issue by adrianio** [jitsi/jitsi#117]
Randomly audio pass from headphones on speaker and I could not pass back on headphones. Options/audio does not permit selecting back headphones. I have to quit/enter program to select back headphones.
Jitsi used on SIP account, Jitsi version 2.9.5441, Windows 8.1.

**Comment by ibauersachs** [comment]
This sounds like your headset is disconnected from the computer during a call, which would initiate the switch to another available device. Please attach your [logs](https://jitsi.org/logs).
