### ISSUE TITLE
Night mode/multiple color themes

### ISSUE THREAD

**Issue by aoighost** [jitsi/jitsi#126]
It would be useful for those of us who prefer darker colors on our desktop to be able to have the ability to switch to a night mode for the GUI. This would be much easier on the eyes at night.

**Comment by JohnReedLOL** [comment]
If you know a little Java, you might be able to change the Swing "Look and Feel" to a color scheme that is softer on the eyes. See: https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

**Comment by damencho** [comment]
Please before you open an issue, please discuss it on one of our mailing lists.
See: https://jitsi.org/Development/MailingLists

**Comment by JohnReedLOL** [comment]
Or you could change the brightness/contrast/saturation on your computer monitor to optimize it for nighttime viewing by making it darker.

**Comment by JohnReedLOL** [comment]
Sorry I couldn't be of more help.

**Comment by JohnReedLOL** [comment]
Oh sorry. I did not realize that by replying to another person't complaint I was opening an issue. Thank you very much.

________________________________

**Comment by shodanx2** [comment]
Hello,
This post is top google result for jitsi desktop dark mode 

I am curious to know if in 2026 it is possible to change the colours to dark mode ?

I find the current colours quite difficult on the eyes

<img width="1474" height="1100" alt="Image" src="https://github.com/user-attachments/assets/a82ab7c0-b66a-4070-bd3e-87403297f5f1" />

Although the last version of jitsi is 2017, is this project abandonned ?
