### ISSUE TITLE
No font setting for chat windows

### ISSUE THREAD

**Issue by zawmn83** [jitsi/jitsi#131]
HI

Is there setting to change font style for chat windows?

**Comment by damencho** [comment]
Please use our users list for asking question before opening new issues:
http://lists.jitsi.org/pipermail/users/

This answer has been already answered.

**Comment by zawmn83** [comment]
Thanks for guiding me to the correct place. 
Can I confirm the setting is not available and can't change font in jitsit ?  

I search till 2013, almost all questions about font are not answered. 
But I only found below post in mailing list of Apr 2014.

"Unfortunately there's no way to change the text size at the moment. It
is a known limitation and something we'd like to fix, but as far as I
know the plan is to wait until the interface is migrated to HTML5."

**Comment by damencho** [comment]
We use the system java fonts and currently inside jitsi you cannot change this. When the UI is switched to HTML one, this feature can be easily added. For now your only option is to change the java font settings, which can be done outside jitsi. 
Please use the mailinglist.
