### ISSUE TITLE
Display name for multiple SIP Accounts 

### ISSUE THREAD

**Issue by gaartsen** [jitsi/jitsi#134]
Hi, It seems There can only be 1 single Display name for every single SIP account. Change the Display Name for Account B, and both the Display names for account A and B are changed into the new name.

**Comment by ibauersachs** [comment]
The actual DISPLAY_NAME property is only applied to the account being edited. The account SIP registration wizard however is somehow being reused as a singleton and doesn't load the properties correctly into the UI.
