### ISSUE TITLE
OSX Upgrade allowed even when not

### ISSUE THREAD

**Issue by Aviator45003** [jitsi/jitsi#135]
When on OSX, Jitsi allows an upgrade to a version which then can not run on that version of OSX. Simple version check would be great.

**Comment by ibauersachs** [comment]
What versions of OSX are we talking about?

**Comment by Aviator45003** [comment]
10.8.2.

**Comment by ibauersachs** [comment]
We do support 10.8, however you should upgrade to at least 10.8.5 for security reasons. Your short messages aren't really helpful in finding the problem. We'd need a detailed error description, the versions of Jitsi you used, the error message(s) and your logs.
