### ISSUE TITLE
Registering a new XMPP account with Jitsi fails

### ISSUE THREAD

**Issue by michaelkeuter** [jitsi/jitsi#136]
When I try to register a new XMPP account within Jitsi (v2.9.5458 on Mac OS X 10.9.5) it always fails with: 

"Unknown XMPP-error (XMPPError connecting to jit.si:5222.). Check if the name of the server is correct."(translated from German)

I tried to register on different XMPP server like "jit.si", "swissjabber.ch" or "jabber.ccc.de" without success. When I register the account with Adium, I can use the existing account with Jitsi without problems. Only the registration fails.

**Comment by ibauersachs** [comment]
The underlying bug is IIRC that we don't lookup the SRV with the real address for the server, but instead try to connect to the domainname directly. This is obviously wrong. Shouldn't be too hard to fix though.

**Comment by michaelkeuter** [comment]
Update: this is the exact error from the Jitsi Log file:

```
2015-06-18 13:32:01.497 SCHWERWIEGEND: [97] plugin.jabberaccregwizz.JabberAccountCreationForm.createJabberAccount().171 XMPPError connecting to jit.si:5222.: remote-server-error(502) XMPPError connecting to jit.si:5222.
```

**Comment by ibauersachs** [comment]
http://lists.jitsi.org/pipermail/dev/2015-August/024905.html

**Comment by emcho** [comment]
I am only seeing the discussion now. I don't understand the reasoning. I don't feel strongly about it but I don't see exactly how we are solving what is a server-side issue by disabling it on the client side.

**Comment by ibauersachs** [comment]
@emcho It's not a server side issue. We don't perform SRV lookups when determining the server to register with. And the used XMPPConnection object doesn't use the certificate service nor does it ensure a secure connection.
