### ISSUE TITLE
Window Position

### ISSUE THREAD

**Issue by METHODTECH** [jitsi/jitsi#145]
O/S = Windows
The main jitsi application window remembers its position fine but any time you make a call the call window appears to the top/left position which is usually directly in front of what I'm working on. So every time I make a call I have to drag it to my second display. It would be great if the code could be updated to remember the position. Otherwise I really like jitsi!

**Comment by ibauersachs** [comment]
@damencho Didn't you just recently implement exactly this?

**Comment by damencho** [comment]
@METHODTECH Have you tried latest nightly builds as this was added recently? (Thanks @ibauersachs for the reminder :))

**Comment by METHODTECH** [comment]
I HAVEN'T been using the nightly builds - only updating from within jitsi! I will try this - thanks!

**Comment by METHODTECH** [comment]
Well that fixed the window position annoyance but it has now introduced a new issue. I use 2 different accounts for making calls and it used to prompt me for which one to use which is exactly what I wanted. It now just makes the call using the first account. Suggestions?

**Comment by METHODTECH** [comment]
Scratch that - my bad. I was using a number I typically use for testing and was clicking on it in the call history versus the main call button. Did learn something though - didn't realize the history used the account the original call was made on! Thanks!
