### ISSUE TITLE
Jitsi video crash

### ISSUE THREAD

**Issue by smarx80** [jitsi/jitsi#149]
Hi,
when I try to enter in video settings, Jitsi crash.

A fatal error has been detected by the Java Runtime Environment:
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x7708a048, pid=8092, tid=3848

 JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
 Java VM: Java HotSpot(TM) Client VM (25.40-b25 mixed mode windows-x86 )
 Problematic frame:
 C  [msvcrt.dll+0xa048]

hs_err_pidxxx.log is available , but github does not permit to attach files except images.

It seems that I have the same (or similar) problem of Sui (reported 1 year ago)

http://lists.jitsi.org/pipermail/users/2014-July/007483.html

Thanks.
Simone.

**Comment by ibauersachs** [comment]
Please create a Gist with the hs_err_pid file and link to it here.

**Comment by smarx80** [comment]
Hi,
hope that I've created it correctly.....
https://gist.github.com/smarx80/6ce4bd5e054665a12598

Thanks.

**Comment by ibauersachs** [comment]
Should be fixed in 4c938c852e66dc22e84136656cadb44fdd31c2e4. Please reopen if it still crashes with the latest nightly.
