### ISSUE TITLE
i18n german: New Facebook account screen - email not username

### ISSUE THREAD

**Issue by ecki** [jitsi/jitsi#155]
If I select "Add Account" and pick network "Facebook" the resulting screen shows me E-Mail and Passwort instead of Username and Passwort in the german locale. It is correct in the english version. Seen on jitsi win x64 on Windows 7 version  2.8.5426 (latest stable).

![screenshot 2015-09-26 00 10 08](https://cloud.githubusercontent.com/assets/361432/10113296/1080e79a-63e3-11e5-9092-154915372b82.png)
 
The dialog btw mentions I need to create a facebook username, it does not mention that I also should create a "app password" in case my fb account is "code protected". The resulting error message from facebook has no useful error code in the response xmpp message.

**Comment by ibauersachs** [comment]
Facebook doesn't support XMPP anymore, so this is obsolete.
