### ISSUE TITLE
Fine-tuning for display of drop-down lists

### ISSUE THREAD

**Issue by elfring** [jitsi/jitsi#158]
I am trying the software "jitsi 2.8-5426" out also on my openSUSE system.

I see drop-down lists in the dialogues "Account Info" and "Connection Info" where a letter like "S" is printed/drawn above the grey border for these input controls in a KDE session.
[How do you think about](http://lists.jitsi.org/pipermail/users/2015-February/008744.html "More fine-tuning for display of drop-down lists?") to move the shown text output a bit to the right?

**Comment by ibauersachs** [comment]
As mentioned in the referenced mailing list thread, I'm not going to juggle around pixels for broken themes. If you want to spend time on this, feel free to create a pull request.
