### ISSUE TITLE
Jitsi crashes Microsoft Outlook & Excel (Office 2016 via Office 365 Home)

### ISSUE THREAD

**Issue by tx3eh8IUD1** [jitsi/jitsi#159]
Hey there,

I know I am not supposed to post before discussing on the mailing list. However, I have a rather serious concern:

I installed Jitsi (and included the Outlook Option to make it default IM). Whenever JITSI is open, outlook crashes upon startup (and also while running). 

Also, in Excel, the app crashes when Jitsi is running and I select "Export", or "Share" under the File tab. I have tried to reinstall jitsi without the "oulook IM option", but to no avail. The software seems simply incompatible.

I expect more jitsi users might upgrade to the new office soon, so I wanted to be sure that this issue is known. It's 100% replicable on my machine, but I have not tested it on other computers.

My system: 
Windows 10
Office 365 (office 2016) Home

**Comment by ibauersachs** [comment]
I have yet to install Office 2016, but please note this quote from Microsoft as you stated using the 64bit version on the mailing list:
> Important: Microsoft recommends the use of 32-bit (x86) versions of Office 2016, Project 2016, and Visio 2016 applications as the default option for all platforms.

**Comment by ibauersachs** [comment]
Okay, the 32bit version crashes too. As a workaround to disable the IM integration, edit the registry:
- edit HKCU\Software\IM Providers\DefaultIMApp -> set to e.g. "None"
- create HKCU\Software\IM Providers\None
(The created folder needs to match the value in DefaultIMApp or Outlook falls back to the default Communicator value)

As the IM integration is quite a beast, this will need some time. Any community help would be much appreciated.

**Comment by tx3eh8IUD1** [comment]
Hey @ibauersachs ,

thanks for the help. I have tried setting the value to "Skype", as there is a "Skype" folder in the "IM Providers" registry. However, whenever I start Jitsi, the value is overridden, resuling in the crash(es) described above. The same is true when I create a "None" Key and set the value of "DefaultIMApp" to "None".

Any way I can stop this default override? 

(On a side note: Thank you for the tip using a different Office Version. I think we both know that you couldn't have been serious there. There are plenty reasons why Microsoft does offer a 64bit version, and why people would use it.)

My setup after jitsi reverted the value back to "Jitsi".
![2015-10-06_jitsi-v-registry](https://cloud.githubusercontent.com/assets/6958661/10323140/144055ae-6c4f-11e5-986c-51cf2f4a39e8.png)

**Comment by ibauersachs** [comment]
You did uncheck the option to set Jitsi as the default IM Provider in the options, right?
Also, when DefaultIMApp points to Jitsi but there is no IM Providers\Jitsi folder, then Office automatically falls back to Communicator. If you create the folder Jitsi it should disable the integration as well (because our plugin actually fiddles with the Communicator folder - there's unfortunately quite a mess).

And I was dead serious about using the 32bit version of Office. Except for large data in Excel there's really not much use for it and it's likely that we wont continue the support for it.

**Comment by ibauersachs** [comment]
@tx3eh8IUD1 should work again. To restore the functionality, enable presence integration in Jitsi's options and set `DefaultIMApp` to `Communicator`.

**Comment by tx3eh8IUD1** [comment]
Sorry @ibauersachs but I cannot get it to work.

Where exactly can I enable presence integration?

Under "contact sources" / "Address book", both checkmarks were set. I have disabled the second, to no avail.

Communicator is the default IM in my registry.

**Comment by ibauersachs** [comment]
Jitsi creates an UpAndRunning entry, but due to the mess I mentioned this is sometimes in the IM Providers\Jitsi key and sometimes in IM Providers\Communicator. Do you find this entry with a value of 2? Set DefaultIMApp to the key where you found the entry. If it's nowhere at all, manually create it below Jitsi and point DefaultIMApp to it.
I'll take a look at this, but it's not my top priority.

**Comment by tx3eh8IUD1** [comment]
I found the "UpAndRunning" key with a value of 0. I set it to 2. 

It was in the communicator folder. I looked through the settings withing Jitsi and not in the registry before....

**Comment by ibauersachs** [comment]
Hmm, not sure what's going on now. I'm seeing some issues now as well again with UpAndRunning not being set and presence only there for a few seconds. No crash though. I'll update this once I find some time.

**Comment by dieterlohrstraeter** [comment]
Hi,
I have exact the same issue as described with Outlook 2016 64-bit when running jitsi on Win10. Unfortunately I don't understand how to solve it from the thread above. It seems to me ibauersachs has provided a fix #159, but I don't know how to install it. I cannot find any related files or directory with similar path etc on my computer.
Can you please guide me?

**Comment by ibauersachs** [comment]
The fix for the crash is in Jitsi's nightly builds, but from what I've seen so far is that presence doesn't really work with it then.

**Comment by piejanssens** [comment]
Installed latest nightly (16/01) and enabled default IM setting in setup, but there is no Jitsi add-in to be seen in the Outlook 2016 options and the call button is not enabled in a contact card.

**Comment by MarcoEs** [comment]
Hi guys, do you have a solution about this issue?

**Comment by MarcoEs** [comment]
Was so easy to fix, please uncheck>  MAKE JITSI THE DEFAULT INSTANT MESSAGING .. that's all when you install..

 See you.

**Comment by Herewith** [comment]
@MarcoEs , which version are you using? MS Outlook 2016 keeps crashing for me if stable release (2.8.5426-x64) is used, even with that option unchecked. In nightlies (2.9.5509-x64), the option doesn't matter: it seems doing nothing.

**Comment by MarcoEs** [comment]
You have the true, I did test where some works and others not, this application is not stable I tried with all versions.... I'm looking other softphone options Jitsi not work deftly with Office365.

**Comment by ibauersachs** [comment]
@MarcoEs Jeez, just use the nightly, it's been fixed there for months now.

**Comment by dieterlohrstraeter** [comment]
Indeed, after installing the "nightly" (2.9.5509 64-bit) for Win10-64, Outlook 2016 doesn't crash anymore :+1: 
Honestly I didn't test everything, but I'll do it by time.
I was new to Jitsi, so I didn't understand where to find. At the end it's easy.
Just go to https://jitsi.org/Main/Download#latestnightly

Thanks for fixing

**Comment by ibauersachs** [comment]
@dieterlohrstraeter There are still issues with showing the actual online/offline status for contacts because of some messed up registry entries, but it doesn't affect Office anymore. I'm working on fixing that, but, as with everything regarding Jitsi, it takes up my spare time and sadly a day has only 24 hours.

**Comment by MarcoEs** [comment]
Hi folks at this time what is the best release to use with no error with O365?

I tried with this one: jitsi-2.9.5519-x86.exe, perhaps not works good..

Thanks.

**Comment by fredericmohr** [comment]
Any idea when this will make it into the stable branch? (Or when 2.9 will become stable)
We're using jitsi at work and rolling out a nightly to all users doesn't sound like fun.

**Comment by ibauersachs** [comment]
I'm working on releasing a stable build, but I can't give you an estimate on when this might be. Right now, you can use build 2.9.5532 with reasonable confidence. The open issues that prevent me from releasing mostly affect Linux only.

If you don't need the Office integration, you can delete
- `Jitsi\native\jmsofficecomm.dll` (for presence integration)
- `Jitsi\native\jmsoutlookaddrbook*`(for Outlook address book search)

**Comment by piejanssens** [comment]
@ibauersachs I installed 5532, but I don't see the addin listed in outlook/options/addins?
Btw, this never got developed right? https://jitsi.org/index.php/GSOC2009/SyncMsOutlook

**Comment by ibauersachs** [comment]
It's not an add in for Outlook. The IM presence in Jitsi starts as a COM server and Outlook (or Word, Visual Sutdio, etc.) queries it.
The sync thing isn't necessary as Outlook is queried directly (over MAPI) when you search for a contact.

**Comment by piejanssens** [comment]
I wasn't expecting to be able to look for Outlook contacts within Jitsi - awesome!
Then I think something is not right in my setup because I'm not able to use the call icon on contacts within Outlook and nor am I able to search for Outlook contacts within Jitsi currently. What should I check?
