### ISSUE TITLE
Jitsi on Linux gives on each startup Alsa lib errors

### ISSUE THREAD

**Issue by ArthurBorsboom** [jitsi/jitsi#167]
Although the sound works fine, on each time the application starts, ALSA lib errors do appear.
On a different linux machine, it gives different errors, but also ALSA lib errors.

ALSA lib pcm_dsnoop.c:614:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:963:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave

Could the sound probing mechanism be the cause and maybe it needs improvement?

**Comment by ibauersachs** [comment]
I'm not sure which library is printing those messages, but, just as you say, it works and is thus not really an issue. If you want to remove the messages, or find a volunteer who does, please open a pull request. I'm closing this because really none of the developers has time for this.

**Comment by ArthurBorsboom** [comment]
Okay, fair enough.
