### ISSUE TITLE
Google contacts problem

### ISSUE THREAD

**Issue by pepemedigu** [jitsi/jitsi#169]
Hi, I use ubuntu 14.04 and Jitsi versions 2.9.5478 and 2.9.5475, and I can't add google contacts in Tools -> Options -> Advanced -> Contact sources -> Google contacts -> +
I put data in Account name and "Save", but nothing happens.

Thanks in advance.

**Comment by ibauersachs** [comment]
We need your full [logs](https://jitsi.org/logs). Please send them to the mailing list or create a Gist and link to it here.

**Comment by Adamoff** [comment]
I have the same problem... Logs shows 
INFO: [23] impl.googlecontacts.GoogleContactsConnectionImpl.connect().132 Google contacts connection failure: com.google.gdata.util.AuthenticationException: Error authenticating (check service name)

I doublechecked e-mail and pass... The same problem with another google account

**Comment by pepemedigu** [comment]
2015-10-18 21:17:44.585 SEVERE: [138] util.UtilActivator.uncaughtException().119 An uncaught exception occurred in thread=Thread[Thread-11,5,main] and message was: Missing client ID or client secret. It is not possible to use Google Contacts API without it.
java.lang.IllegalStateException: Missing client ID or client secret. It is not possible to use Google Contacts API without it.
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.get(OAuth2TokenStore.java:157)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsConnectionImpl.connect(GoogleContactsConnectionImpl.java:122)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl.loadConfig(GoogleContactsServiceImpl.java:142)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl.access$000(GoogleContactsServiceImpl.java:47)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl$1.run(GoogleContactsServiceImpl.java:94)

**Comment by pepemedigu** [comment]
I haven't a field to put my password, only Account name (email address) and Prefix .

**Comment by jitsi-developers** [comment]
Hi,
      
      It's okay. You're not supposed to have one. As of a few months
      ago, it is not supported anymore to connect to Google services
      (via software) using username + password combo. Instead, OAuth2
      support is mandated.
      
      The way it is expected to work, is that you enter your email
      address/user id (I'm not sure which, atm) and the very first time
      the Contacts API is contacted, you are requested to enter your
      OAuth 2 code exactly as Google generates it for you when you
      follow the instructions on the screen.
      
      The only time you use your password, is when you log into Google
      itself (via a web page) so you can retrieve this OAuth 2 code.
      
      I need to check if there is a use case I missed. So far, I haven't
      got an idea what could go wrong in your specific case.
      
      Danny
      
      
      
      On 19-10-15 12:32, pepemedigu wrote:
    
    
      
      I haven't a field to put my password, only Account name (email
        address) and Prefix .
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      
      
      
      _______________________________________________
dev mailing list
dev@jitsi.org
Unsubscribe instructions and other list options:
http://lists.jitsi.org/mailman/listinfo/dev

**Comment by Adamoff** [comment]
Excuse me... I understand you why it is not function but i don't understand how to fix it at all ! Could you be so kind to post step by step instruction with examples ?
Tnx !

**Comment by jitsi-developers** [comment]
Hi,
      
      I think you misunderstand my intentions. I'm not sure what causes
      your problem, so I cannot give you step-by-step instructions.
      I am giving some pointers of how it should work. I'm hoping you
      can confirm or deny any of these hints. That is, have you - for
      example - ever gotten the instruction dialog that asks you to
      generate and copy into it an access token from Google?
      
      As I explained earlier. You need not look for an input field where
      you can enter your password, as that is not an option anymore.
      
      Kind regards,
      Danny
      
      
      On 19-10-15 20:33, Adamoff wrote:
    
    
      
      Excuse me... I understand you why it is not function but i
        don't understand how to fix it at all ! Could you be so kind to
        post step by step instruction with examples ?
        Tnx !
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      
      
      
      _______________________________________________
dev mailing list
dev@jitsi.org
Unsubscribe instructions and other list options:
http://lists.jitsi.org/mailman/listinfo/dev

**Comment by Adamoff** [comment]
I think that is right way to fix it coz i have the same authentication problem to Google Contacts at another SIP-client.
So... How to start OAuth 2 authentication in Jitsi and log into Google web page ? I'm still confused...

**Comment by pepemedigu** [comment]
Hi developers,
I can't see any dialog about generating a token.
I attach you the dialog, I put my address, press Save, and nothing happend.

Thank you very much,

![captura de pantalla de 2015-11-12 13 04 10](https://cloud.githubusercontent.com/assets/15120133/11117901/f6bbde52-893d-11e5-88ca-4b01604e9186.png)

**Comment by ibauersachs** [comment]
The token dialog only comes up once you search for a contact in the main window.

@cobratbq do you think the initial request could be made from the add-dialog and never from the search?

**Comment by pepemedigu** [comment]
But, I can't save the Google source. When I press Save, the source wasn't created, no action succeed.

**Comment by jitsi-developers** [comment]
Hi all,
      
      I was following this thread, but was too busy to respond in time,
      noticed Ingo's message just now. Sorry about that, it wasn't my
      intention but I have been quite busy lately ...
      
      About the issue ... I have seen different error messages in this
      thread.
      
      (1.)
      First:
      2015-10-18 21:17:44.585 SEVERE: [138]
          util.UtilActivator.uncaughtException().119 An uncaught
          exception occurred in thread=Thread[Thread-11,5,main] and
          message was: Missing client ID or client secret. It is not
          possible to use Google Contacts API without it.
        
          java.lang.IllegalStateException: Missing client ID or client
          secret. It is not possible to use Google Contacts API without
          it.
         at
net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.get(OAuth2TokenStore.java:157)
         at
net.java.sip.communicator.impl.googlecontacts.GoogleContactsConnectionImpl.connect(GoogleContactsConnectionImpl.java:122)
         at
net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl.loadConfig(GoogleContactsServiceImpl.java:142)
         at
net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl.access$000(GoogleContactsServiceImpl.java:47)
         at
net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl$1.run(GoogleContactsServiceImpl.java:94)
      I'm pretty sure this happens on your own builds from source,
      correct?
      
      Please check the build task "-pre-googlecontacts". This
      task copies a template as a file which is supposed to provide the
      chat client's ID and secret. These are used by Google's OAuth2 API
      to distinguish one OAuth2 client from another. I use my own ID and
      secret when I make a personal build. Similarly, the Jitsi build
      server has one configured. (damencho knows the specifics about
      this IIRC)
      
      Please look up "GoogleAPIClientToken.java.tmpl" and "GoogleAPIClientToken.java".
      They should contain more information on this. So, this is not
      actually a bug, but a warning issued by Jitsi because it's missing
      information and therefore is not attempting to contact Google
      OAuth2 API servers.
      
      (2.)
      Last time I looked, I focused on the following error:
      
      
        INFO: [23]
        impl.googlecontacts.GoogleContactsConnectionImpl.connect().132
        Google contacts connection failure:
        com.google.gdata.util.AuthenticationException: Error
        authenticating (check service name)
      
      I don't know what causes this. I do not have this issue. The only
      things I can think of to suggest are the following:
      
      1. Remove any Google Contacts configuration lines already in the
      configuration file. Close Jitsi *first*! Then edit the file 'sip-communicator.properties'
      in the directory "~/.jitsi". (I'm not sure which
      directory this is on Windows. Please refer to https://jitsi.org/logs
      the correct directories are mentioned there for your particular
      OS.)
      You recognize the Google Contacts entries by (without the quotes
      themselves): "net.java.sip.communicator.impl.googlecontacts.<emailaddress>.ENCRYPTED_PASSWORD".
      Remove this line for each of the email addresses and you should
      get asked for a new token again. (There's a few lines that look
      alike which store the window's last position.)
      
      2. Check your Jitsi properties (in the application Jitsi, just the
      options) and verify that your contact sources are activated. For
      Google Talk accounts there is an option to disable Google Contacts
      searches, so make sure that Google Contacts searches are enabled
      for your accounts.
      
      Of course, if the above does not work, it helps to provide us with
      the extra information of whether you found the configuration lines
      described in 1.
      
      Also, try out the Google Contacts searches with a precompiled
      packaged Jitsi version. If it works there, then this might be an
      issue with building Jitsi.
      
      Hope this clarifies it a bit.
      
      Danny
      
      
      
      
      
      On 12-11-15 15:03, pepemedigu wrote:
    
    
      
      But, I can't save the Google source. When I press Save, the
        source wasn't created, no action succeed.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      
      
      
      _______________________________________________
dev mailing list
dev@jitsi.org
Unsubscribe instructions and other list options:
http://lists.jitsi.org/mailman/listinfo/dev

**Comment by jitsi-developers** [comment]
One quick remark, see below.
      
      
      On 12-11-15 20:22, Danny van Heumen wrote:
    
    
      
      INFO: [23]
          impl.googlecontacts.GoogleContactsConnectionImpl.connect().132
          Google contacts connection failure:
          com.google.gdata.util.AuthenticationException: Error
          authenticating (check service name)
        
        I don't know what causes this. I do not have this issue. The
        only things I can think of to suggest are the following:
        
        1. Remove any Google Contacts configuration lines already in the
        configuration file. Close Jitsi *first*! Then edit the file 'sip-communicator.properties'
        in the directory "~/.jitsi". (I'm not sure which
        directory this is on Windows. Please refer to https://jitsi.org/logs
        the correct directories are mentioned there for your particular
        OS.)
        You recognize the Google Contacts entries by (without the quotes
        themselves): "net.java.sip.communicator.impl.googlecontacts.<emailaddress>.ENCRYPTED_PASSWORD".

        Remove this line for each of the email addresses and you should
        get asked for a new token again. (There's a few lines that look
        alike which store the window's last position.)
      
    
    
    These instructions for 1. are probably unnecessarily complex. Please
    check Tools -> Options -> Security -> "Saved Passwords..."
    first. The Google Contacts accounts might be listed there. I'm not
    sure if Google Contacts "Contact sources" are also listed in the
    Saved Passwords window.
    
    Danny

**Comment by adiamini** [comment]
Sorry for re-opening a task marked as closed but ... I didn't understand what I have to do :-)

I recently installed jitsi (version 2.10.5550 on Ubuntu, via apt-get), and I'd simply like to use it; sorry for my end-user aptitude, but I haven't time to get into the bowels of each tool I need to use.

So:

 - No idea what **`build task "-pre-googlecontacts"`** means
 - No idea where to find **`"GoogleAPIClientToken.java.tmpl" and "GoogleAPIClientToken.java"`**
 - My **`sip-communicator.properties`** file is (and always has been) empty
 - When I try to add my google account I click on "Save" and really nothing happens. In log file, the error is the same mentioned by other users:

`2018-01-23 17:27:33.652 SEVERE: [281] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[AWT-EventQueue-0,6,main] and message was: Missing client ID or client secret. It is not possible to use Google Contacts API without it.`

Can someone please help me solve this problem ?

Thanks in advance !

**Comment by cobratbq** [comment]
Hi @adiamini, the issue you face is the following: When Google changed to using OAuth2 authentication, it became necessary for everyone wanting to use that feature, to request a client ID and secret. In Jitsi builds provided by the Jitsi team, they embed their own.

For custom builds, you would need to request your own client ID and secret at Google. You can specify that you want an OAuth2 token for a desktop application and will be provided with suitable credentials. You can find the GoogleAPIClientToken.java.tmpl in the source code of Jitsi. (You should be able to find that one.)

Do I understand correctly that you get this error from a Jitsi package that is provided by Ubuntu? (That is, you did not build your own?) If this is the case, then they probably missed this during packaging. That should probably be considered a bug to fixed in the distribution. (Although I don't know if/how distributions manage such OAuth2 keys ...)

**Comment by adiamini** [comment]
Hi @cobratbq, thank you very much, your answer is very clear. Yes, I installed Jitsi using `apt-get` command, I didn't compiled it from source even if, at this point, I think I should do it to include suitable OAuth2 credentials.

The appropriate solution would be that Jitsi gave the possibility to enter the parameter, in some way (being it UI or conf file), but waiting for this to happen I will try to compile it from sources.

Thank you again, have e nice day !

**Comment by cobratbq** [comment]
Hmm... I guess that's an option, but given that you need to request the OAuth2 credentials in the developer console, this is too much of a hurdle for normal users. And on top of that, it is not the way it should be. I'm currently busy, but if I find some time I'll try and investigate.

I'm sorry that the Google Contacts give so many people problems. Although OAuth2 sounds like a nice feature in theory, for desktop software it can be quite an issue.
