### ISSUE TITLE
Jitsi jitsi-2.9.5479-x64 hangs on splashscreen during startup as one particular user

### ISSUE THREAD

**Issue by seanasay** [jitsi/jitsi#172]
It does not hang as other users and I have tried deleting but to no avail.

%APPDATA%\Jitsi
%LOCALAPPDATA%\Jitsi

Hangs at the loading Nimbuzz Avatars but that is a red herring as if I remove that jar it hangs at the next plugin.

very last entry in the procmon log is related to HKCU Keyboard Layout?

![jitsi hang](https://cloud.githubusercontent.com/assets/15193673/10632383/0624e730-77dc-11e5-9334-7ac33acdd5ae.PNG)

**Comment by cubei** [comment]
I have the same problem with jitsi-2.10.5550-x64.exe 2017-02-07 on my Windows Server 2012 R2.
