### ISSUE TITLE
ippi account connection error

### ISSUE THREAD

**Issue by tedych** [jitsi/jitsi#176]
Registered a new ippi account in an effort to be able to audio/video chat through jitsi without using gtalk accounts but Jitsi (latest stable) throws errors when trying to connect to this account. These errors are intermittent and about half of the attempts to connect fail with this error (attached).
I hope this will be fixed because I was pointed to make an ippi account if I want to flawlessly audio chat (gtalk account seems very unreliable (though sometimes it works)).
Win7 Enterprise x64.
![jitsi-ippi-error](https://cloud.githubusercontent.com/assets/15326046/10791488/4a29e920-7d91-11e5-83d9-da7d3f4b177b.png)

**Comment by jitsi-developers** [comment]
Hi,

The issue also exists here on Ubuntu 12.04 with Jitsi build for Ubuntu. 
I completed the registration 4 hours ago on ippi but jitsi throws an 
error (see image).
I have searched for any connection error with Jitsi-ippi but nothing found.
Pop-up error

/Regards/,
/Ahmad

P.S: running jitsi -d in the console doesn't give more information

/

**Comment by tedych** [comment]
This turns to a 100% not being able to connect after few attempts. Did nobody test the basic SIP connection to the french ippi (Jitsi being served and hosted and written in France) for so long, because Jitsi is primarily a SIP communicator and SIP should be working with no issues.. even if XMPP audio/video has its many issues.
Ippi is the recommended SIP service almost everywhere Jitsi is mentioned. The information in the screenshot above should point to where to search for the bug.

**Comment by jitsi-developers** [comment]
Hi,

It's embarrassing to say that there is nothing wrong with the SIP
protocol. I have tested ippi using both ippi account and SIP account.
When you type your SIP or ippi ID, don't type "myusername@ippi.fr" or
"john@voiphone.net". It's completely misleading. Just type your ID
without the domain.

As for adding ippi from SIP interface, you have to go to "Advanced",
type your ID in the username field and then type your domain in the
Registrar field (ippi.fr in this case).

The id@domain label was really misleading. You may close the issue.

On 10/29/2015 10:11 AM, tedych wrote:
>
> This turns to a 100% not being able to connect after few attempts. Did
> nobody test the basic SIP connection to the french ippi (Jitsi being
> served and hosted and written in France) for so long, because Jitsi is
> primarily a SIP communicator and SIP should be working with no
> issues.. even if XMPP audio/video has its many issues.
> Ippi is the recommended SIP service almost everywhere Jitsi is
> mentioned. The information in the screenshot above should point to
> where to search for the bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jitsi/jitsi/issues/176#issuecomment-152108424>.
>
>
>
> _______________________________________________
> dev mailing list
> dev@jitsi.org
> Unsubscribe instructions and other list options:
> http://lists.jitsi.org/mailman/listinfo/dev

-- 
/Regards/,
/Ahmad/
