### ISSUE TITLE
Jitsi didn't start with recompiled libjitsi

### ISSUE THREAD

**Issue by sioux1977** [jitsi/jitsi#193]
Hi guys, i need to enable g.729, i want to try it before buy the license, but i can't make it working.

I did following steps:
1) I have download from github jitsi-master.zip and libjitsi-master.zip
2) i have unzipped all of them.
3) in libjitsi source directory, i did 'ant make-with-g729'
4) i have copied the new libjitsi.jar into jitsi-master/lib/installer-exclude/libjitsi-1.0-SNAPSHOT.jar
5) in jitsi source directory, i did 'ant clean bundle-libjitsi make'

Compilation goes well, but when i did 'ant run', i receive a lot of exception regarding missing bundles (see attached file)
[exception.txt](https://github.com/jitsi/jitsi/files/45914/exception.txt)

Thank you in advance.

**Comment by ibauersachs** [comment]
libjitsi needs to be built with Maven (`mvn package`) meanwhile to include the necessary OSGi metadata. The Maven build though doesn't have an option to include the g729 code, so you'd need to adapt the pom.

**Comment by sioux1977** [comment]
Thank you for your answer... i have tried to build it with maven, but it fails with a missing dependency, can you tell me the right steps to compile with maven? (i don't know how to use it, i have tried with no luck...)

(in attach you can find the complete build output)
[mvn-package.txt](https://github.com/jitsi/jitsi/files/47219/mvn-package.txt)

**Comment by ibauersachs** [comment]
If your Maven installation comes from a Debian (or some other non-official Apache) package, then please try uninstalling it and download it from [Apache](https://maven.apache.org/download.cgi). The line `file:/usr/share/maven2/lib/maven-debian-uber.jar` in your log makes me think that this might be the reason.

**Comment by sioux1977** [comment]
I have uninstalled maven from my system (i use Linux Mint) and i have deleted the ~/.m2 directory; i have downloaded maven 3.3.9 from apache and i have tried again, but it still fail on same junit test. In attach the new maven output.
[mvn-output2.txt](https://github.com/jitsi/jitsi/files/47303/mvn-output2.txt)

**Comment by ibauersachs** [comment]
Not sure what's going on there, but you can skip the tests (`-Dmaven.test.skip=true`).

**Comment by sioux1977** [comment]
Hi Ingo, now i have the new libjitsi-1.0-SNAPSHOT.jar; i have unzipped it just to be sure that bundle metadata is in place (it's in place and seems to be correct).

I have copied it in (jitsi-source)/lib/installer-exclude and i have rebuilded jitsi (see ant-rebuild.txt) successfull, but running it i have other OSGi errors (see ant-run.txt); seems to be that can't find libjitsi...

[ant-run.txt](https://github.com/jitsi/jitsi/files/47360/ant-run.txt)
[ant-rebuild.txt](https://github.com/jitsi/jitsi/files/47361/ant-rebuild.txt)

**Comment by ibauersachs** [comment]
libjitsi cannot find a required dependency in ice4j; you probably need to update that too (build it with Maven as well).

**Comment by sioux1977** [comment]
i have download and built it (producing ic4j-1.0-SNAPSHOT), i have renamed it to ice4j.jar and copied into (jitsi-source)/lib/installer-exclude but i have got same errors...

**Comment by sioux1977** [comment]
Hi ingo, any news? Thank you for wasting your time with me...

**Comment by ibauersachs** [comment]
Somehow libjitsi now requires ice4j as an OSGi dependency and this breaks a whole lot of stuff. You can work around it by removing org.ice4j.socket from the manifest import in libjitsi. But be aware that this is a hack (and needs a serious investment of time from our side to clean up - which I don't have currently).

Change the libjitsi/pom.xml from `<Import-Package>*,sun.lwawt,sun.lwawt.macosx</Import-Package>` to `<Import-Package>!org.ice4j.socket,*,sun.lwawt,sun.lwawt.macosx</Import-Package>`, then package it again and copy to jitsi.

**Comment by sioux1977** [comment]
It's a really mess... i have tried as you suggest and i can compile 
right but at runtime libjitsi didn't find org.ice4j.socket. I am think 
that apart changes for g.729, i can't compile in the right way in any 
case... so how you can deploy the nightly build of jitsi? may be are you 
use an older version of libjitsi? (in this case, how can i download a 
version of libjitsi that compile well?)

Il 02/12/2015 23:20, Ingo Bauersachs ha scritto:

**Comment by ibauersachs** [comment]
@gpolitis you last updated libjitsi. Which exact revision was that?

The nightlies of Jitsi use the libjitsi binary committed in the lib/installer-exclude folder, thats why they still work. I know this should change (and it will), but it needs time nobody currently has.

**Comment by gpolitis** [comment]
I'm sorry for not including the commit hash. I haven't kept it anywhere, so I can't say for sure which one was it, but https://github.com/jitsi/libjitsi/commit/8c7e340b92c4ba62045df3f9554351b0750cee74 should work (that's the merge commit).

**Comment by fredericojssilva** [comment]
any updates on that? I'm exactly with the same problem!

**Comment by ibauersachs** [comment]
I'll try to work on it next week, but no promises.

**Comment by jonvargas** [comment]
Hello. I am facing the same issue. The latest libjitsi version doesn't seems compatible with latest jitsi's version. If I checkout the tag with the patch applied by @gpolitis , it doesn't compile:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jvargas/Projects/libjitsi/src/org/jitsi/impl/neomedia/MediaStreamStatsImpl.java:[334,31] cannot find symbol
  symbol:   method getRoundTripDelay(long,long,long)
  location: class net.sf.fmj.media.rtp.RecvSSRCInfo
[ERROR] /home/jvargas/Projects/libjitsi/src/org/jitsi/impl/neomedia/transform/rtcp/StatisticsEngine.java:[681,51] cannot find symbol
  symbol:   method getRoundTripDelay(int)
  location: class net.sf.fmj.media.rtp.RecvSSRCInfo
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.213 s
[INFO] Finished at: 2016-04-04T12:12:51-06:00
[INFO] Final Memory: 24M/509M
```

Which would be the version of libjitsi that is able to compile against latest jitsi sources? I want to make a simple change in the libjitsi's code and deploy into jitsi. 

By the way, with this pull request (https://github.com/jitsi/jitsi/pull/234) the jitsi's code compiles, but it doesn't run because it still complains at execution time:

```
     [java] ERROR: Bundle org.jitsi.libjitsi [119] Error starting reference:file:sc-bundles/libjitsi.jar (org.osgi.framework.BundleException: Unable to resolve org.jitsi.libjitsi [119](R 119.0): missing requirement [org.jitsi.libjitsi [119](R 119.0)] osgi.wiring.package; (&(osgi.wiring.package=org.ice4j.socket)(version>=1.0.0)(!(version>=2.0.0))) Unresolved requirements: [[org.jitsi.libjitsi [119](R 119.0)] osgi.wiring.package; (&(osgi.wiring.package=org.ice4j.socket)(version>=1.0.0)(!(version>=2.0.0)))])
     [java] org.osgi.framework.BundleException: Unable to resolve org.jitsi.libjitsi [119](R 119.0): missing requirement [org.jitsi.libjitsi [119](R 119.0)] osgi.wiring.package; (&(osgi.wiring.package=org.ice4j.socket)(version>=1.0.0)(!(version>=2.0.0))) Unresolved requirements: [[org.jitsi.libjitsi [119](R 119.0)] osgi.wiring.package; (&(osgi.wiring.package=org.ice4j.socket)(version>=1.0.0)(!(version>=2.0.0)))]
     [java] 	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4114)
     [java] 	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111)
     [java] 	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
     [java] 	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
     [java] 	at java.lang.Thread.run(Thread.java:745)

```

Help is pretty much appreciated.

**Comment by ibauersachs** [comment]
There are a few PRs in jitsi-universe, ice4j and libjitsi pending. Once they are merged, I can proceed with updating Jitsi.

**Comment by lyubomir** [comment]
@ibauersachs, I'm to merge as many of @champtar's PRs as possible this week so will it be of help to you if I merge these jitsi-universe, ice4j, and libjitsi PRs that you mentioned above?

**Comment by ibauersachs** [comment]
Yes, as I don't want to commit customized binaries in Jitsi.
