### ISSUE TITLE
Jitsi auto disconnect

### ISSUE THREAD

**Issue by vandergun** [jitsi/jitsi#195]
I see,sometimes, Jitsi disconnect and reconnect account , I use XMPP. any one have solution?
And Jitsi 64bit use too much memory, can i disable something to fix that?

**Comment by ibauersachs** [comment]
This can happen with unreliable servers or connections.
No.
Please use the mailing list for questions like these.

**Comment by roeycohen** [comment]
@ibauersachs the mailing list really doesn't work well...
google doesn't search it and the embedded search engine is really bad.
why aren't you using github or something similar like most open source projects do?
