### ISSUE TITLE
Disconnecting problem 

### ISSUE THREAD

**Issue by awends86** [jitsi/jitsi#196]
The softphone seems to disconnect from my SIP after about 3 minutes of non usage. it doesn't show as disconnected status but I cannot receive calls or make calls.   If I change the status from "online" to "offline" and back to "online" I can receive calls for another 3-5 minutes or so. Any help?

**Comment by damencho** [comment]
This is a problem that your NAT forgets your mappings. In other words you need to configure one of the keeplive methods available in your advanced sip account settings. Some servers can do this also, like asterisk has the option qualify, sending a sip packet every 25 seconds to keep that mapping alive, its recommended if you configure it on the client side to configure it at 25 seconds interval.

**Comment by damencho** [comment]
Please post your question to the dev list. Not as issues.

**Comment by awends86** [comment]
Thanks. I sent an email regarding my other issues with call conferencing
but have not heard any response. Whenever I create a conference call there
is overwhelming static on the other parties lines.
