### ISSUE TITLE
Dictionary Portuguese Brazil

### ISSUE THREAD

**Issue by rodrigocorsi2** [jitsi/jitsi#202]
Hi,

I've a tested dictionary pt_BR, I would like to send it to jitsi server, how can I do this?

thank you

**Comment by damencho** [comment]
Currently all translations happen on http://translate.jitsi.org/ and changes got pushed to the repository from there.

**Comment by ibauersachs** [comment]
@damencho I think he's talking about the spellchecker, not the translation. These dicts are downloaded from somewhere on jitsi.net/org on demand.

**Comment by rodrigocorsi2** [comment]
Exactly, we need to publish the file pt_BR.zip on http://dictionaries.jitsi.net/ like other dicts.
Then include in /jitsi/resources/config/spellcheck/parameters.xml the line:
```
<locale label="Portuguese (Brazil)" isoCode="pt,br" dictionaryUrl="http://dictionaries.jitsi.net/pt_BR.zip" flagIcon="br"/>
```

**Comment by damencho** [comment]
You can send it to me and I will upload it and add it.

**Comment by rodrigocorsi2** [comment]
I sent an email to you, can I do a pull request?

**Comment by damencho** [comment]
I've upload it and add it to the list of dictionaries, you can test it with build 5490 when it is ready.
