### ISSUE TITLE
Dependencies for Mac, Windows, Linux clients

### ISSUE THREAD

**Issue by NaurisSadovskis** [jitsi/jitsi#206]
Hi all,

first, thanks for continues development of Jitsi.

Our machines consist of:
70% Linux (CentOS 6.6)
20% Windows 7 (Enterprise)
10% Mac (Mavericks, Yosemite)
Java versions: 1.8.0.65_b17 on Mac and Linux, 1.7.0_45-b18 on Windows. 

Can you advise, what would be an 'ideal' OS/Java/system configuration (perhaps, extra audio/video plugins needed) on all three platforms? While audio/video calls seem to work with no problems, I ran into issues with RDC whereupon switching back to video it crashed the application. I also noticed that some RDC, in some combinations (Mac to Linux, Mac to Windows, Linux to Mac) would grind to a halt when controlling the target. It works fine the other way around. 

Have these issues popped up somewhere before? Any help would be appreciated. 

Nauris

**Comment by ibauersachs** [comment]
These are questions for the mailing list (users@jitsi.org), not the issue tracker.
