### ISSUE TITLE
SSO for Jitsi

### ISSUE THREAD

**Issue by willemdh** [jitsi/jitsi#208]
Does Jitsi provide SSO? If yes could I have a link to some documentation how to set this up please?

**Comment by jitsi-developers** [comment]
Afaicr, is integration with Kerberos on a wish-list. Very few are interested in it.
Only thing available is Single-Sign-OFF, by means of powering down your machine ☺

From: dev [mailto:dev-bounces@jitsi.org] On Behalf Of willemdh
Sent: woensdag 20 januari 2016 15:43
To: jitsi/jitsi
Subject: [jitsi-dev] [jitsi] SSO for Jitsi (#208)


Does Jitsi provide SSO? If yes could I have a link to some documentation how to set this up please?

—
Reply to this email directly or view it on GitHub<https://github.com/jitsi/jitsi/issues/208>.

______________________________________________________________________
Dit bericht kan informatie bevatten die niet voor u is bestemd. Indien u niet de geadresseerde bent of dit bericht abusievelijk aan u is toegezonden, wordt u verzocht dat aan de afzender te melden en het bericht te verwijderen. De Staat aanvaardt geen aansprakelijkheid voor schade, van welke aard ook, die verband houdt met risico's verbonden aan het electronisch verzenden van berichten.

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. The State accepts no liability for damage of any kind resulting from the risks inherent in the electronic transmission of messages.

**Comment by willemdh** [comment]
Ok, thanks for the information. We are using Spark at the moment, which does has SSO implemented, but has other issues. 
SSO is on our 'required features list' in the search for a replacement.

**Comment by ibauersachs** [comment]
The problem with SSO is that Java is not capable of using Windows' Kerberos correctly (it wants to access the TGT, which is not possible (except if you set a registry key (which is AFAIK gone in Windows 8) and disable UAC) for security reasons).

**Comment by willemdh** [comment]
If someone would ever consider giving this a try, this thread contains some useful information:
https://community.spiceworks.com/topic/379664-openfire-sso-on-windows

**Comment by gradinaruvasile** [comment]
Jitsi can use LDAP for contact source lookup, that includes authentication against LDAP already (i use it with AD). Why not use that component for authentication?

**Comment by ibauersachs** [comment]
@gradinaruvasile Authentication against LDAP is a server side thing, this issue about SSO (i.e. not entering a password again on the client). And this is currently not possible with Java on Windows (which is the only platform where I have a working Kerberos server).

I'm closing this issue. Once Java supports Windows' Kerberos or SSPI, please ask to reopen.

**Comment by mkaatman** [comment]
Has this situation changed?

https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/single-signon.html

**Comment by ibauersachs** [comment]
@mkaatman No, it hasn't. See:
- http://stackoverflow.com/questions/14556119/how-do-people-make-java-spnego-client-work-in-windows
- https://bugs.openjdk.java.net/browse/JDK-6722928

I might consider upgrading the apache-httpclient libraries though. This would at least help to get SSO for provisioning.

**Comment by maciey** [comment]
Hi Any progress re SSO ?
It would be extremely useful to have this option

**Comment by maciey** [comment]
How this was done in Spark then ?

**Comment by ibauersachs** [comment]
See the links above.

**Comment by billroland** [comment]
I believe the situation has indeed changed, if I read this correctly Java now provides native GSS-API library for Windows.
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-6722928
