### ISSUE TITLE
Zeroconf/Bonjour Serverless/Registrarless

### ISSUE THREAD

**Issue by vindicatorr** [jitsi/jitsi#210]
Looked at:
https://jitsi.org/Development/PluginZeroConf
and https://trac.jitsi.org/ticket/358 (Support for Bonjour / ZeroConf)

ChatSecure allows you to enter only a username and nothing more when creating "WiFi Mesh Chat"
Jitsi requires a domain to be added to the username.

Running latest (buggy) master commit b59ada8348ec9048fce58801d58a6c76200382a4

**Comment by ibauersachs** [comment]
Zeroconf/Bonjour has been disabled for a long time as it wasn't maintained. Lacking resources for even the most important protocols, I don't see this coming back. Registrarless SIP should be working in a LAN without firewalls.
