### ISSUE TITLE
XXX sent you a message that was intended for another session. If you are logged in multiple times another session may have received this message.

### ISSUE THREAD

**Issue by dandelion-lover** [jitsi/jitsi#214]
When I am at home, the chat work fine, but when I am at work, person B can receive my message, but I receive this instead:
"XXX sent you a message that was intended for another session. If you are logged in multiple times another session may have received this message." 
Restarts do not help.
Jitsi 2.8.5426, Debian Jessie.

Older descriptions:
http://lists.jitsi.org/pipermail/dev/2014-December/022955.html
https://trac.jitsi.org/ticket/1279

**Comment by jitsi-developers** [comment]
Please, switch on both sides to nightly builds, this OTR issue is fixed already, also you have to check if your Jitsi client created (multiple) OTR sessions, which you can select over the padlock in the right lower corner of the chat window.
I would always stop OTR manually after the chat (on both sides) to avoid creation of different OTR sessions, especially if you use Jitsi at home/work with same computer.
OTR works correctly, even the creation of different sessions occurs as it should
br, MS

On January 29, 2016 2:41:33 PM GMT+03:00, dandelion-lover <notifications@github.com> wrote:
>When I am at home, the chat work fine, but when I am at work, person B
>can receive my message, but I receive this instead:
>"XXX sent you a message that was intended for another session. If you
>are logged in multiple times another session may have received this
>message." 
>Restarts do not help.
>Jitsi 2.8.5426, Debian Jessie.
>
>Older descriptions:
>http://lists.jitsi.org/pipermail/dev/2014-December/022955.html
>https://trac.jitsi.org/ticket/1279
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jitsi/jitsi/issues/214
>
>------------------------------------------------------------------------
>
>_______________________________________________
>dev mailing list
>dev@jitsi.org
>Unsubscribe instructions and other list options:
>http://lists.jitsi.org/mailman/listinfo/dev

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
