### ISSUE TITLE
Presence Information

### ISSUE THREAD

**Issue by Schnigga** [jitsi/jitsi#215]
Hello,
I'm provisioning Jitsi over a HTTP-Interface. When I'm setting the property for the presence information in the SIP-Account on false the Client shows "me" (German "Ich") in the GUI (see [here](http://fs5.directupload.net/images/160201/no26l6r8.png)). When I'm setting the property to true it shows the display Name configured with the Display Name property. I'd like to configure the SIP Account without the presence information enabled, but Jitsi should show the Display Name in GUI.

Presence property:
net.java.sip.communicator.impl.protocol.sip.accsip.IS_PRESENCE_ENABLED=[false/true]
Display Name property:
net.java.sip.communicator.impl.protocol.sip.accsip.DISPLAY_NAME=[string]

best Regards
Schnigg

**Comment by ibauersachs** [comment]
@Schnigga are you using CUSAX? (Doesn't really matter for the issue itself, but helps me remember where that comes from.)

**Comment by Schnigga** [comment]
@ibauersachs 
No. I'm only using SIP. 

But if this can help you: When I'm also provisioning a XMPP Account it shows me the name of the XMPP user instead of "ME". This is independent of SIP-Presence Information.

**Comment by ibauersachs** [comment]
Try the next nighlty build please.

**Comment by Schnigga** [comment]
@ibauersachs 
thank you for solving this! It is working now, but it's not showing the "ACCOUNT_DISPLAY_NAME" in Main GUI, instead it's showing the "User_ID". So actually it looks like in Screenshot 01 but in should look like in Screenshot 02.

![jitsi_screenshot 01](https://cloud.githubusercontent.com/assets/8692923/13389318/271697ca-dec7-11e5-967c-605d2d2925b3.png)
![jitsi_screenshot 02](https://cloud.githubusercontent.com/assets/8692923/13389317/2716acd8-dec7-11e5-84f3-71014f68707b.png)

best regards
schnigga
