### ISSUE TITLE
jitsi freezes 

### ISSUE THREAD

**Issue by rockrockovic** [jitsi/jitsi#218]
WARNING: impl.protocol.jabber.OperationSetBasicInstantMessagingJabberImpl.isCarbonSupported().775 Failed to retrieve carbon support.service-unavailable(503)
severe impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact mail@adress.tld service-unavailable.
then freeze.....

tried deb nightly and stable....
also tried the uncheck the box of tray/docker...

my desktop: ubuntu 15.10
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java

**Comment by rockrockovic** [comment]
before the content of post before this line is visible in the logs:
WARNING: impl.protocol.jabber.OperationSetBasicInstantMessagingJabberImpl.isCarbonSupported().775 Failed to retrieve carbon support.service-unavailable(503)

**Comment by ibauersachs** [comment]
Incomplete bug report. Please see https://github.com/jitsi/jitsi/blob/master/CONTRIBUTING.md and https://jitsi.org/logs.

**Comment by rockrockovic** [comment]
yeah, no.
i am not subscribing yet another mailinglist.
have a nice day figuring out yourself
