### ISSUE TITLE
Jitsi crashes whenever it tries to use video

### ISSUE THREAD

**Issue by squarefractal** [jitsi/jitsi#220]
I'm using Jitsi 2.8.5426 on Windows 8.1 x64.

Whenever Jitsi tries to use video from the camera in any way, for example, in a video call or when trying to modify the video options from Tools > Options > Video, it crashes.

The hs_errors_pid* file has been attached below.
[hs_err_pid1372.txt](https://github.com/jitsi/jitsi/files/134352/hs_err_pid1372.txt)

**Comment by teawrecks** [comment]
Experiencing exactly the same issue.

Windows 7 x64

[hs_err_pid5932.txt](https://github.com/jitsi/jitsi/files/191039/hs_err_pid5932.txt)

**Comment by ibauersachs** [comment]
This must be somehow related to the particular webcam. Lacking hardware causing this, I can't test or reproduce it.

**Comment by teawrecks** [comment]
I don't know about squarefractal, but I'm trying to use DroidCam to use my Nexus 5 as a webcam. This is an unorthodox setup, but luckily if you want to test it all you need is a semi-recent android phone. While using DroidCam could be related to the issue, it is worth noting that the person I was trying to webcam with was also using Windows 7 + DroidCam + Nexus 5 + Jitsi without any of the issues I am seeing. So it's still not a 100% repro case.

**Comment by squarefractal** [comment]
Well, it's difficult to say which camera is being used, since I can't access the settings section; and there are two "cameras" on the computer:

```
USB Video Device
	Device Kind	Camera/scanner
	Device Name	USB Video Device
	Vendor	Chicony Electronics Co Ltd
	Comment	HP HD Webcam
	Location	USB Composite Device
		Driver
			Date	6-21-2006
			Version	6.3.9600.17217
			File	C:\WINDOWS\system32\drivers\usbvideo.sys
ManyCam Virtual Webcam
	Device Kind	Camera/scanner
	Device Name	ManyCam Virtual Webcam
	Vendor	Visicom Media Inc.
		Driver
			Date	12-26-2014
			Version	4.1.300.0
			File	C:\WINDOWS\system32\DRIVERS\mcvidrv.sys
```

**Comment by ibauersachs** [comment]
@teawrecks I don't have an Android phone.
@squarefractal Try to get rid of the ManyCam Virtual WebCam. I know there have been issues before with virtual cam stuff.

**Comment by teawrecks** [comment]
Ah my issue was ManyCam as well. Forgot I had that. Uninstalled it and the video tab works fine now. Thanks!

**Comment by squarefractal** [comment]
[**@ibauersachs**](https://github.com/ibauersachs) commented on [Friday, April 1, 2016 11:17:32 AM](https://github.com/jitsi/jitsi/issues/220#issuecomment-204255906 "2016-04-01T05:47:32Z - Replied by Github Comment Enhancer"):
> Try to get rid of the ManyCam Virtual WebCam. I know there have been issues before with virtual cam stuff.

Unfortunately this is not an option for me — I actually plan to use the virtual webcam to switch between casting video from the actual webcam and my screen.
