### ISSUE TITLE
disable XMPP advanced contact details

### ISSUE THREAD

**Issue by Schnigga** [jitsi/jitsi#226]
Hello,
is there a property to disable the advanced XMPP Contact Info? So I'd like to add a XMPP account but it shouldn't show me his advanced contact details. Reason for this is, that the XMPP phone numbers aren't correctly added in the OpenFire Server and if there is also a SIP Account configured in Jitsi the users are calling the wrong number. 

best Regards
Schnigga

**Comment by ibauersachs** [comment]
You can try playing around with the property `net.java.sip.communicator.impl.protocol.jabber.VCARD_REPLY_TIMEOUT`, e.g. setting it to 0, but you're probably better off disabling VCard support in OpenFire by setting `provider.vcard.className` to an invalid class name.

**Comment by Schnigga** [comment]
@ibauersachs 
Thank you! This solves my Problem! Disabling the vcard on the openfire isn't possible, because its used from other services too.

best Regards
schnigga
