### ISSUE TITLE
Jitsi crashing in windows traced back to run.c

### ISSUE THREAD

**Issue by powerpbx** [jitsi/jitsi#229]
The Jitsi nightly builds work fine so those builds must be done differently.  I have read of others having the same problem as I am trying to get compiled windows installer running.

My development environment is Windows 10 64bit, Eclipse Mars 64bit, JDK v1.7.79 64bit, Ant v1.9.6, TDM32 GCC 5.1.0.  I have tried different versions of all of these things including Mingw32 gcc to verify it's not the compiler.  I am trying to compile Jitsi as a 32bit app.  Yes I am using jre 32bit as my included runtime.

I have narrowed it down to run.c when it tries to do the JNI call.  The following commit seems to be partially responsible.  It was apparently added to prevent a similar crash condition. When I remove it I can get Jitsi to run.  Splash screen doesn't work though so something is still a little off.

I have also verfied all my paths and dependencies in my development environment.  It all seems to point back to run.c

http://code.metager.de/source/diff/jitsi/src/native/windows/run/run.c?r1=/jitsi/src/native/windows/run/run.c@f7361e133800b3b3c0de5c22e9d2e494194e84c3&r2=/jitsi/src/native/windows/run/run.c@dc1c301d2d23a469da8f0cde5bcdf5183232b3a9&format=s&full=0

>- Applies Ingo Bauersachs' fix for a crash related to an invalid calling convention upon trying to call JNI_CreateJavaVM.
- Fixes a failure to load the JRE runtime library because of unreachable dependencies which are actually available in the bin directory.

**Comment by ibauersachs** [comment]
There's nothing special in there. Have you verified that the `runtimeLib` and `javaHome` arguments in `Run_runJavaFromRuntimeLib` are what they should be? I'm suspecting that these point to a 64bit JRE.

**Comment by powerpbx** [comment]
Thank you for the response.  Based on your advice I tried creating a 64bit installer which worked perfectly.  Using the same setup I tried creating a 32bit installer making sure to change my paths to all 32 development software including JDK and embedded JRE.  It still won't work and I cannot find any 64bit paths or software anywhere other than my OS.  

I went so far as to uninstall all 64bit development software including JDK ,JRE and Eclipse and TDM64 GCC.  Even with all 32bit develpment sofware I cannot get it to work.  My next step would be to try set this all up on a 32bit Windows OS which I don't have.  I guess I will have to keep looking for the root cause on 64bit OS.

**Comment by powerpbx** [comment]
I removed the -O2 compiler flag and now I see it is getting as far as loading Java bundles.  The splash screen freezes on "NimbuzzAvatars".  So it is running SIPCommunicator.java and getting as far as org.apache.felix.main.Java.

The only thing I find related to that error is this.  I confirmed my load order is 13 as per that fix.
https://github.com/jitsi/jitsi/commit/f5dc6edede237288d6b09dddcabd1ed47f55c8c2

**Comment by jitsi-developers** [comment]
Try removing your sip-communicator.bin folder that is in your home folder
and try starting again.

**Comment by powerpbx** [comment]
I had looked for that but there is no folder or file with that name or any similar name.  I also did a drive and registry search.

**Comment by ibauersachs** [comment]
You'll need to get access to what Java is printing to STDOUT. You can e.g. change SIPCommunicator.java (near the end of the main(...) method) to print this into a file.

**Comment by powerpbx** [comment]
If I run jitsi.exe that was compiled without the -O2 flag it installs and runs on Windows 7 32bit.  If I compile with the -O2 flag it crashes the same as it does on Windows 10 64bit.

I found this line in SIPCommunicator.java
    System.setOut(new ScStdOut(System.out));
and had a look at ScStdOut.java and read all the comments in the file but it's not clear to me what I should do here to print out STDOUT.

This still looks like it could be a JNI issue to me because if I remove that code as explained in my first post it will work.

**Comment by powerpbx** [comment]
I managed to get my 32bit compiled version running on Win10 64bit.  It requires a combination of using a slightly older embedded JRE (JRE8u40) in combination with removing the -O2  CPPFLAG from ./src/native/windows/run/Makefile.

**Comment by powerpbx** [comment]
I thought I had everything working.  I have 32bit app working on windows 7 32bit and Windows 10 32bit.  I have 64bit app working on Windows 10 64bit.

However, I cannot get the exact same 32 or 64bit apps working on Windows 7 64bit.  Freezes at splash screen.

**Comment by powerpbx** [comment]
I have it working on Win 7 64 now.  When my development environment is Win 7 64bit it works.  When my development environment is Win 10 it doesn't seem to be portable to Win 7 64bit.

**Comment by ibauersachs** [comment]
The Jitsi releases are built on Windows 7 64bit, using cygwin.
32bit compiler: gcc version 4.5.2 (tdm-1)
64bit compiler: gcc version 4.5.2 (tdm64-1)
Embedded JRE: 8.0.40.25

I don't know what else could be the problem, so I'm closing this issue.
