### ISSUE TITLE
Fix for pipe function not working in Windows makefile

### ISSUE THREAD

**Issue by powerpbx** [jitsi/jitsi#236]
This is our first try at fixing the ARCH not working because pipe doesn't seem to work in windows makefile.  It also removes that last remaining dependency on MSYS (sed) as far as we can tell.   Open to suggestions on other ways to do this.

https://github.com/powerpbx/jitsi/commit/e26bdb51fcfc3638a66d3b47ae095bfd4e5c187d

**Comment by ibauersachs** [comment]
Please create a pull request from a branch in your fork. And please sign the the CLA (https://jitsi.org/icla) if you haven't already done so.

**Comment by powerpbx** [comment]
Is this the place for issues?  We haven't signed the CLA so we just want to point out the issue for now?
