### ISSUE TITLE
pjsip can't login jitsi

### ISSUE THREAD

**Issue by ishtarmms** [jitsi/jitsi#237]
hello, I am use pjsip in my pbx,
When I'm login, I got this error in my pbx log

[2016-03-14 17:38:37] NOTICE[2225] chan_sip.c: Registration from '"9806" <sip:9806@192.168.0.250>' failed for '192.168.0.31:5062' - Wrong password

But I'm sure my password is not wrong

and I got log in jitsi
From: "9806" <sip:9806@192.168.0.250>;tag=a63af4fb
To: "9806" <sip:9806@192.168.0.250>;tag=as113d4919
Call-ID: 6ecd4f4f1f889bb24a3376b2e8d1eda9@0:0:0:0:0:0:0:0
CSeq: 8 REGISTER
Server: FPBX-12.0.70(13.7.2)
Allow: INVITE,ACK,CANCEL,OPTIONS,BYE,REFER,SUBSCRIBE,NOTIFY,INFO,PUBLISH,MESSAGE
Supported: replaces,timer
Content-Length: 0

'ɦVX񆠓                 E ɔ  5񱠠  ( 򓆓ā񠠒EGISTER sip:192.168.0.250:5062 SIP/2.0
Call-ID: 6ecd4f4f1f889bb24a3376b2e8d1eda9@0:0:0:0:0:0:0:0
CSeq: 9 REGISTER
From: "9806" <sip:9806@192.168.0.250>;tag=a63af4fb
To: "9806" <sip:9806@192.168.0.250>
Max-Forwards: 70
User-Agent: Jitsi2.9.5500Windows 8
Expires: 600
Contact: "9806" <sip:9806@192.168.0.31:5062;transport=udp;registering_acc=192_168_0_250>;expires=600
Via: SIP/2.0/UDP 192.168.0.31:5062;branch=z9hG4bK-393436-9e5bb3815823dfe6c5575c4ac5333287
Content-Length: 0

'ɦVX񆠟  _               E Qɔ  5𥀨 򠠠 ēƂ=  SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 192.168.0.31:5062;branch=z9hG4bK-393436-9e5bb3815823dfe6c5575c4ac5333287;received=192.168.0.31;rport=5062
From: "9806" <sip:9806@192.168.0.250>;tag=a63af4fb
To: "9806" <sip:9806@192.168.0.250>;tag=as113d4919
Call-ID: 6ecd4f4f1f889bb24a3376b2e8d1eda9@0:0:0:0:0:0:0:0
CSeq: 9 REGISTER
Server: FPBX-12.0.70(13.7.2)
Allow: INVITE,ACK,CANCEL,OPTIONS,BYE,REFER,SUBSCRIBE,NOTIFY,INFO,PUBLISH,MESSAGE
Supported: replaces,timer
WWW-Authenticate: Digest algorithm=MD5,realm="asterisk",nonce="4fc9fcf6"
Content-Length: 0

anyone know what happen?and how can I do?

**Comment by dulm-today** [comment]
The first REGISTER message do not contain the WWW-Authenticate field, so the SIP server return statuscode 401 with WWW-Authenticate: Digest algorithm=MD5,realm="asterisk",nonce="4fc9fcf6".
You should retransmit the REGISTER message that contain the WWW-Authenticate field and add value of "response" to it. the "response" is calculated by MD5 with realm, nonce, cnonce, password etc.

**Comment by ibauersachs** [comment]
Just tried Jitsi 2.9.5513 against FPBX-13.0.119(13.8.2) and PJSip is working fine (UDP and TLS).
