### ISSUE TITLE
Video is muted in Chrome

### ISSUE THREAD

**Issue by Sladoeg** [jitsi/jitsi#238]
Hello, there,
I am getting no audio from remote client in Chrome 49.0.2623.87m.
The remote client is on Raspberry Pi 2 and USB Camera with Microphone with UV4L WebRTC extension installed.
In Chrome Dev Tools --> Console I have found the following:
`pi video is now active <video muted=?"true" autoplay id=?"remoteVideo_stream_label" src=?"blob:?https%3A/?/?meet.jit.si/?73ec218e-3384-43bc-a904-ce2cf9a2bd8f" style=?"display:? block;? visibility:? hidden;?">?</video>? DataChannels.js:187selected endpoint changed: pi https://meet.jit.si/libs/modules/UI/videolayout/VideoLayout.js:360`
How can I fix Video muted issue? Thank you.

**Comment by damencho** [comment]
This is not jitsi issue. Please use the mailinglist. Do not post issues in all projects.
