### ISSUE TITLE
Can't connect to facebook

### ISSUE THREAD

**Issue by Sequoia** [jitsi/jitsi#239]
I'm not sure what troubleshooting steps I'm missing but I delete my FB profile on Jitsi, re-add with username and password, and every time it says password is bad. Is there a step for setting up app specific passwords in Facebook that I'm missing?

**Comment by bgrozev** [comment]
Facebook does not provide an XMPP API anymore. They officially deprecated it years ago, and recently turned it off completely. It is not going to work with Jitsi and has been removed in the nightlies.
