### ISSUE TITLE
Do not use pre-compiled binaries

### ISSUE THREAD

**Issue by coypoop** [jitsi/jitsi#241]
There's nothing generating lib/native/freebsd and lib/native/freebsd-64, which contains just binary files.
I think that the rationale for this is pretty self-explanatory.

Ideally, do not download things from sourceforge over HTTP, too:
src/native/libjunbound/make-linux.sh:16-17
    wget -nc http://downloads.sourceforge.net/project/expat/expat/2.1.0/$expat.tar.gz
    wget -nc http://unbound.net/downloads/$unbound.tar.gz

(Similarly, make-mac.sh)

**Comment by ibauersachs** [comment]
We'll switch to dnssecjava when I find the time.
