### ISSUE TITLE
Russian language in Jitsi

### ISSUE THREAD

**Issue by rikishi0071** [jitsi/jitsi#246]
Hi everyone, I glad to say that Jitsi was fully translated into Russian two weeks ago! But there's no commit yet! We'd like to use fully translated version of Jitsi, but now it is impossible because when I get a source code, the translation file is still OLD!

http://translate.jitsi.org/ru/sip_communicator/notices

Please tell me, how can I get or build a fully russian translated version of Jitsi?

**Comment by ibauersachs** [comment]
I just committed the translation from Pootle, should be available in the next nightly build.
