### ISSUE TITLE
Problem with Openfire 4.0.2

### ISSUE THREAD

**Issue by qutorial** [jitsi/jitsi#251]
After the server version changed, the new Smack library is used in it, the one in my jitsi (maybe an old one, 2.8.5426) has a packet parsing problem in Smack and is not connecting to the server anymore.

**Comment by ibauersachs** [comment]
The 2.9.5513 can connect to Openfire 4.0.2, so nothing I can do for 2.8 anymore. However, I don't think this has anything to do with Smack, it's more likely a problem with the supported TLS ciphers. But I cannot say for sure without the logs.
