### ISSUE TITLE
Clicking the hang up button does not hang up

### ISSUE THREAD

**Issue by ddsol** [jitsi/jitsi#253]
When I'm in a video call and I'm ready to hang up I tend to reach for the hang up button. This is a mistake because the button never hangs up my call.

Instead it displays a dialog that asks me to rate my experience in stars. I always rate it the lowest because I'm very frustrated right then because disconnecting my call is not working. Then when I'm done rating the lowest, I am presented with some kind of survey asking me all kinds of questions. In the meantime, I'm still in a video call that I am trying to get out of. So I wise up and close the window.

Please remove the hang up button because it doesn't work and it's misleading. Instead, just let user close the tab.

Alternatively it may be a good idea to just hang up the call and give the user a survey after the call is already disconnected. This would allow for survey results that are not heavily skewed by frustration.

**Comment by damencho** [comment]
This is not a jitsi issue, it is a jitsi-meet one (actually lib-jitsi-meet). Could you please use the mailinglist before opening issues.

This is a known issue and we are working on it with callstats guys where the stats and feedback is landing currently.
