### ISSUE TITLE
Sign binaries with SHA256

### ISSUE THREAD

**Issue by ibauersachs** [jitsi/jitsi#254]
Since Jan 16 Windows demands SHA256 signatures and ignores the SHA1 signature.

**Comment by jitsi-developers** [comment]
on Debian testing already complaints since several weeks (I have posted
it also previously):

http://download.jitsi.org/deb/unstable/Release.gpg: Signature by key
040F57608F84BAF1BF844A62C697D823EB0AB654 uses weak digest algorithm (SHA1)
