### ISSUE TITLE
disconnected from server

### ISSUE THREAD

**Issue by Awibow** [jitsi/jitsi#255]
Hi All,

I'm using openfire as my XMPP server.
but sometimes my jitsi client can't connect to server anymore.
and the error message from manager.my.domain.name : 
" You are using an invalid client, and therefore will be disconnected.  Please ask your system administrator for client choices ".

Previously, it was ok and everything is working well.
anyone have the same issue ? and how to fix this ?

Thanks.

**Comment by ibauersachs** [comment]
Jitsi can connect perfectly fine to Openfire 3.10.x and 4.0.2. Maybe your sysadmin limited the allowed clients with the Client Control plugin.

**Comment by Awibow** [comment]
Hi Ibauersachs,
thank you for your explanation.
I will crosscheck this to my sysadmin.

**Comment by birender** [comment]
I have the facing similar type of problem.
When a remote user connects then it shows error "Unfortunately, something went wrong."
https://webrtc.ajdevdemos.com/Hard
