### ISSUE TITLE
help for fmj source for android (r36)

### ISSUE THREAD

**Issue by xialion** [jitsi/jitsi#262]
i am try to recompile fmj.jar for android, i found fmj source in libjitsi, but the version is not correct. i need the fmj source for android(r36), the author is lyubomir.

please help, thank you very much.
email: 190029150@qq.com

**Comment by mbulamboma** [comment]
Did you found the solution?

**Comment by ibauersachs** [comment]
https://github.com/jitsi/fmj is the source used in Jitsi Desktop, the original SVN repo is at SourceForge: https://sourceforge.net/projects/fmj/
