### ISSUE TITLE
Unable to move incoming call window

### ISSUE THREAD

**Issue by bdodroid** [jitsi/jitsi#263]
I'm unable to move the incoming call window and it sits right in the center of my screen and hovers over top of everything. 
Can you tell me where in the code the incoming call window is getting set so I can change that? 
Its extremely annoying if you get multiple calls.

**Comment by bdodroid** [comment]
Found it. You can move the incoming call window by modifying a section in 
/Git/jitsi/src/net/java/sip/communicator/impl/gui/main/call/PreCallDialog.java

So if you want it to appear in the bottom right corner like I did you can replace this:
> if (visibleWindows.isEmpty())
> {
>    
>     // No existing visible windows displayed. Just center this one.
>     preCallWindow.setLocationRelativeTo(null);
> }

with this

> if (visibleWindows.isEmpty())
> {
> 
>     GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
>     GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
>     Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
>     int x = (int) rect.getMaxX() - preCallWindow.getWidth();
>     int y = (int) rect.getMaxY() - (preCallWindow.getHeight() + 40);
> 
>     preCallWindow.setLocation(x, y);
>     // No existing visible windows displayed. Just center this one.
>     //preCallWindow.setLocationRelativeTo(null);
> }

**Comment by ibauersachs** [comment]
Should be fixed with #279
