### ISSUE TITLE
Make and Deploy Failure

### ISSUE THREAD

**Issue by breebee** [jitsi/jitsi#264]
I have followed step by step to configure eclipse from the documentation and it seems there is an ant make issue i have no clue how to resolve. I clean project and rebuilt the project before make and deploy and this is the error im receiving.

Buildfile: C:\JITSI\Jitsi Master\jitsi\build.xml
clean-bundle-repositories:
init:
-pre-version:
version:
    [javac] Compiling 3 source files to C:\JITSI\Jitsi Master\jitsi\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] 1 warning
     [echo] Jitsi version 2.9.0.build.by.SVN
-pre-googlecontacts-none:
     [copy] Copying 1 file to C:\JITSI\Jitsi Master\jitsi\src\net\java\sip\communicator\impl\googlecontacts
-pre-googlecontacts:
compile:
    [javac] Compiling 2 source files to C:\JITSI\Jitsi Master\jitsi\classes

BUILD FAILED
C:\JITSI\Jitsi Master\jitsi\build.xml:301: Error running javac.exe compiler

Total time: 1 second

**Comment by ibauersachs** [comment]
This is not a Jitsi issue. See e.g. http://stackoverflow.com/questions/3394369/getting-error-running-javac-exe-compiler-message-while-using-ant-in-eclipse on how to properly configure your Eclipse.
