### ISSUE TITLE
debian packaging: alternative java packages

### ISSUE THREAD

**Issue by fommil** [jitsi/jitsi#265]
jitsi depends on the standard debian openjdk packages, but there is a far superior alternative to debian's "mystery meat" openjdk[1] in the form of Azul's Zulu: https://www.azul.com/products/zulu/

Azul contribute significantly towards OpenJDK development, so I trust them far more than the Debian packagers in order to deliver high quality OpenJDK binaries.

It would be good if your `.deb`s allowed for the debian java or a zulu java, so that when installing jitsi it doesn't install in the debian openjdk if zulu is available.

Sorry for bypassing the mailing lists for this, it's a simple feature request rather than a bug (also I haven't used a mailing list in about 15 years, so it feels very alien to me to do that).

[1] there is justification to say this. Azul follow a rigorous release process when they cut a version of OpenJDK and make release notes available, linking back to bug reports against the Java issue tracker, after being instrumental in fixing many of those bugs. There is no such process in Debian and appears to be against arbitrary mercurial commits.

**Comment by fommil** [comment]
details, I think you're depending on `default-jre` but depending on `java-runtime` might be all that is needed.

**Comment by fommil** [comment]
(I've also asked Azul to provide `default-jre` which might be another way to fix this)

**Comment by ibauersachs** [comment]
Neither Debian nor Ubuntu have a package "java-runtime".

**Comment by fommil** [comment]
(btw, jitsi is awesome... I just discovered it today. It could revolutionise how we do remote collaboration in ENSIME!)

**Comment by fommil** [comment]
oh wow, thank you! I'm going to try this out very soon.
