### ISSUE TITLE
Incorrect SDP Sent with OPUS

### ISSUE THREAD

**Issue by leamingrad** [jitsi/jitsi#266]
When I change the list of encodings so that only OPUS is selected, the following SDP is sent:

nonev=0
o=3162030020-jitsi.org 0 0 IN IP4 192.168.80.10
s=-
c=IN IP4 192.168.80.10
t=0 0
m=audio 5020 RTP/AVP 96
a=rtpmap:96 opus/48000/2
a=fmtp:96 usedtx=1
a=ptime:96 20
a=extmap:1 urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:2 urn:ietf:params:rt

The "a=ptime:96 20" is invalid, as jitsi appears to be prepending the RTP payload number before the ptime value.

This was seen when using version 2.9.5519. Please let me know if there are any diagnostics required.

**Comment by bgrozev** [comment]
Thank for the report. Can you test if this fixes it? https://github.com/jitsi/libjitsi/pull/167

**Comment by leamingrad** [comment]
In that case, I will wait for the correct fix to make it in. Out of interest, how do I test a patch? Do I just wait for the next nightly build?

**Comment by bgrozev** [comment]
You would have to re-build the project (or at least libjitsi in this case).

**Comment by leamingrad** [comment]
Ah. Are there instructions on how to do this somewhere (I have never compiled it before)?

**Comment by peerasan** [comment]
To compile libjitsi  is really good way???
