### ISSUE TITLE
OPUS "Use DTX" setting is ignored in 200 OK messages

### ISSUE THREAD

**Issue by leamingrad** [jitsi/jitsi#269]
I have disabled the "Use DTX" setting for OPUS in my jitsi client. However, when the client receives an invite, it replies with the following SDP in its 200 OK:

```
v=0
o=3162030020-jitsi.org 0 0 IN IP4 192.168.80.10
s=-
c=IN IP4 192.168.80.10
t=0 0
m=audio 5089 RTP/AVP 97
a=rtpmap:97 opus/48000/2
a=fmtp:97 usedtx=1
a=ptime:97 20
```

In particular, the `usedtx=1` header should not be there as that is indicating the use of DTX. This was seen when using version 2.9.5519

**Comment by leamingrad** [comment]
On further investigation, this is on INVITEs as well as 200 OKs

**Comment by ibauersachs** [comment]
You need to restart Jitsi for the Use DTX setting to become effective.
