### ISSUE TITLE
Cannot enter username in Jitsi

### ISSUE THREAD

**Issue by Tombert** [jitsi/jitsi#284]
Hello!  On NixOS, when I install Jitsi, I cannot enter in my username.  Consequently, I can't figure out how to connect.  Here is a screenshot: 

![snapshot1](https://cloud.githubusercontent.com/assets/2027925/16716767/1c70ff48-46d4-11e6-9fcd-696af4e24fe2.png)

**Comment by ibauersachs** [comment]
Sounds like you're using the old broken version from the Ubuntu 14.04 repository. Anyway, this is either a packaging and/or a Java problem that we can't do anything about.
