### ISSUE TITLE
Jitsi offers two different AES keys for SRTP with the same tag

### ISSUE THREAD

**Issue by rlupton20** [jitsi/jitsi#286]
This possibly leads to confusion of keys between endpoints.

RFC: "The tag MUST be unique among all crypto attributes for a given media line".

Taken directly from SIP messages:

...SIP INVITE...
User-Agent: Jitsi2.8.5426Windows 7
Content-Type: application/sdp
Content-Length: 723

v=0
o=*****************
s=-
c=****************
t=0 0
m=audio 5016 RTP/SAVP 0
a=rtpmap:0 PCMU/8000
a=extmap:1 urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:2 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=rtcp-xr:voip-metrics
a=crypto:1 AES_CM_128_HMAC_SHA1_32 inline:0l9qLX1vH6S4eLZ6MUf+VE34GM9QvakT0XVhPkXU
m=video 5018 RTP/SAVP 96 99
a=recvonly
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=4DE01f;packetization-mode=1
a=imageattr:96 send * recv [x=[0-1920],y=[0-1080]]
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=4DE01f
a=imageattr:99 send * recv [x=[0-1920],y=[0-1080]]
a=crypto:1 AES_CM_128_HMAC_SHA1_32 inline:HQz4FbHe+FUM6jmHn/ZgXZVDWuWKjAKiAPyokWEd

**Comment by ibauersachs** [comment]
> "The tag MUST be unique among all crypto attributes **for a given media line**".

These are for different media lines. The first is for audio, the second for video.
