### ISSUE TITLE
Jitsi not showing online/away status correctly

### ISSUE THREAD

**Issue by basildane** [jitsi/jitsi#288]
I have multiple instances of Jitsi that I cannot get to show status correctly.  It shows the user is Online, always.

I have "change status while away" checked, 10 minutes.
User is running Windows 10 Pro.
Jitsi 2.9.5500.
XMPP, ejabberd server.

I have tried reinstalling Jitsi.
I have tried manually changing her status to Away and back to Online.
But then it stays as Online permanently.

**Comment by ibauersachs** [comment]
Requires jitsi/libjitsi#234
