### ISSUE TITLE
Default presence shows as "In a Meeting"

### ISSUE THREAD

**Issue by gatsit** [jitsi/jitsi#289]
The default presence of one of my users shows as 'In a Meeting'.  It happens as soon as the user logs in and they have to change it to 'Online' manually.

Windows 10 Pro
Jitsi for XMPP with Openfire backend server

I have reinstalled multiple versions of Jitsi with no success.  Please advise.

**Comment by ibauersachs** [comment]
If the affected user has Outlook installed, it most likely is due to a calendar item. You can disable the integration with Outlook in Tools->Options->Advanced->External Contacts->Address book.

**Comment by gatsit** [comment]
Hi, 

Thanks for the response.  Unfortunately, that did not correct the issue.  The path is a bit different:  Tools->Options->Advanced->Contact Sources->Address Book.  The global status is still 'Extended Away' and the Jabber status still shows 'In a Meeting'.  If there is anything else I can do, please let me know.

**Comment by j-c-r** [comment]
Hi,

we need also the possibility to disable the sync with the Outlook Calendar. We d'ont want jitsi to set automatically "In a Meeting" when a person has an item in the Outlook Calendar. The search in the adress book is disabled, but has no effect on the status set.

Windows 10
Jitsi with Openfire

**Comment by ibauersachs** [comment]
There's currently no UI for this setting, but you should be able to set the property `net.java.sip.communicator.service.calendar.FreeBusyStatus.disabled` to `false` to disable the calendar integration.

**Comment by j-c-r** [comment]
Hi,

thank you very much. This works fine, but you have to enable the property not disable.

Thanks

**Comment by ibauersachs** [comment]
Yes, thanks. I've updated the comment, and build 5556 now has a UI option as well.
