### ISSUE TITLE
Sipgate account with standard preferences loses audio after third outgoing call

### ISSUE THREAD

**Issue by daTscharlie** [jitsi/jitsi#291]
jitsi-2.9.5532-x64 installed on Windows 10 Redstone lose audio if local port reaches 5008 or higher. Router from Compal with working UPnP. A restart of the application solves this issue. Next call is port 5000, then 5004 -> everything OK, third call with 5008 or higher and the issue is back.

**Comment by ibauersachs** [comment]
I'm unable to reproduce this with SIP. If your account is indeed SIP, I'm tempted to blame the router or your VoIP provider. Please reopen if you're talking about an XMPP account.
Also UPnP is not used with SIP,
