### ISSUE TITLE
How to setup Jitsi to work with an IVR system?

### ISSUE THREAD

**Issue by piejanssens** [jitsi/jitsi#292]
I don't want to setup an IVR system, I just want to be able to use one.
Right when I call some service number and I get connected through an IVR, whatever button on the keypad of Jitsi I press nothing goes through.

**Comment by ibauersachs** [comment]
Try changing the DTMF method in Tools->Options->Accounts->your SIP account->Connection. E.g. RTP (RFC2833 / RFC4733) works with Asterisk.

**Comment by piejanssens** [comment]
Tried all DTMF methods, calling worked with any, but even with RTP I couldn't use IVR.

**Comment by ibauersachs** [comment]
Sorry, no idea what your SIP provider/server needs for this to work. Please ask your provider/admin what settings they require.

**Comment by piejanssens** [comment]
OVH is my provider. I'll ask them.

**Comment by ibauersachs** [comment]
A quick Google search for "ovh sip dtmf" returns plenty of problems. Not sure if you speak French, but: https://forum.ubuntu-fr.org/viewtopic.php?id=1275691

Basically, select Inband as DTMF method and make sure that "telephone-event/8000" is enabled in the list of codecs.

I'm closing this issue as it seems to be an OVH speciality.
