### ISSUE TITLE
Yahoo messenger accounts no longer connect in Jitsi

### ISSUE THREAD

**Issue by gradinaruvasile** [jitsi/jitsi#293]
After the August 31 Yahoo messenger changes, Jitsi no longer connects to Yahoo.
This is the message that pops up, i am sure it presents the wrong reasons:

"You have have been disconnecting and reconnecting to the server too fast. The following account: User name: gradinaruvasile, Server name: yahoo.com is temporarily banned and would have to wait a bit before trying to login again."

I suppose the right reason would be the shutting down of the old messenger infrastructure.

Will this be addressed in Jitsi, either by updating the yahoo conmector to the new version (something like [funyahoo](https://github.com/EionRobb/funyahoo-plusplus) maybe) or removing this option entirely?

**Comment by gradinaruvasile** [comment]
Today it connected again, but only to serve the following message:

"Yahoo Messenger has been upgraded and no longer works with older versions or third party applications. To continue using Yahoo Messenger, please download the newest version at 
https://messenger.yahoo.com/download"

**Comment by ibauersachs** [comment]
Hm. According to the FunYahoo-Link, this would basically mean to write a completely new protocol. Unless someone steps in to do this, it means that the protocol will be removed from Jitsi.
