### ISSUE TITLE
Attended Call Transfer Breaks

### ISSUE THREAD

**Issue by anis-bedhiafi** [jitsi/jitsi#297]
Hello,

I have a problem with the attended call transfer.
I am using Freeswitch as a server and Jitsi revision 2.8.5426 as a client.

Ok on Freeswitch I could do an attended transfer using only DTMF.
Here is how it works:

1- Customer Calls in
2- Agent A picks up
3. Agent A wants to speak with his colleague Agent B. From his keypad, Agent A can press *3 and then enters agent_B_extension and confirms with #
4. Now Customer is put on Hold and Agent B extension is ringing.
5. Now here is the different options for Agent A which he can do by pressing a certain digit on his dialpad:

'0'	it will convert the call to three-way conference (After the last party answers the call)
'#'	to hangup the B leg and return you to the caller (After the last party answers the call)
'*'	it will hangup the B leg and bridge A to C (After the last party answers the call)
'#'	it will cancel the B leg and will return you the caller (Before the answer of the call by the last party)

Using Jitsi:

1- Customer Calls in
2- Agent A picks up
3. Agent A wants to speak with his colleague Agent B. So Agent A initiates a new call to agent B
4. Now Customer is put on Hold and Agent B extension is ringing.
5. Now when Agent A merges all calls together to make a 3-way conference, all calls come together and the conference works. But the problem is, when Agent A wants to leave the conversation, the whole call get terminated and disconnects all the participants. 

How can Agent A quit and leave Customer with Agent B. Just like when pressing 0 when using dtmf codes with freeswitch?

Thank you for any suggestion.

**Comment by ibauersachs** [comment]
Two things here:
- In an attended transfer, the participants are never joined to a conference (the * case in your Freeswitch scenario). Whatever the conference thing is called, it's not an attended transfer anymore.
- The conferences Jitsi is creating are client side, Freeswitch isn't involved at all. It's thus not possible to achieve the '0' scenario.

**Comment by anis-bedhiafi** [comment]
Thank you for clarifying the image.
