### ISSUE TITLE
Supported XEPs

### ISSUE THREAD

**Issue by mathiasertl** [jitsi/jitsi#298]
We at jabber.at provide [a list of recommended clients](https://jabber.at/clients/) for our users and show support for a few important XEPs. I couldn't find a list of supported XEPs for Jitsi, so my question is if you support:

* XEP-0027
* XEP-0167
* XEP-0198
* XEP-0280
* XEP-0313
* XEP-0352
* XEP-0357
* XEP-0363

Of course it would also be great if you could ping us about new versions for your client, especially if they improve support for the mentioned XEPs ;-)

greetings, Mati

**Comment by ibauersachs** [comment]
> XEP-0027
No, and that XEP is obsolete, so we never will.
> XEP-0167
Yes.
> XEP-0198
No.
> XEP-0280
Yes.
> XEP-0313
No. Prerequisite for OMEMO, we'd like to have it but lack resources.
> XEP-0352
No. This XEP is IMO directed towards mobile clients and the definition of being active or not is not as clear as on a mobile device.
> XEP-0357
No. Directed at mobile clients. Might make sense for Windows' connected standby mode, but no resources to even think about implementing it.
> XEP-0363
No. Interesting, but as a (public) server operator I'd have my doubts about what users are going to upload...

**Comment by mathiasertl** [comment]
@ibauersachs Thanks for the updates - I will update the info on our page right away.

On XEP-0363: We have it, quite a few other servers do as well. Conversations, Gajim, Monal and Profanity support it AFAIK. It's incredibly easy to implement. So you might consider that.
