### ISSUE TITLE
"Impersonating" other users in jitsi

### ISSUE THREAD

**Issue by fredericmohr** [jitsi/jitsi#299]
One of my colleagues stumbled over a (display?) bug in jitsi. Under certain circumstances, it appears that chat members can "impersonate" others. I don't think that this is a security issue, due to the required circumstances, but I haven't thought about all possible ways to (mis-)use this, so I might have overlooked something.

We just tried to repeat the problem on jitsi 2.8.5426 and it worked.

Steps to reproduce:
- open a 1-on-1 chat (aka Alice talks to Bob)
- Alice writes something, which shows up as 

```
alice@server date+time 
alice's message
```
- Alice hits the "up-arrow" key and changes her message (edit)

```
alice@server date+time 
alice's message (edited)
```
- Bob types something which shows up as 

```
bob@server date+time 
bob's message
```
- Alice type something which shows up in Bob's message box

```
bob@server date+time 
bob's message
alice's new message
```

As I said, I don't think this is a security issue, since 
- one can (apparently) only impersonate users that post right after an edit (so they have to be in the chat room)
- the actual post owner is correctly shown in the log files

I assume that this is just a display error.

![screenshot_20161019_163743](https://cloud.githubusercontent.com/assets/5955966/19524570/7518b908-961e-11e6-9945-95e1444b4c99.png)

**Comment by ibauersachs** [comment]
We know about that bug and it's a glitch in the last message edit functionality. It always seemed not important enough to spend time on it, given that resources are very limited and other open bugs affect whether the application can be used at all. Thanks for reporting it though.
