### ISSUE TITLE
Option to disable OSX notifications about other users typing XMPP messages

### ISSUE THREAD

**Issue by caitp** [jitsi/jitsi#304]
The notification disrupts workflow and occupies too much screen real estate, for something which is not particularly valuable.

<img width="359" alt="screen shot 2016-11-21 at 10 00 53 am" src="https://cloud.githubusercontent.com/assets/2294695/20487475/6c66ae4c-afd1-11e6-906c-3302f9cd91dc.png">

**Comment by bgrozev** [comment]
I think the "proactive typing notifications" event under Preferences->Events might control this.

**Comment by caitp** [comment]
You're right, it does seem to work. It would be nice to make this easier to find, but closing as working as intended.
