### ISSUE TITLE
Jitsi 2.8&2.9 problem with opensips 2.2.2

### ISSUE THREAD

**Issue by cr7xiaoyu** [jitsi/jitsi#305]
Jitsi 2.8&2.9 problem with opensips 2.2.2

PC in home , ip from router with dhcp , PC can visit Internet
Server in office , it has a internet ip address ,server only install opensips(without rtpproxy and mediaproxy).
 
Problem1:
I use jitsi in PC1 , it can log in server,
But I use jitsi in PC2 and PC3 , it can’t log in server. 
Three PC has use the difference user name.
If I close jitsi in PC1 for some minutes , jitsi in PC2 maybe can log in.

Problem2:
I use jitsi in PC1 ,It can log in server , then I use command to show status,why the contact has a inside ip?
Contact:: sip:150@192.168.0.140:5060;transport=udp;registering_acc=xxx_xxx_xx_xxx Q=
When linphone log in,the contact is a outside ip 
“Contact:: sip:131@123.113.33.172:20729;transport=udp Q= “

I install opensips in PC1 , jitsi in PC2 and PC3 is ok!

the picture and cfg in word,
https://mega.nz/#!0QAg0CDZ!BWyOO0wSF6PqJvzWzAubV58EerabeCCsaPBT3T-UvLE

**Comment by csabaradi** [comment]
Check https://voipmagazine.wordpress.com/2014/10/01/opensips-provisioning-for-a-simple-sip-call/.
See highlighted the "Firewall rules".

**Comment by ibauersachs** [comment]
This looks a lot to be a server configuration issue. Anyway, 2.8/2.9 aren't supported anymore.
