### ISSUE TITLE
Update Smack to 4.2

### ISSUE THREAD

**Issue by DanScharon** [jitsi/jitsi#306]
Volunteer(s) needed to update Jitsi to use Smack 4.2.

Other issues, e.g. #205 and #300 depend on this.

There is already a branch to start from: https://github.com/jitsi/jitsi/tree/smack4-2

**Comment by Flowdalic** [comment]
With my Smack maintainer hat on: I'm happy to assist. We have just recently upgraded Spark from an ancient Smack version (< 4.0) to Smack 4.1.9. That experience told us that

- The longer you wait, the harder it gets
- You should expect some regressions
- Use a build system that is able to consume Maven artifacts.

So you probably want an extended beta period where Jitsi+Smack4.2 is tested, while the changes to the stable Jitsi variant are kept at a minimum. And then do the switch.

Also you really should consider using a build system which is able to consume Maven artifacts. Smack is highly modular these days, and has also many dependencies, of which some also have dependencies. So there are dependencies and transitive dependencies everywhere, which you don't want to add manually as jars. I personally would consider the current build system of Jitsi a blocker of the Smack version bump, and switch to something else (Maven, Gradle, sbt, …) first. I now it's not easy, but IMHO definitely worth it.

**Comment by ibauersachs** [comment]
Thanks Florian. We'll try to release 2.10 around Fosdem, which opens the window for a migration. Maybe you're around at Fosdem and we can discuss some of the issues you ran into?

- Except for Jitsi Desktop, all other projects are already using Maven. It makes sense to migrate Jitsi Desktop too, but this will be a time consuming task which I'm not sure is worth it as a whole. It might make more sense to e.g. embed Ivy into Ant than lots of Ant scripts into the maven-ant-plugin. But I'm open to suggestions.
- Modularity of Smack: the effort of getting Jitsi into Debian is ongoing. Is Smack available there as one or multiple packages to depend on? If not, any plans to package it?

**Comment by Flowdalic** [comment]
> Maybe you're around at Fosdem and we can discuss some of the issues you ran into?

I'll be a FOSDEM. Looking forward seeing you there.

**Comment by ibauersachs** [comment]
The branch smack4-2 compiles against Smack 4.2-rc2. It won't work yet, I haven't even tried to launch Jitsi. tbc.

**Comment by reavertm** [comment]
Hopefully this will solve issue with our corporate Cisco Jabber server (we use custom SSO forwarder/proxy to plug jitsi there) introduced with ecf3954dd7f738e6f828da861788d9b3760b8468, which results with "IQ must be of type 'set' or 'get'..." exception.

**Comment by Flowdalic** [comment]
> Hopefully this will solve issue with our corporate Cisco Jabber server (we use custom SSO forwarder/proxy to plug jitsi there) introduced with ecf3954, which results with "IQ must be of type 'set' or 'get'..." exception.

Thanks for your feedback. But without further, more detailed information chances are low that anyone will be able to answer this. Do you have reported the issue? Was there a bug/issue created somewhere? Do you have an XMPP trace which was collected when this happened?

**Comment by reavertm** [comment]
Backtrace starts with:

`[java] 2017-04-13 17:36:32.672 SEVERE: [535] org.jivesoftware.smack.Connection.notifyListener() IQ must be of type 'set' or 'get'. Original IQ: <iq id="JXr0u-2" from="name.surname@host.com/jitsi" type="result"><query xmlns="jabber:iq:roster"><item jid="name.surname@host.com" name="name.surname@host.com" subscription="to"><group>Contacts</group></item><item jid=`

then follows with a lot of <item> ..</item> for each known contact. Do you expect it's smack API misuse (so that I should report it here) or smack lib issue (so I should report it upstream)?

**Comment by pdefert** [comment]
Is there a build to do tests?

**Comment by ibauersachs** [comment]
I'll push some updates tonight, but I can guarantee you that it won't work for much more than being shown online.

**Comment by ibauersachs** [comment]
I've updated the branch. As I said, don't expect much. I need to update some dependent libraries to Smack 4.2 first (i.e. Jingle Nodes, maybe some others too).

**Comment by ibauersachs** [comment]
@Flowdalic In case someone is interested in JingleNodes for OpenFire: https://github.com/jitsi/jinglenodes/tree/jitsi-smack4-2

**Comment by Flowdalic** [comment]
Thanks @ibauersachs :)

Also FYI there is a bug in 4.2.0 which in rare cases makes Smack not detect IQ replies. If you see ResponseTimeoutExceptions as result of an IQ request while seeing the reply in the debugger, then it's likely that you hit that. It's already fixed in 4.2.1-SNAPSHOT.

**Comment by ibauersachs** [comment]
Yai, chat and a basic Jingle call is working.

@Flowdalic Thanks for the IQ reply hint, haven't seen or noticed it yet. What I've run into a few times now however is the bug mentioned by @bbaldino in igniterealtime/Smack#124.

I tried to add your XMPP contact as I'd have some design questions. Any chance you've got some time to chat about these?

**Comment by pdefert** [comment]
and file transfert works with good speed on local network ?

**Comment by ibauersachs** [comment]
@pdefert This doesn't have anything to do with file transfers. It may become easier to implement file transfer over Jingle with the update.

**Comment by ibauersachs** [comment]
@reavertm see #362

**Comment by marclaporte** [comment]
And now Smack 4.3:
https://github.com/igniterealtime/Smack/releases/tag/4.3.0

**Comment by GNUDimarik** [comment]
@ibauersachs and @damencho can this issue be closed by merging of smack4-2 to masteR?
