### ISSUE TITLE
XMPP: cannot connect via port 443

### ISSUE THREAD

**Issue by bugmenot2** [jitsi/jitsi#308]
I'm behind firewall so I've tried changing port to 443. But it seems Jitsi (v2.8.5426) still cannot connect to the server (no error message shown). At the same time Pidgin works.

**Comment by ibauersachs** [comment]
Jitsi doesn't support BOSH (XMPP over HTTP) yet. So if you change the port from 5222 to 443 and the server supports BOSH, then it obviously won't work.
Even if the server listens to plain XMPP on port 443, a restrictive firewall likely inspects the traffic, sees that it isn't http and denies the connection.
