### ISSUE TITLE
Portuguese language issue

### ISSUE THREAD

**Issue by kokbira** [jitsi/jitsi#310]
Trying to close a Jitsi chat window with not sent message, a popup appeared missing correct translation.

Which message appeared:
"Voçê está tentando fechar um chat com uma mensagem não enviada. Tem a certeza que quer fechar este chat?"

Which text would be correct:
"Você está tentando fechar um chat com uma mensagem não enviada. Tem certeza de que quer fechar este chat?"

![image](https://cloud.githubusercontent.com/assets/877757/22023248/216230a6-dca4-11e6-93aa-35b1acf6ff59.png)

**Comment by ibauersachs** [comment]
Please update the translation in [Pootle](http://translate.jitsi.org/projects/sip_communicator/), our translation server.

**Comment by jitsi-developers** [comment]
Hi,

On 17/01/2017 08:01, kokbira wrote:
> Trying to close a Jitsi chat window with not sent message, a popup
> appeared missing correct translation.
>
> Which message appeared:
> "Voçê está tentando fechar um chat com uma mensagem não enviada. Tem a
> certeza que quer fechar este chat?"
>
> Which text would be correct:
> "Você está tentando fechar um chat com uma mensagem não enviada. Tem
> certeza de que quer fechar este chat?"

Thank you for taking the time to report this!
Our translations are managed on https://translate.jitsi.org
You can create an account there and make the fix yourself (note that it 
will not immediately appear on meet.jit.si). If you don't want to do 
this let me know and I will make the fix above for you.


Boris

**Comment by kokbira** [comment]
Done ;)
