### ISSUE TITLE
Is Jitsi client still maintained?

### ISSUE THREAD

**Issue by uportalis** [jitsi/jitsi#313]
Hi

According to Jitsi website, the last version of the Jitsi client was release on Q1 2013 and the next version is planned for 2015 (see https://jitsi.org/Development/Roadmap). And we are in 2017.
By the way I can see (very) few commits on GitHub.

Is Jitsi client still maintained? Is is planned to release in the future?

rgds,
Louis

**Comment by ibauersachs** [comment]
http://lists.jitsi.org/pipermail/users/2017-January/012121.html
