### ISSUE TITLE
Camera shows only black rectangle

### ISSUE THREAD

**Issue by lbcp** [jitsi/jitsi#314]
Hi,
I am using jitsi with windows 10 and installed the latest nightly.
VoIP (using XMPP) works fine and I also receive an Video image from my contacts. However, my own camera from my laptop (ASUS T300) does not work at all. The camera light is on but I cant see myself. Instead only a black rectangle is shown.
Since it worked at first I think something is wrong with the codecs but I cant figure out what. I tried every video codec provided by jitsi but cant see any image. Maybe the changes Microsoft made with the anniversary update creating these problems.
Other video programs like Skype and FreeTrack are working.

I hope I was able to explain the issue sufficiently and someone could fix this issue.
Best,
lbcp

**Comment by ibauersachs** [comment]
This is caused by the new size check in jitsi/libjitsi@5b3412e8d22e2014be2f051719e1e71d5ea5def7, which is only necessary when `flip` is true. Fix to follow sometime this week.
