### ISSUE TITLE
Click-to-Dial / SIP URI Fails

### ISSUE THREAD

**Issue by UmbraChimera** [jitsi/jitsi#315]
If you click a SIP link in the latest version, or newest nightly, Jitsi will be unable to complete the call because it will attempt to dial  sip5551234567 instead of 5551234567. This obviously results in every call failing.

**Comment by UmbraChimera** [comment]
Question about this, @ibauersachs, do you know of a version of Jitsi I can deploy currently that has neither the Outlook 2016 issue or this new SIP URI issue? Or do I currently, need to pick between the two.

**Comment by ibauersachs** [comment]
I don't know when then sip: links broke, so I cannot answer that. If you don't need the Office integration, you can delete the files `Jitsi\native\jmso*.dll`. I'll try to look at this soon, so you should be able to use a 2.11 nightly.

**Comment by ibauersachs** [comment]
`tel:` and `callto:` URIs are working, btw.

**Comment by UmbraChimera** [comment]
Awesome, thank you so much. I'll let my agents know.

**Comment by UmbraChimera** [comment]
Oh they are? I'll try adding Jitsi to the registry for those protocols on one of my test machines. For some reason Jitsi still refuses to show as option for tel: for anyone with Windows 10. Thanks for the tip!

**Comment by ibauersachs** [comment]
Apparently I forgot to include one crucial registry item in the installer. It should be available in the next build (2.11.5554). If you can control your clients with GPO, you can add this for previous versions:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications]
"Jitsi"="Software\\Jitsi\\Capabilities"
```

**Comment by UmbraChimera** [comment]
Thanks, I'll do those updates, and grab that nightly.

**Comment by UmbraChimera** [comment]
Also, would it help if I can tell you which nightly broke sip links? I think I have it in my work notes somewhere.

**Comment by UmbraChimera** [comment]
2.9.5509 Should be close to the time.

**Comment by UmbraChimera** [comment]
It seemed to correlate to the same nightly update that fixed this: https://github.com/jitsi/jitsi/issues/159

**Comment by UmbraChimera** [comment]
Any updates on this yet?

**Comment by ibauersachs** [comment]
I haven't had time yet. Sometime next week maybe.
