### ISSUE TITLE
Incomming call popup - location on the screen

### ISSUE THREAD

**Issue by aprimorar** [jitsi/jitsi#319]
When there is an incoming call, an box appears in the middle of the screen.
I didn't find any option to change this.
I would like if the notification were on the left bottom corner...is that possible to do now? If isn't, may you implement that?

I use kubuntu 16.10:
Linux suporte03 4.8.0-38-generic #41-Ubuntu SMP Wed Feb 8 14:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ibauersachs** [comment]
It's not currently possible to change that. Please create a pull request if you want to add an option to configure this location.

**Comment by aprimorar** [comment]
I don't do java.
Is it possible to append to an implementation queue of yours?

Thanks.
