### ISSUE TITLE
Garbled text

### ISSUE THREAD

**Issue by fvbnx** [jitsi/jitsi#322]
Running W10 Pro 1607
Screencap of settings http://i.imgur.com/CaBPTgF.png
Add account http://i.imgur.com/DOBmsJL.png

**Comment by ibauersachs** [comment]
What language is that? (See the dropdown further down in the general options)

**Comment by fvbnx** [comment]
http://i.imgur.com/B0VZ90Z.png
http://i.imgur.com/43V0LQH.png
I've tried pressing everything in there. Don't know what to do.

**Comment by ibauersachs** [comment]
I don't know what's going on there. What's your system language?
If you can, please try to select one of the items that show a `100` at the far right, that should be one of the fully translated languages (English, German, Spanish (Hebrew and Bahasa Indonesia wrongly show up as fully translated too)).
