### ISSUE TITLE
Jitsi jitsi-2.10.5550 hangs on splashscreen during startup

### ISSUE THREAD

**Issue by EUFC19** [jitsi/jitsi#328]
tried updating jitsi software and jitsi crashed

installed using new installer ... same

![image](https://cloud.githubusercontent.com/assets/25921738/23155076/f5718bcc-f84b-11e6-9df9-da446cd034aa.png)

Stuck in a loop

**Comment by EUFC19** [comment]
tried delete %appdata%, reinstall, same issue faced

**Comment by ibauersachs** [comment]
Duplicate of #321
