### ISSUE TITLE
Edit HTML files in new version of Jitsi MEet

### ISSUE THREAD

**Issue by bamms** [jitsi/jitsi#330]
Installed the latest version. Been trying to locate the HTML files so I can make some editing but haven't been able to locate them. I know react.js might have been implemented, but please guide on how I can make UI changes. Searched for over 2 days and not found
Please help

**Comment by bamms** [comment]
Any assistance please

**Comment by saghul** [comment]
You are in the wrong repository, Jitsi Meet is here: https://github.com/jitsi/jitsi-meet :-)

**Comment by bamms** [comment]
Thanks
