### ISSUE TITLE
Error: Get session-id error when trying to login as host (focus user)

### ISSUE THREAD

**Issue by puetzstef** [jitsi/jitsi#332]
Hi,
I'm running jitsi on an Ubuntu 16.04 LTS server and nginx. I configured it with guest domain. When opening a meeting room as host the login fails with ther error message: Get session-id error: 
So opening a room as host does not work for me. I added my logs (jicofo, prosody and jvb).

Maybe there is a configuration error. I'm running the stable jitsi from the repository and used this guide to set it up:

https://github.com/jitsi/jicofo

The focus user was registered with the following command:

sudo prosodyctl register focus auth.meet.absglobalfactoring.de xxx

I hope someone can help me. If further information is needed I will do my best to provide it.

Greetings
Stefan

**Logs:**
[jicofo.txt](https://github.com/jitsi/jitsi/files/799277/jicofo.txt)
[jvb.txt](https://github.com/jitsi/jitsi/files/799276/jvb.txt)
[prosody.txt](https://github.com/jitsi/jitsi/files/799278/prosody.txt)
Chrome Webdeveloper Log during login:
![chromedeveloperloginlog](https://cloud.githubusercontent.com/assets/25301590/23305667/3b182bc6-faa0-11e6-89b0-c94522863e84.JPG)

Additionally here are my configs:

**Configs:**
[jicofo_config.txt](https://github.com/jitsi/jitsi/files/799394/jicofo_config.txt)
[jitsi_meet_config.txt](https://github.com/jitsi/jitsi/files/799393/jitsi_meet_config.txt)
[prosody_config.txt](https://github.com/jitsi/jitsi/files/799395/prosody_config.txt)
[jicofo_sip-communicator.properties.txt](https://github.com/jitsi/jitsi/files/799410/jicofo_sip-communicator.properties.txt)
[nginx_config.txt](https://github.com/jitsi/jitsi/files/799420/nginx_config.txt)

**Comment by ibauersachs** [comment]
This repository/issue tracker is for the Jitsi Desktop client. Please ask for help on the [mailing list](https://lists.jitsi.org).
