### ISSUE TITLE
Sometimes jitsi call show me error "ICE FAILED" in outside network

### ISSUE THREAD

**Issue by the-alone-maple** [jitsi/jitsi#340]
Hi ,ibauersachs,Jitsi is a great client,but sometimes I use itmake a call in outside network,it show me "ICE FAILED"error.
Is that my xmpp server need  to change some cofigurations?

**Comment by ibauersachs** [comment]
If clients are behind a NAT/firewall that doesn't allow direct connections, then the server must be running a Jingle Nodes relay. There's plugin for e.g. Openfire.

**Comment by the-alone-maple** [comment]
Ok，thanks for your anwser。
