### ISSUE TITLE
Jitsi not starting up on Win7

### ISSUE THREAD

**Issue by frankhorvat** [jitsi/jitsi#342]
Having an issue whereby application working for approx 1 week after install & config but now won't start - even after reboot of PC. 

Any ideas of where to look? Not keen to re-install but will do so if no suggestions help

**Comment by frankhorvat** [comment]
System Win7 32bit & Jitsi v2.10.5550

**Comment by ibauersachs** [comment]
Duplicate of #321

**Comment by frankhorvat** [comment]
I'm not getting any splash screen/window popping up but will try #321

**Comment by frankhorvat** [comment]
When I run the script you suggest in #321 - I get the following in the logfile
"......Error occurred during initialization of VMjava/lang/NoClassDefFoundError: java/lang/Object......." 
& attached is the Jna.jar file 
[jna.zip](https://github.com/jitsi/jitsi/files/863201/jna.zip)

**Comment by ibauersachs** [comment]
Okay, then it may not be the same problem. I would suggest you reinstall Jitsi, the error indicates a broken installation.
Reinstalling won't affect your accounts or history.

**Comment by ibauersachs** [comment]
Can you please try [build 5580](https://download.jitsi.org/jitsi/nightly/windows/) (or newer) and lets us know?

**Comment by ibauersachs** [comment]
No feedback, closing.
