### ISSUE TITLE
Project startup errors

### ISSUE THREAD

**Issue by chenshixiu** [jitsi/jitsi#343]
java.lang.UnsatisfiedLinkError: unsupported JNI version 0xFFFFFFFF required by E:\jitsiMasterTest\jitsi\lib\native\windows-64\jmsofficecomm.dll
How to solve this problem

**Comment by ibauersachs** [comment]
This is expected behavior in th dev-env. Read the source code around the thrown exception to change a registry key from jitsi.exe to javaw.exe

**Comment by chenshixiu** [comment]
what "read the source code around the thrown exception to change a registry key from jitsi.exe to javaw.exe"?
Where is the change?

**Comment by chenshixiu** [comment]
My system is Windows 7, jdk7, jre7. In making jitsi download the source code in eclipse to deploy, run times the 2017-03-22 11:33:14. 087 serious: [20] plugin. Msofficecomm. Messenger. < clinit > () 176 Couldn 't load jmsofficecomm. If you are was debugging, make sure that registry key HKLM \ SOFTWARE \ Microsoft \ Office \ [\ Wow6432Node] Outlook \ Call Integration \ IMApplication is set to the javaw exe. Unsupported JNI version 0 XFFFFFFFF required by E: \ Anna \ jitsiMasterTest \ jitsi \ lib \ \ jmsofficecomm native \ Windows - 64 DLL
Java. Lang. ExceptionInInitializerError and under Caused by: Java. Lang. RuntimeException: Java. Lang. UnsatisfiedLinkError: unsupported JNI version 0 XFFFFFFFF required by E: \ Anna \ jitsiMasterTest \ jitsi \ lib \ \ jmsofficecomm native \ Windows - 64 DLL
At net.java.sip.com municator. Plugin. Msofficecomm. Messenger. < clinit > (180) Messenger. Java:
... 7 more
Under Caused by: Java. Lang. UnsatisfiedLinkError: unsupported JNI version 0 XFFFFFFFF required by E: \ Anna \ jitsiMasterTest \ jitsi \ lib \ \ jmsofficecomm native \ Windows - 64 DLL
Can you tell me, how to solve these problems? What causes it? Thank you very much!!!!!!

**Comment by chenshixiu** [comment]
2017-03-23 09:48:11.888 严重: [961] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectUsingSRVRecords().912 No SRV addresses found for _xmpp-client._tcp.114.119.7.210
2017-03-23 09:48:12.768 严重: [961] util.account.LoginManager.run().442 Failed to register protocol provider. 
java.lang.ArrayIndexOutOfBoundsException: 0
How to solve this problem?

**Comment by chenshixiu** [comment]
Changes in the registry, “HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Office\Outlook\Call Integration\IMApplication”, Read the source code around the thrown exception to change a registry key from jitsi.exe to javaw.exe

**Comment by astuter** [comment]
What to do if "Call Integration" doesn't exists on given path. 

[Check out this link:](https://drive.google.com/file/d/1RCIOehvKEksztToFUqfSMqPokeX_AJ6q/view?usp=sharing)
