### ISSUE TITLE
SIP towards Telefonica O2 not working anymore

### ISSUE THREAD

**Issue by reavertm** [jitsi/jitsi#351]
We use SIP provided by Telefonica O2.
Jitsi is apparently unable to parse SIP URL starting with tag 5563 (3ce87cf04f5e5137f611c2a5e9339d62971456aa)
Last working SIP here is with revision 816b339f3298059f921ab10239cf09a7703b0c81.
Backtrace:
`[java] 2017-04-13 17:59:25.866 SEVERE: [496] impl.protocol.sip.ProtocolProviderServiceSipImpl.register().443 No address found for ProtocolProviderServiceSipImpl(<my_sipnumber>@CUST01-CUCM-SUB-03-CL3.<intranethost> (SIP))`
`[java] 2017-04-13 17:59:29.924 SEVERE: [563] impl.protocol.sip.ProtocolProviderServiceSipImpl.register().443 No address found for ProtocolProviderServiceSipImpl(<my_sipnumber>@CUST01-CUCM-SUB-03-CL3.<intranethost> (SIP))
`
^ this is with tag 5563, latest master version doesn't even attempt to connect to SIP server (incorrectly considering SIP configuration incomplete?) or at least such even is not logged

Configuration:
SIP id: `<my_sipnumber>@CUST01-CUCM-SUB-03-CL3.<intranethost>`
password: (my SIP password)
display name: (some display name, my `name.surname@<intranethost>`)
registrar: `CUST01-CUCM-SUB-03-CL3.<intranethost>`
port: 5060
authorization name: (my username)
client TLS certificate: none
[ ] bypass proxy security check....
[X] Configure proxy automatically (but doesn't work even if I explicitly define it)

(`<my_sipnumber>`, `<intranethost>` is stuff I had to scramble but works of course with 816b339f3298059f921ab10239cf09a7703b0c81 or with other SIP client)

**Comment by ibauersachs** [comment]
The commits you mentioned don't have anything to do with SIP, they only affect XMPP (which isn't even used in Jitsi Desktop, it's only there for the Videobridge).

Since the error message says there's no address for `CUST01-CUCM-SUB-03-CL3.<intranethost>`, please check if that is actually the correct server.

**Comment by ibauersachs** [comment]
No feedback, closing. Please provide logs if you want us to investigate this further.
