### ISSUE TITLE
Error on link pasting

### ISSUE THREAD

**Issue by imp1sh** [jitsi/jitsi#352]
When I try to paste something into a windows where I message text, every time I try to paste a link like such https://www.heise.de it throws an error.
German error message:
Diese Nachricht konnte nicht zugestellt werden
Zustellung der Nachricht ist fehlgeschlagen.

Typing a link works though.

OS X 10.11.6
Jitsi 2.10.5550
Copied by CMD + c
Pasted by CMD + v
Communication is encrypted with OTR.
This is REALLY annoying.

If I paste the same link without OTR it tries to send the receiver a file. 
<<date>> trying to send file to user blablabla.
and then it says
<<date> error in sending blablabla to blablabla

I don't know why it tries to do that. It's just a link thats inside the clipboard. Maybe it has something to do with this modern clipboards that don't copy the text purely any more but also formatted and html code or so...

**Comment by valentin-nasta** [comment]
I have the same issue, and I found a message on the mailing list from Ulises Fronceda:

> Bug report:
> When copying URL from Google's Chrome Omnibox with HTTPS and paste directly
> from the clipboard to the chat in Jitsi, it does not paste the URL and
> instead it try to send a file with 0 bytes.
> 
> If you copy the URL and paste in something else, like a notepad, and then
> copy again and paste in the chat, it works. This is because Google's
> Omnibox copy the HTTPS into the clipboard with other format (URI UTF-8) and
> here's the bug were we cannot paste it directly to Jitsi chat.
> 
> As long as i have seen, it didn't happen for me in Windows 10, it only
> happens in MAC OS X (don't know if Ubuntu have the same problem)
> Reproduction Steps:
> 1. You are in MAC OS
> 2. You go to Google Chrome, enter in any web page with HTTPS connection
> 3. Copy to clipboard
> 4. Paste into Jitsi Chat, voilá, it does not paste, it tries to send it as
> a file w/ 0 bytes.
> 
> So yeah, it's basically a little bit pity because in the company were i am,
> we are pasting URL's from Chrome all the time
> 
> Thank you so much in advance!

http://lists.jitsi.org/pipermail/users/2017-March/012464.html

**Comment by ibauersachs** [comment]
I don't have a Mac. Unless someone donates one to me, I cannot work on it. It would be even better if someone would create a pull request...
