### ISSUE TITLE
Quickly alt tabbing in and out of Jitsi windows makes the taskbar button flash

### ISSUE THREAD

**Issue by lmojzis** [jitsi/jitsi#356]
Version 2.10.5550 win64

Steps to reproduce:
 - Open any Jitsi window
 - Alt tab out of it
 - Alt tab in and out of in in less than ~500 ms

Jitsi will make the taskbar button flash (according to system preferences, by default it will flash 7 times and then stay lit)

**Comment by lmojzis** [comment]
Just realized the next time you alt tab into Jitsi the "File" menubar entry will be highlighted so it can be windows menubar behavior related

**Comment by ibauersachs** [comment]
I just tried that, nothing happens. Neither with the taskbar nor with the menu.

**Comment by lmojzis** [comment]
Happens on 2 separate computers running Windows 7 x64 with DWM and Aero
disabled with Classic theme. That is all they have in common.

Dne 2. 7. 2017 12:41 napsal uživatel "Ingo Bauersachs" <
notifications@github.com>:

**Comment by ibauersachs** [comment]
Okay, I was able reproduce it with the DWM disabled. But the only time we actually register the window to flash is when a message is coming in. This isn't the case when tabbing in/out. Given that it only happens when DWM is disabled, I can't spend more time on it.
