### ISSUE TITLE
Client Crash when connecting to Slack XMPP Server

### ISSUE THREAD

**Issue by Catscratch** [jitsi/jitsi#361]
Hi,

I tried to connect Jitsi with XMPP slack server. During connect process Jitsi freezes.

Is this a known problem I may fix by myself? Or can I deliver more information you need?

Thanks!

**Comment by ibauersachs** [comment]
Connecting to Slack works just fine for a sample setup I just created. Has your team the XMPP Gateway enabled?
When using the settings from https://jitsi-dev.slack.com/account/gateways, add them into Jitsi like this:

XMPP Username: <User>@<Host>
Password: <Password>

You should see the `slackbot` in your contact list.

**Comment by Catscratch** [comment]
I only get this:
`2017-07-27 09:02:24.825 SCHWERWIEGEND: [251] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectUsingSRVRecords().912 No SRV addresses found for _xmpp-client._tcp.<MYSLACKGROUP>.xmpp.slack.com
2017-07-27 09:02:25.829 INFORMATION: [251] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin().1289 Chosen TLS protocol and algorithm:
Protocol: TLSv1.2
Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256`

**Comment by ibauersachs** [comment]
Well, that's a misconfiguration on Slack's side. They should provide this DNS record. However, Jitsi would still be able to connect since we try using the hostname (`<Slackgroup>.xmpp.slack.com`) when an SRV cannot be found.
Is that message the only problem?
