### ISSUE TITLE
Jitsi and Asterisk with a non standart port

### ISSUE THREAD

**Issue by uriah156** [jitsi/jitsi#363]
IP-PBX Asterisk uses a non standart port (not 5060). Jitsi is registred successfully on asterisk. Incoming calls are good. But when Jitsi makes an outgoing call SIP INVITE is sent to the asterisk on standard port 5060 and a challenge is not committed.

**Comment by damencho** [comment]
Did you set proxy options in sip account settings under connection tab?
You have to un-check configure proxy automatically and configure proxy address (the asterisk address or domain name you use to access it), the custom port and the protocol used.

**Comment by uriah156** [comment]
Оf couse yes. Registration server and proxy server are setuped with necessary port and protocol.

**Comment by uriah156** [comment]
In the logs of Wireshark I can see the message INVITE to asterisk on the port 5060.

**Comment by ibauersachs** [comment]
Can you please provide the logs of such a failed call?

**Comment by ibauersachs** [comment]
No feedback, closing.
