### ISSUE TITLE
Import asterisk phonebook and extensions

### ISSUE THREAD

**Issue by anavasis** [jitsi/jitsi#365]
Hello,
i would like to import contacts from the asterisk phone book directly to jitsi. 
How is that possible?

Thanks

i have to add here that i am using freepbx

**Comment by ibauersachs** [comment]
I assume you're referring to the [Asterisk Phonebook Module](https://wiki.freepbx.org/display/FPG/Asterisk+Phonebook+Module). This can't be connected to Jitsi. An implementation would require that:
- FreePBX provides the list of those extensions via an API
- Someone writes an address book plugin for Jitsi that queries this API
