### ISSUE TITLE
Creating a DMG fails with /var/root/bin does not exist

### ISSUE THREAD

**Issue by wellkwen** [jitsi/jitsi#368]
when I try make DMG app for make

`sudo ant dmg`

jre-8u131-macosx-x64 I have, Mac OS 10.12.5

```
BUILD FAILED
/Users/nikki/jitsi/resources/install/build.xml:1385: The following error occurred while executing this line:
/Users/nikki/jitsi/resources/install/build.xml:1426: /var/root/bin does not exist.
```

**Comment by ibauersachs** [comment]
> /Users/nikki/jitsi/resources/install/build.xml:1426: /var/root/bin does not exist.

The build.xml doesn't contain /var/root anywhere. Where is this coming from? What version are you trying to build? Line 1426 in the current master branch doesn't call anything either (it's an empty line).

**Comment by ibauersachs** [comment]
No feedback, closing.
