### ISSUE TITLE
Jitsi doesn't start, message "Properties Editor"

### ISSUE THREAD

**Issue by thiagpastore** [jitsi/jitsi#371]
I installed JITSI jitsi-2.10.5550-x64.msi on fresh legal Windows 8.1. After the installation, JITSI doesn't start, there's a message "Properties Editor
![jitsi_issue](https://user-images.githubusercontent.com/5825531/27752015-56f398da-5db5-11e7-97ee-8ac3d1669b22.jpg)
" and nothing else.

**Comment by ibauersachs** [comment]
Can you please try [build 5580](https://download.jitsi.org/jitsi/nightly/windows/) (or newer) and lets us know?

**Comment by ibauersachs** [comment]
No feedback, closing.

**Comment by fatihaksoyorg** [comment]
Hi;
i have the same problem.
I tried other versions too

**Comment by s-semicwetik** [comment]
[log_jitsi_v2.11.5633.txt](https://github.com/jitsi/jitsi/files/5590496/log_jitsi_v2.11.5633.txt)
Hello, 
my jitsi v2.11.5633 
the same program error
details of the program execution in TXT 
Help me please =\ 
OS: windows 7
