### ISSUE TITLE
No error message when the "pbx" can't be reached

### ISSUE THREAD

**Issue by lhirlimann** [jitsi/jitsi#374]
My sip server is behind a VPN. When the VPN is not up I can still make calls (and the UI displays that i'ts conncting.

The console shows : 
 2017-07-17 10:27:14.058 SEVERE: [2817] impl.protocol.sip.OperationSetBasicTelephonySipImpl.processResponse().634 Received error: 481 Call leg/transaction does not exist

Could this be cought and get a nice message , like the server is currently unavailable.

**Comment by ibauersachs** [comment]
This error message was sent by your SIP server. Is it possible that you only need the VPN to actually transfer audio-data, but not to for SIP messages? When you disconnect the VPN, your SIP account would normally go offline, which in turn would prevent from starting a call in the first place.

In any case, please provide us your [logs](https://desktop.jitsi.org/logs).
