### ISSUE TITLE
libappindicator is not listed as a dependancies in the rpm manifest

### ISSUE THREAD

**Issue by lhirlimann** [jitsi/jitsi#375]
Trying to install the manifest fails as you need at least libappindicator which was not installed on my fedora 26 workstation.

**Comment by ibauersachs** [comment]
Could you please clarify what you mean exactly? libappindicator is actually listed as a dependency, see here:
https://github.com/jitsi/jitsi/blob/master/resources/install/rpm/SPECS/jitsi.spec#L21

**Comment by lhirlimann** [comment]
rpm -i jistsi.rpm complained that libindicator was not installed had to install it by hand.

**Comment by jitsi-developers** [comment]
I notice that Usul mentions "libindicator" and Ingo mentions
"libappindicator".  Is that a typo on someone's part, or the problem?


Martin

**Comment by ibauersachs** [comment]
@lhirlimann Can you please confirm if you meant lib**app**indicator or libindicator?

**Comment by lhirlimann** [comment]
yes confirming : 
  665 | install libappindicator  | 2017-07-15 12:14 | Install        |    2 >

**Comment by ibauersachs** [comment]
I don't know much about rpm packaging, but AFAIK there isn't anything more I can do than declaring the required dependencies. It would be the package manager's job to install those dependencies.

@elfring Any idea? Was libappindicator an issue for you?

**Comment by elfring** [comment]
>Any idea?

It seems that a software distribution like “openSUSE” prefers to [refer to such a library with a version suffix in the name](https://software.opensuse.org/package/libappindicator3-1 "Application indicators library for GTK+ 3").
Will any more [checks and package name substitutions](https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Handling_dependencies "openSUSE Build Service cross distribution howto: Handling dependencies") be needed then?

**Comment by ibauersachs** [comment]
libappindicator3 is a different library (for GTK3).

**Comment by elfring** [comment]
How do you think about to [refer to the name “libappindicator1” for SUSE-based software distributions](https://software.opensuse.org/package/libappindicator1 "Application indicators library")?

**Comment by ibauersachs** [comment]
Why? [libappindicator](https://software.opensuse.org/package/libappindicator) is available on Suse.

**Comment by elfring** [comment]
Yes. - [This software](https://software.opensuse.org/package/libappindicator "Application indicators library") is also available there.
The provided package names can be different from the selection on Fedora 26, can't they?

**Comment by ibauersachs** [comment]
It could be different, but [it's not](https://www.rpmfind.net/linux/rpm2html/search.php?query=libappindicator&submit=Search+...&system=&arch=).

**Comment by elfring** [comment]
* Did you notice already that the name “libappindicator” refers to a source file package within the SUSE software context?
* Under which circumstances are you going to add version suffixes to the names for needed binary packages?

**Comment by ibauersachs** [comment]
I'm closing all RPM issues and we will disable the RPM builds. Once the migration to OpenH264 and Smack 4.2.x is complete, we can reconsider how to proceed with RPMs. If there are public build infrastructures for various systems (Suse, Fedora, etc.) available, we might be able to use those instead of our own - which doesn't scale.
