### ISSUE TITLE
Alsa warning messages on fedora 26

### ISSUE THREAD

**Issue by lhirlimann** [jitsi/jitsi#376]
I'm using the rpm provided from your website. When I start Jitsi I see the following error messages on the console : 
[ludo@Oulanl ~]$ jitsi 
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave

[ludo@Oulanl cpuminer-multi]$ rpm -qa |grep alsa
alsa-lib-1.1.4.1-1.fc26.x86_64
alsa-plugins-pulseaudio-1.1.4-1.fc26.x86_64
alsa-utils-1.1.4-1.fc26.x86_64
alsa-lib-1.1.4.1-1.fc26.i686
alsa-plugins-pulseaudio-1.1.4-1.fc26.i686

**Comment by ibauersachs** [comment]
This is normal. ALSA prints to stderr, which we don't redirect.
