### ISSUE TITLE
Improve GitHub release naming

### ISSUE THREAD

**Issue by baimafeima** [jitsi/jitsi#385]
Could you name the releases here on GitHub more explicitly, that is, to indicate which ones are beta releases and which ones are stable ones?

**Comment by ibauersachs** [comment]
I've added `Jitsi-2.x` tags for the existing releases. Unfortunately Github provides no control over what is shown in the _n releases_ tab. Moving the existing tags into a subfolder (e.g. snapshot/1234) would break the build system and is not something that I can easily do for now.

**Comment by baimafeima** [comment]
@ibauersachs Thanks a lot for taking care of this so quickly. Maybe there is a way to further improve it when there is more time.
