### ISSUE TITLE
Badge always visible even if no missed call on MacOS

### ISSUE THREAD

**Issue by davidbernard04** [jitsi/jitsi#386]
On MacOS, the dock icon always has a badge, even if it indicates there is no missed call or new message:
![jitsi_dock_icon](https://user-images.githubusercontent.com/14351661/29316358-b770d5de-8195-11e7-90df-21d01850e16b.png)

This is not a typical Mac behavior, and hiding the badge when there is no new event would give a better user experience in my opinion.

**Comment by davidbernard04** [comment]
I have tested successfully this snippet of code:

**src/net/java/sip/communicator/impl/osdependent/jdic/SystrayServiceJdicImpl.java:468**

        if (OSUtils.IS_MAC)
        {
            Application application = Application.getApplication();
            if (count > 0)
            {
                application.setDockIconBadge(new Integer(count).toString());
            }
            else
            {
                application.setDockIconBadge(null);
            }
        }

Let me know if you prefer that I create a branch and pull-request.

**Comment by ibauersachs** [comment]
A pull request would be nice. Please make sure to sign the [CLA](https://jitsi.org/icla) though.

**Comment by davidbernard04** [comment]
Looks like I don't have the rights to commit.

**Comment by ibauersachs** [comment]
You don't have commit rights to Jitsi directly until you [become a comitter](https://desktop.jitsi.org/Documentation/CommitAccess). The way pull requests usually work on Github (in general, not specific to Jitsi) is:
- Fork the repo
- Create a branch in your fork, make the changes, commit and push them
- (Sign a CLA and/or follow some project speficic requirements)
- Create a pull request from your branch

See the [Github help](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for more information.

**Comment by davidbernard04** [comment]
@ibauersachs I sent the pull-request for this! https://github.com/jitsi/jitsi/pull/395

**Comment by davidbernard04** [comment]
@ibauersachs Let me know if everything's alright with the pull-request. That's my first in github. ;)

**Comment by ibauersachs** [comment]
Sorry for the delay, I was busy at work. I've merged the PR; thanks for your contribution!
