### ISSUE TITLE
Please provide example how to login SIP with tls

### ISSUE THREAD

**Issue by basildane** [jitsi/jitsi#387]
I have read all the documentation I can find, and now I'm looking at the source code trying to figure out how to specify the correct SIP ID to login with tls.

I have 255@mydomain.com.
It logins with SIP port 5060.

I've tried 255@mydomain.com;tlsenable=yes
That returns an error.  I'm stumped.

**Comment by ibauersachs** [comment]
Tools->Options->Account->Your SIP Account->Connection.


![sip-tls](https://user-images.githubusercontent.com/949783/29567601-1767a8ce-874e-11e7-971a-3b8c752aa9b5.png)

**Comment by basildane** [comment]
Thank you!
