### ISSUE TITLE
Jitsi not showing hints - extension status of other extensions (SIP)

### ISSUE THREAD

**Issue by basildane** [jitsi/jitsi#388]
All my other endpoints are working, but all Jitsi endpoints are just showing a grey dot (unavailable) for all remote extensions.

Asterisk 14, pjsip.
Jitsi 2.11.5585

I checked with wireshark and the subscribe/notify looks good to me, and like I said, everything else displays the status normally, but not Jitsi.

Here is an example subscribe and notify:

User Datagram Protocol, Src Port: sip (5060), Dst Port: sip (5060)
Session Initiation Protocol (SUBSCRIBE)
    Request-Line: SUBSCRIBE sip:208@10.0.10.15 SIP/2.0
        Method: SUBSCRIBE
        Request-URI: sip:208@10.0.10.15
        [Resent Packet: False]
    Message Header
        Call-ID: 7130ded7105f29340be71e4c46779010@0:0:0:0:0:0:0:0
        CSeq: 1 SUBSCRIBE
            Sequence Number: 1
            Method: SUBSCRIBE
        From: "207" <sip:207@10.0.10.15>;tag=b4b0ea8b
            SIP Display info: "207"
            SIP from address: sip:207@10.0.10.15
            SIP from tag: b4b0ea8b
        To: <sip:208@10.0.10.15>
            SIP to address: sip:208@10.0.10.15
                SIP to address User Part: 208
                SIP to address Host Part: 10.0.10.15
        Via: SIP/2.0/UDP 10.242.2.2:5060;branch=z9hG4bK-353432-9f1bb11b96332d2b3e7ff13adf71e83b
            Transport: UDP
            Sent-by Address: 10.242.2.2
            Sent-by port: 5060
            Branch: z9hG4bK-353432-9f1bb11b96332d2b3e7ff13adf71e83b
        Max-Forwards: 70
        Contact: "207" <sip:207@10.242.2.2:5060;transport=udp;registering_acc=10_0_10_15>
            SIP Display info: "207"
            Contact URI: sip:207@10.242.2.2:5060;transport=udp;registering_acc=10_0_10_15
                Contact URI User Part: 207
                Contact URI Host Part: 10.242.2.2
                Contact URI Host Port: 5060
                Contact URI parameter: transport=udp
                Contact URI parameter: registering_acc=10_0_10_15
        User-Agent: Jitsi2.11.5585Windows 10
        Event: presence
        Accept: application/pidf+xml
        Expires: 3600
        Content-Length: 0

User Datagram Protocol, Src Port: sip (5060), Dst Port: sip (5060)
Session Initiation Protocol (NOTIFY)
    Request-Line: NOTIFY sip:207@10.242.2.2:5060;registering_acc=10_0_10_15 SIP/2.0
        Method: NOTIFY
        Request-URI: sip:207@10.242.2.2:5060;registering_acc=10_0_10_15
        [Resent Packet: False]
    Message Header
        Via: SIP/2.0/UDP 10.0.10.15:5060;rport;branch=z9hG4bKPj0d423934-0398-472b-9d7b-f74bbd982720
            Transport: UDP
            Sent-by Address: 10.0.10.15
            Sent-by port: 5060
            RPort: rport
            Branch: z9hG4bKPj0d423934-0398-472b-9d7b-f74bbd982720
        From: <sip:208@10.0.10.15>;tag=4605377e-80d5-499d-96d6-3d9cb366d642
            SIP from address: sip:208@10.0.10.15
            SIP from tag: 4605377e-80d5-499d-96d6-3d9cb366d642
        To: "207" <sip:207@10.0.10.15>;tag=b4b0ea8b
            SIP Display info: "207"
            SIP to address: sip:207@10.0.10.15
                SIP to address User Part: 207
                SIP to address Host Part: 10.0.10.15
            SIP to tag: b4b0ea8b
        Contact: <sip:10.0.10.15:5060>
            Contact URI: sip:10.0.10.15:5060
                Contact URI Host Part: 10.0.10.15
                Contact URI Host Port: 5060
        Call-ID: 7130ded7105f29340be71e4c46779010@0:0:0:0:0:0:0:0
        CSeq: 12325 NOTIFY
            Sequence Number: 12325
            Method: NOTIFY
        Event: presence
        Subscription-State: active;expires=3599
        Allow-Events: presence, dialog, message-summary, refer
        Max-Forwards: 70
        User-Agent: FPBX-14.0.1.4(14.6.0)
        Content-Type: application/pidf+xml
        Content-Length:   567

**Comment by ibauersachs** [comment]
Please attach the entire [logs](https://jitsi.org/logs) from Jitsi. These two snippets don't say much. In general, if I remember correctly, Asterisk isn't standard-compliant in a few ways regarding presence, but I know for sure that basic presence (available/busy/offline) is working with FreePBX 13, so it's also possible that v14 broke something.

**Comment by basildane** [comment]
I emailed the logs to dev as requested.  I'm happy to provide anything else you need, or do testing.

**Comment by ibauersachs** [comment]
I didn't see the logs on the list. Can you attach them here or send them to me directly?

**Comment by basildane** [comment]
[2017-08-22@17.25.27-logs.zip](https://github.com/jitsi/jitsi/files/1265231/2017-08-22.17.25.27-logs.zip)

Log file as requested.

**Comment by ibauersachs** [comment]
Asterisk seems to send crap in the `<contact/>` element of the PIDF. Compare the Wireshark screenshots from my working FreePBX13 vs. a subscription from your logs:

![image](https://user-images.githubusercontent.com/949783/29897993-dac26156-8de3-11e7-8aa1-13d96cf50b9b.png)

![image](https://user-images.githubusercontent.com/949783/29898034-fb44bc08-8de3-11e7-9acc-483507d515bb.png)

**Comment by basildane** [comment]
Astercrap (tm).

**Comment by basildane** [comment]
Wow, it's trying to escape HTML, that looks like a bug to me.  But then, all my other voip endpoints deal with it, including some that have not been updated in 6 years.

**Comment by ibauersachs** [comment]
The (hard-)phones potentially use the `From:` header instead of the PIDF data. Please also note that the excerpt in my example uses chan_sip, not chan_pjsip.

**Comment by ibauersachs** [comment]
Did you follow this up with a bug report at Asterisk or would you expect us to find a workaround for this stupidity?

**Comment by basildane** [comment]
I hadn't thought about it.  I would be surprised if no one else had noticed this on the asterisk side.  I'll check their issues.

**Comment by basildane** [comment]
Well, I spent 4 days trying to create an issue on asterisk.  They seem more interested in useless logs that are not related to the problem.  They still haven't acknowledged the issue after 4 days.  And some browsing around other issues, it looks like they sit for over 2 years before anyone looks at them.

I tried.

**Comment by ibauersachs** [comment]
Thanks. Even if they close it due to missing logs, can you please reference the issue you created here?

**Comment by basildane** [comment]
Asterisk issue: [ASTERISK-27290](https://issues.asterisk.org/jira/browse/ASTERISK-27290)

**Comment by ibauersachs** [comment]
According to https://gerrit.asterisk.org/#/c/1023/4/tests/channels/pjsip/subscriptions/presence/verify_bodies/verify_pidf/test-config.yaml, this crap valid is consired valid. I disagree because of [RFC3863#4.1.5](https://tools.ietf.org/html/rfc3863#section-4.1.5) and all other examples of `<contact/>` elements there. I'm adding this comment in the Asterisk issue too.

**Comment by ibauersachs** [comment]
Should be fixed in Asterisk >= 13.19.0 and >=15.2.0

**Comment by basildane** [comment]
We are on 14, and it was reported on 14.  They skipped asterisk 14?

**Comment by ibauersachs** [comment]
Apparently, since 14 is not an LTS version and receives security fixes only:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+Versions

**Comment by basildane** [comment]
Well, I can't win.

Is there anything you can do on the Jitsi side to fix this?  It's a severe problem for me as I am 40 miles away from where some users are, and I can no longer see if calls are being answered since we upgraded to 14.
Either that or I have to write my own standalone program to sit beside jitsi to restore the functionality.

**Comment by ibauersachs** [comment]
As I said in #394, I will, but right now I simply don't have time for it. I'm closing this issue in favor of #394 since this was specific to Asterisk.

**Comment by basildane** [comment]
394?  Cool.  I wasn't aware of that.
