### ISSUE TITLE
Call popup notification

### ISSUE THREAD

**Issue by anavasis** [jitsi/jitsi#393]
Hello,

I am using freepbx and use jitsi to make and receive calls. The problem i have is that when i receive a call
and accepting it and then a second is calling the notification popup is ringing inside my ear .
Is there any solution? Moreover how can i make the notification popup to be in another possition on the
screen and not in the center?

Thanks in advance

**Comment by tomaso01** [comment]
Hello,

I have the same problem. I'm talking with one customer and when the second one calling, notification sound is diffusing and I dont hear what the first customer says.
I will be grateful for your help

Greetings!

**Comment by ibauersachs** [comment]
You can disable receiving a second call in FreePBX for your extension. The second caller will then get the busy signal.
I think there's also a property in Jitsi that would essentially configure the same thing. @damencho?

You cannot configure the location of the popup. It is intended to be obstrusive so you don't accidentally miss calls.

**Comment by damencho** [comment]
The property for jitsi is net.java.sip.communicator.impl.protocol.CallWaitingDisabled.

```
    /** ......... specifies whether call
     * waiting is disabled i.e. whether it should reject new incoming calls when
     * there are other calls already in progress.
     */
```

**Comment by truelai** [comment]
> The property for jitsi is net.java.sip.communicator.impl.protocol.CallWaitingDisabled.
> 
> ```
>     /** ......... specifies whether call
>      * waiting is disabled i.e. whether it should reject new incoming calls when
>      * there are other calls already in progress.
>      */
> ```

@damencho - can you tell us how to implement this property?  Do I need to edit a specific jar file? Or must this be done when compiling? Would you be able to give a quick explanation?

**Comment by cesar-ayuuk** [comment]
@damencho would you mind giving us a quick explanation how to implement this? Which file i need to edit?

**Comment by damencho** [comment]
Add new property net.java.sip.communicator.impl.protocol.CallWaitingDisabled with value true and restart Jitsi
Here:
![image](https://user-images.githubusercontent.com/3263098/85737079-ad909380-b6c4-11ea-9a87-55d673356e75.png)
