### ISSUE TITLE
External contacts config form uses dropdown instead of tabs

### ISSUE THREAD

**Issue by Af0x** [jitsi/jitsi#399]
Hello,

on Fedore 26, if you select the local address-book as external address-book it will not show any suggestions. Additional after closing jitsi and open it again it will lose the option and select e.g. LDAP instead.

Version 2.11.5589 running on in Fedora 26.

Regards,

Af0x

**Comment by ibauersachs** [comment]
I'm not sure I understand the problem. Jitsi on Linux doesn't have a local addressbook like on Windows (querying Outlook) or on Mac (querying whatever the built-in OSX app for contacts is). The available options to configure on Linux are thus Thunderbird and LDAP.

The dropdown also doesn't revert to anything, it is a configuration selector like a tab panel. Admittedly, this is a rather bad UI design. I'm leaving the issue open to change this to a tab panel.

**Comment by Af0x** [comment]
it would be nice if under Linux the Evolution address book could be utilized. Evolution is the default e-mail client under GNOME desktop: https://en.wikipedia.org/wiki/Evolution_(software)

**Comment by ibauersachs** [comment]
Sure, but I simply don't have the resources to create and maintain yet another plugin. Feel free to help out and create a pull request.

**Comment by Af0x** [comment]
that´s above my skill level. I´m just the guy with the ideas and visions ^^
