### ISSUE TITLE
Nginx install fail

### ISSUE THREAD

**Issue by Jdierssen** [jitsi/jitsi#401]
I got an error about my nginx and i fixed it but it still didn`t work so i uninstalled it but whenever i try to install it is says that it`s already installed but i can`t see what path and the webserver isn`t running either

**Comment by ibauersachs** [comment]
Jitsi Desktop doesn't use a webserver like nginx. If you're referring to an issue with Jitsi Meet, please report the bug in the correct repository.
In any case you need to describe your issue much more detailed.
