### ISSUE TITLE
Regression in SIP, unable to go 'online' anymore

### ISSUE THREAD

**Issue by reavertm** [jitsi/jitsi#402]
Jitsi no longer goes 'online' for SIP account. This is some Cisco SIP server in this case.
I bisected Jitsi to:

> mrozowsk@cnu420dqzs jitsi]$ git bisect bad
> 5f9610cbb2d2ed89afe033b4691d607d408393a6 is the first bad commit
> commit 5f9610cbb2d2ed89afe033b4691d607d408393a6
> Author: Danny van Heumen <danny@dannyvanheumen.nl>
> Date:   Sat Apr 8 20:40:15 2017 +0200
> 
>     Blind attempt at fixing Jitsi client respecting contact header expiry value.
> 
> :040000 040000 c53af3670b7468f107b4d419ee9f0bd6fdaad9b9 5e2feabbcad6c77ea6e73c6e30ea03738fc81154 M      src
> [mrozowsk@cnu420dqzs jitsi]$ git status
> HEAD detached at 5f9610cbb
> You are currently bisecting, started from branch 'master'.
>   (use "git bisect reset" to get back to the original branch)
> 
> nothing to commit, working tree clean

I enabled SIP logging, .pcap file is created and while I cannot attach it here due to corpo email addressed being exposed there, some SIP related communication is:

> 1	0.000000	10.154.117.175	10.154.34.65	DNS	100	Standard query 0x3a73 AAAA CUST01-CUCM-SUB-03-CL3.int.net.nokia.com
> 2	0.051000	10.154.34.65	10.154.117.175	DNS	181	Standard query response 0x3a73 AAAA CUST01-CUCM-SUB-03-CL3.int.net.nokia.com SOA usfraaa-ipam-dns001.americas.nsn-net.net
> 3	0.059000	10.154.117.175	10.154.34.65	DNS	100	Standard query 0x6488 A CUST01-CUCM-SUB-03-CL3.int.net.nokia.com
> 4	0.062000	10.154.34.65	10.154.117.175	DNS	116	Standard query response 0x6488 A CUST01-CUCM-SUB-03-CL3.int.net.nokia.com A 10.158.20.170
> 5	0.167000	0.0.0.0	10.158.20.170	SIP	720	Request: REGISTER sip:CUST01-CUCM-SUB-03-CL3.int.net.nokia.com  (1 binding) | 
> 6	0.289000	10.158.20.170	0.0.0.0	SIP	706	Status: 200 OK  (1 binding) | 
> 7	0.290000	10.158.20.170	0.0.0.0	SIP	706	Status: 200 OK  (1 binding) | 
> 8	0.294000	10.158.20.170	0.0.0.0	SIP	483	Status: 100 Trying | 
(...)
> 14	2.319000	10.158.20.170	0.0.0.0	SIP	483	Status: 100 Trying | 
(...)
> 85	7.413000	0.0.0.0	10.158.20.170	SIP	720	Request: REGISTER sip:CUST01-CUCM-SUB-03-CL3.int.net.nokia.com  (1 binding) | 
> 86	7.519000	10.158.20.170	0.0.0.0	SIP	483	Status: 100 Trying | 
> 87	7.526000	10.158.20.170	0.0.0.0	SIP	483	Status: 100 Trying | 
> 88	7.537000	10.158.20.170	0.0.0.0	SIP	705	Status: 200 OK  (1 binding) | 
> 89	7.539000	10.158.20.170	0.0.0.0	SIP	705	Status: 200 OK  (1 binding) | 

SIP account is marked as offline.
In Jitsi before this 5f9610cbb commit, SIP account goes online: in .pcap there is no second attempt at REGISTER, and when calling, there is INVITE,  Trying, Ringing, OK, ACK.. works well.
Reverting this commit only (against current master) fixes the issue for me.

**Comment by reavertm** [comment]
Nothing SIP related in log or in terminal. There is some exception in org.jitsi.impl.neomedia.notify.AudioSystemClipImpl.exitRunOnceInPlayThread(AudioSystemClipImpl.java:124 but unrelated.

Jitsi originated:

> E5
> REGISTER sip:CUST01-CUCM-SUB-03-CL3.int.net.nokia.com SIP/2.0
> Call-ID: 3967024a5712efca4796cc4782b1c335@0:0:0:0:0:0:0:0
> CSeq: 1 REGISTER
> From: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>;tag=1e80542f
> To: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>
> Via: SIP/2.0/UDP 10.154.117.175:5060;branch=z9hG4bK-383135-d56094d99dfb1f237b4c1fc947b8af04
> Max-Forwards: 70
> User-Agent: Jitsi2.11.0.build.by.SVNLinux
> Expires: 600
> Contact: "XXX@XXX.com" <sip:XXXXXX@10.154.117.175:5060;transport=udp;registering_acc=CUST01-CUCM-SUB-03-CL3_int_net_nokia_com>;expires=600
> Content-Length: 0

followed by server's:

> E5
> SIP/2.0 100 Trying
> Via: SIP/2.0/UDP 10.154.117.175:5060;branch=z9hG4bK-383135-d56094d99dfb1f237b4c1fc947b8af04
> From: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>;tag=1e80542f
> To: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>
> Date: Fri, 22 Sep 2017 16:25:14 GMT
> Call-ID: 3967024a5712efca4796cc4782b1c335@0:0:0:0:0:0:0:0
> CSeq: 1 REGISTER
> Content-Length: 0

> E5
> SIP/2.0 100 Trying
> Via: SIP/2.0/UDP 10.154.117.175:5060;branch=z9hG4bK-383135-d56094d99dfb1f237b4c1fc947b8af04
> From: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>;tag=1e80542f
> To: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>
> Date: Fri, 22 Sep 2017 16:25:14 GMT
> Call-ID: 3967024a5712efca4796cc4782b1c335@0:0:0:0:0:0:0:0
> CSeq: 1 REGISTER
> Content-Length: 0

> E5
> SIP/2.0 200 OK
> Via: SIP/2.0/UDP 10.154.117.175:5060;branch=z9hG4bK-383135-d56094d99dfb1f237b4c1fc947b8af04
> From: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>;tag=1e80542f
> To: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>;tag=1636213230
> Date: Fri, 22 Sep 2017 16:25:14 GMT
> Call-ID: 3967024a5712efca4796cc4782b1c335@0:0:0:0:0:0:0:0
> Server: Cisco-CUCM10.5
> CSeq: 1 REGISTER
> Expires: 600
> Contact: "XXX@XXX.com" <sip:XXXXXX@10.154.117.175:5060;transport=udp;registering_acc=CUST01-CUCM-SUB-03-CL3_int_net_nokia_com>
> Supported: X-cisco-sis-7.1.1
> Content-Length: 0

> E5
> SIP/2.0 200 OK
> Via: SIP/2.0/UDP 10.154.117.175:5060;branch=z9hG4bK-383135-d56094d99dfb1f237b4c1fc947b8af04
> From: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>;tag=1e80542f
> To: "XXX@XXX.com" <sip:XXXXXX@CUST01-CUCM-SUB-03-CL3.int.net.nokia.com>;tag=1636213230
> Date: Fri, 22 Sep 2017 16:25:14 GMT
> Call-ID: 3967024a5712efca4796cc4782b1c335@0:0:0:0:0:0:0:0
> Server: Cisco-CUCM10.5
> CSeq: 1 REGISTER
> Expires: 600
> Contact: "XXX@XXX.com" <sip:XXXXXX@10.154.117.175:5060;transport=udp;registering_acc=CUST01-CUCM-SUB-03-CL3_int_net_nokia_com>
> Supported: X-cisco-sis-7.1.1
> Content-Length: 0

Server is sending the same Trying and OK responses twice. Also in "OK" case.
So it looks to me like Jitsi connected properly but marked account as offline regardless.

Reverting 5f9610c alone fixes the issue for me.

**Comment by ibauersachs** [comment]
The commit mentioned in the last comment is indeed incorrect. It fails to check that the contact header actually has an `expires` attribute. But simply reverting it is also wrong since that will always ignore an expires attribute in the contact header if an Expires header is set. Though I'm not sure what the RFC requires in terms of precedence.

**Comment by damencho** [comment]
I will try testing and fixing this these days. 
The RFC explains how multiple Contacts are handled, which we do not support at the moment, I think. But basically, the contact expires overrides the global one, as it can be different for different contacts.
` The registrar now processes each contact address in the Contact
         header field in turn.  For each address, it determines the
         expiration interval as follows:

         -  If the field value has an "expires" parameter, that value
            MUST be taken as the requested expiration.

         -  If there is no such parameter, but the request has an
            Expires header field, that value MUST be taken as the
            requested expiration.

         -  If there is neither, a locally-configured default value MUST
            be taken as the requested expiration.`

https://tools.ietf.org/html/rfc3261#page-64

**Comment by damencho** [comment]
The strange thing is I do not see the problem here if there is no expire in the contact header. I still see the provider as online.

The method contactHeader.getExpires() will return -1 if the header param is missing and it will set the value from the expires header, so it seems to me the code will act correctly here.
Not sure what can be wrong to not show the provider as Online.

**Comment by ibauersachs** [comment]
@damencho If the a `Contact`-header is present, but doesn't have an expires-parameter, `grantedExpiration` is `-1`. Thus the condition on line 435 becomes true (`grantedExpiration <= 0`) and the account will be unregistered.

**Comment by damencho** [comment]
Thanks, I was looking at just the snippet of the changes :( and didn't noticed there is more contact header logic after it ... reproduced.
