### ISSUE TITLE
SRV lookups are not supported.

### ISSUE THREAD

**Issue by leftyb** [jitsi/jitsi#409]
It seems that Jitsi does not support SRV records resolution, although it is a standard at the RFC.
Is that so, or I am using an old Jitsi?  If is not supported, any plan to include it

Thank you

**Comment by damencho** [comment]
Jitsi uses NAPTR and SRV, if there is no NAPTR records it uses SRV. All you need is when configuring the sip account leave the "Configure proxy automatically" checked.
