### ISSUE TITLE
Video Call with JSXC Client

### ISSUE THREAD

**Issue by diegobill** [jitsi/jitsi#411]
jsxc/jsxc#630

**Comment by ibauersachs** [comment]
You mention the Jitsi Android client in the jsxc issue, however that client is no longer maintained. Are you seeing the same problem on Jitsi Desktop (this repo)?

**Comment by diegobill** [comment]
@ibauersachs , I need a Android client, I Did not test this repo. Is there a Android client in this repo?

**Comment by ibauersachs** [comment]
No. The Android client **was** at [jitsi/jitsi-android](https://github.com/jitsi/jitsi-android). It is no longer supported.
If you see the same problem with the desktop client, we'll try to fix it. If not, please close this issue.
