### ISSUE TITLE
ubuntu 17.10 callto uri issue

### ISSUE THREAD

**Issue by Deletron** [jitsi/jitsi#415]
The setup is next:

- Ubuntu 17.04 + Jitsi Stable = Callto link works fine.

>  Ubuntu 17.10 + Old /home drive from 17.04 = Jitsi still works.(not working after recheck)

- Ubuntu 17.10 Fresh install + Jitsi = works on manual copy paste of numbers 

- but when click on callto links it gives weird result calling a number with /// slashes in front of it. i.e. instead of +373 333 333 333 it goes ///+373 333 333 333 with a fail

P.S. Browser Google Chrome + mimelist (callto=jitsi.desktop)
For now I have tried to replace from another 17.04 .jitsi folder to 17.10 in /home but with no success. As I'm not that good with ubuntu can someone suggest what else can be picked from old  /home directory that will make callto uri work? or any other suggestion?

**Comment by Deletron** [comment]
OK, today I have narrowed searches, its somewhere in connection between Google Chrome and Jitsi.
I had tried to launch callto links through Firefox and it worked fine, but the problem is that I need Google Chrome...
Can anyone help me with a suggestion where that connection between Chrome and Jitsi is that add those /// ?

**Comment by damencho** [comment]
Have you tried tel: or sip: urls or xmpp:? 
As I can see only those are supported:
https://github.com/jitsi/jitsi/blob/master/resources/install/debian/jitsi.desktop.tmpl

**Comment by Deletron** [comment]
Surely did, same issue

**Comment by damencho** [comment]
Or sorry I initially misunderstood you, I thought the problem was the detection of the links, not the slashes /// this needs code debugging :) Interesting is it only a linux issue

**Comment by Deletron** [comment]
yes and only on 17.10 Artful version

**Comment by Deletron** [comment]
How can I help with Debugging? I have tested this on 2 different machines with 17.10 on them with same issue.

**Comment by ibauersachs** [comment]
Chrome used to have a bug on Windows and added to many slashes to external URIs. Maybe they (re-)introduced that on Linux. Did you use the same Chrome version on 17.04 and 17.10?

**Comment by Deletron** [comment]
yas exaclty same version of chrome on 17.04 and 17.10

**Comment by Deletron** [comment]
Come on guys, 17.10 is so awesome, the only reason that it stops me to install on all PCs is Jitsi callto issue. Please help :)

**Comment by Deletron** [comment]
Hey guys, how its going, google forum has stretched review of my question till now and in the end they said that my report is first, that no one else encounter it and that I should post report on crbug.com
I had tried on third machine, fresh install 17.10 same issue, have you tested this issue its same problem or I do something wrong?

**Comment by Deletron** [comment]
Today I have rechecked situation 2 where fresh install with old /home directory
Still not working, it's adding /// :(

**Comment by noeldieschburg** [comment]
Hello, same problem here with an arch linux. It seems that the problem comes from gio open. Google chrome call xdg-open, which for gnome3 calls gio open. gio open adds slashes to urls 'tel:+xxx'. I don't understand this behavior. I think it is just a bug. A dirty hack would be to bypass gio open in the gnome3_open func of /usr/bin/xdg-open ...

**Comment by ibauersachs** [comment]
Can you please report this at the Gio project? These slashes don't belong there and Jitsi apparantly is correctly trying to dial what it is being asked to.

**Comment by ibauersachs** [comment]
Should actually already be fixed: https://bugzilla.gnome.org/show_bug.cgi?id=779182
