### ISSUE TITLE
src/native/build.xml should use pkg-config

### ISSUE THREAD

**Issue by lukateras** [jitsi/jitsi#419]
Currently linker flags are hardcoded in `src/native/build.xml`. It'd be great if Jitsi could use `pkg-config` instead.

**Comment by yegortimoshenko** [comment]
If it proves useful, I've wrote a bash function that can transform `pkg-config` output to XML compatible with `src/native/build.xml`:

```
pkgconfig2Ant() {
  for lib in $@; do
    for cflag in $(pkg-config --cflags $lib); do
      echo "<compilerarg value=\"$cflag\" />"
    done
    for ldflag in $(pkg-config --libs $lib); do
      echo "<linkerarg value=\"$ldflag\" location=\"end\" />"
    done
  done
}
```

**Comment by yegortimoshenko** [comment]
> platform:Linux

This also should apply to macOS build, if possible.
