### ISSUE TITLE
jitsi links to 404

### ISSUE THREAD

**Issue by castilma** [jitsi/jitsi#422]
in the chat window the menu secure chat->what's that? links to https://jitsi.org/GSOC2009/OTR.

that's a 404.

**Comment by damencho** [comment]
This should be https://desktop.jitsi.org/GSOC2009/OTR

**Comment by ibauersachs** [comment]
@damencho Please set up a redirect on the new site. There's plenty of installations out there with the existing link

**Comment by damencho** [comment]
Ok, make sense, will fix it today.

**Comment by damencho** [comment]
Fixed.
