### ISSUE TITLE
Jitsi 2.10.5550 no longer works with a JingleNodes Relay (in Openfire)

### ISSUE THREAD

**Issue by elisafk** [jitsi/jitsi#424]
Hello,
we used audio calls via XMPP in Jitsi 2.8.5470 with a Openfire server (4.0.3) and a Jingle Nodes plugin (0.2.0).
Two of our Jitsi clients could not establish a direct connection and have to use the Jingle Nodes relay on Openfire, that worked without a problem with Jitsi version 2.8. But then we updated to a new Jitsi version 2.10.5550 using the same configuration and we noticed 2 things:
a) It takes a considerable amount of time more to establish the call.
b) The call is established but has no audio which renders it useless.

Why is the "new" version of ICE so much slower and why does the calls over Jingle Nodes no longer work? Anyone else got this?

**Comment by elisafk** [comment]
We were able to find why the call was established but didn´t have audio.
In the method createJingleNodesCandidateclass in class JingleNodesHarvester.java, it is necessary to add the line "component.getComponentSocket().add(cand.getCandidateIceSocketWrapper());" after add the stunSocket.

**Comment by bgrozev** [comment]
Thanks, @elisafk ! Your fix makes sense to me, I've opened #464  to get it in
