### ISSUE TITLE
issues with rpm requirements on CentOS 7

### ISSUE THREAD

**Issue by utoplenick** [jitsi/jitsi#425]
Hi, rpm from site requires speexdsp package, but in CentOS 7 there is no speexdsp, just speex that contains both speex and speexdsp.

**Comment by trifo13** [comment]
Hi utoplenick.

Here is my workaround:

1) Remove speex (installed from base) without it's dependencies:

rpm -e --nodeps speex

2) Download and install speex and speexdps separately from epel:

wget https://copr-be.cloud.fedoraproject.org/results/fedpop/speex/epel-7-x86_64/00146973-speex/speex-1.2-0.23.rc2.el7.centos.x86_64.rpm

rpm -i speex-1.2-0.23.rc2.el7.centos.x86_64.rpm

wget https://copr-be.cloud.fedoraproject.org/results/fedpop/speexdsp/epel-7-x86_64/00146970-speexdsp/speexdsp-1.2-0.7.rc3.el7.centos.x86_64.rpm

rpm -i speexdsp-1.2-0.7.rc3.el7.centos.x86_64.rpm

3) Install Jitsi

Best,
Trifo.

**Comment by utoplenick** [comment]
Hm, I think the best way is fix spec for CentOS and build separate package, i did so. If you want I can give you spec.

**Comment by ibauersachs** [comment]
A long as these stupid distros can't agree on using the same package names, the best way is for us to stop building RPMs entirely. Which is probably what we're going to do.

**Comment by utoplenick** [comment]
You can require speexdsp files instead package name.

**Comment by ibauersachs** [comment]
I'm closing all RPM issues and we will disable the RPM builds. Once the migration to OpenH264 and Smack 4.2.x is complete, we can reconsider how to proceed with RPMs. If there are public build infrastructures for various systems (Suse, Fedora, etc.) available, we might be able to use those instead of our own - which doesn't scale.

**Comment by cekstam** [comment]
I made a dependency-only package that provides speexdsp and requires speex for EL.

SPEC and noarch-package: https://github.com/cekstam/speexdsp-via-speex

**Comment by SparcV8** [comment]
> 
> 
> I made a dependency-only package that provides speexdsp and requires speex for EL.
> 
> SPEC and noarch-package: https://github.com/cekstam/speexdsp-via-speex

`[root@manizales yum.repos.d]# wget https://github.com/cekstam/speexdsp-via-speex/blob/master/speexdsp-1-1.el7.noarch.rpm
--2020-04-12 19:48:16--  https://github.com/cekstam/speexdsp-via-speex/blob/master/speexdsp-1-1.el7.noarch.rpm
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: âspeexdsp-1-1.el7.noarch.rpm.1â

    [ <=>                                                                                                                           ] 68,061      --.-K/s   in 0.05s

2020-04-12 19:48:16 (1.25 MB/s) - âspeexdsp-1-1.el7.noarch.rpm.1â saved [68061]

[root@manizales yum.repos.d]# rpm -Uvh speexdsp-1-1.el7.noarch.rpm
error: speexdsp-1-1.el7.noarch.rpm: not an rpm package (or package manifest):
[root@manizales yum.repos.d]#
`
