### ISSUE TITLE
Feature request: Add parameters to called event script

### ISSUE THREAD

**Issue by gunnicom** [jitsi/jitsi#426]
It would be really useful, if you can give a parameter, like the caller id on incoming call,to an executed program/scrript.
You can then do everything, like opening the contact from your database with that number in any software you like.

**Comment by ibauersachs** [comment]
This is already possible, available options are:
- caller.uri
- caller.address
- caller.name
- caller.id

Enclose them in `${}`, e.g. `${caller.id}`. Originally documented in [Trac Issue 1035](https://trac.jitsi.org/ticket/1035).

https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/plugin/notificationwiring/NotificationManager.java#L904

**Comment by gunnicom** [comment]
Thank you. Did only find a very old mailing list that stated it was not supported: http://users.sip-communicator.dev.java.narkive.com/jHx5pm0q/jitsi-users-execute-program-on-incoming-calls-command-notification-handler
