### ISSUE TITLE
Jitsi is still losing passwords/settings

### ISSUE THREAD

**Issue by Commicator** [jitsi/jitsi#430]
My problem seems to be the same as described here:
 https://github.com/jitsi/jitsi/issues/150

The thread is closed, but obiously the problem is still there. I tried it with the newest stable versions 32bit and 64bit under Win7 and every time I open jitsi or even every couple of mins I get this stupid dialogue, where I have to type the password for my SIP-account. This is really getting on my nerves.
Is there noone who managed to get this issue sorted out in three years?

Not only that the password is getting lost.
I'm having three sip-accounts. Every time I want to switch from one account to another, I have to close jitsi completely to be able to use a different account. Since every account is having different contact groups, jitsi manages to confuse these, too, so every other day the contacts get lost.
I really enjoy the idea of having encrypted video and audio, but if the above described "features" don't get removed pretty soon, we have to look for a decent alternative.

**Comment by basildane** [comment]
I'm going to help on this one as well by supplying logs.

**Comment by ibauersachs** [comment]
I've reopened #150 since it contains more information (and closing this instead).
