### ISSUE TITLE
Cannot pickup/hangup with Call Control Button on my headset (Plantronics SAVI 430)

### ISSUE THREAD

**Issue by boblelezard** [jitsi/jitsi#432]

**Comment by ibauersachs** [comment]
The pickup-buttons on headsets usually use proprietary keyboard scan codes. You can try if you can assign a global shortcut in Tools->Options->Advanced, but most likely this won't work.

A possible alternative is support software from the headset manufacturer that runs in the background and sends a keyboard shortcut which you can then assign in Jitsi's global shortcuts.
