### ISSUE TITLE
LLVM

### ISSUE THREAD

**Issue by ohhmm** [jitsi/jitsi#434]
Hey, here is how it could be built for iPhone https://stackoverflow.com/a/13634464/525578
use Java LLVM frontend

**Comment by ibauersachs** [comment]
The VMKit project has been abandoned. And even if that worked, there‘s no code to access audio/video on i-devices, let alone a UI.
There hasn‘t been enough manpower to work on the Android client (which was far easier), so iOS is simply not going to happen.
