### ISSUE TITLE
IPv6?

### ISSUE THREAD

**Issue by davidsummers** [jitsi/jitsi#439]
Is JITSI supposed to work with IPv6?

I tried it out and was not yet successful.

It works fine on IPv4.  I turned IPv4 off and turned on IPv6 on and I can't get it to connect to the remote OpenFire server.  All my contacts on that server show as if I'm not connected.

Is there a log file I can look at to see what is happening?

I'm trying to use IPv6-only by setting IPv4 off and IPv6 on.

I have a NAT64/DNS64 server to be able to reach IPv4-only sites via IPv6-only client.

*** Note: Everything else works on IPv6-only, Email, Skype for Business, FireFox, etc., just not JITSI.

I believe I'm using the latest version of JITSI Desktop on Windows 10: JITSI 2.10.5550.

All I need is IM at the moment on JITSI, that's the only thing I've tested so far with IPv6-only.

**Comment by ibauersachs** [comment]
Yes, it should work, but it's entirely possible that there are bugs. And yes, there are [logs](https://jitsi.org/logs). If you open the .pcap-files with Wireshark, you should be able to see a connection attempt to your Openfire server.
A live Wireshark capture should also show the DNS queries and the connection attempts to the IPv6 address.
