### ISSUE TITLE
[feature] on-the-fly room creation with notification to participants to emulate branching/forking

### ISSUE THREAD

**Issue by jibe-b** [jitsi/jitsi#442]
Here is an exploratory suggestion. I let you choose if it is in the scope of Jitsi or should stay a satellite.

Conf'calls sometime become crowdy and subgroups are interested by topics which will not interest the rest of the participants.

Here is the feature: add the option to create a room on the fly, indicating the topic of the branching which get visible as an infobuble to all participants, enabling to switch to this new room.

I guess a prototype could simply be a webapp which does all this creating new jitsi rooms with the selected users.

**Comment by ibauersachs** [comment]
Is this about a new feature in [Jitsi Meet](https://meet.jit.si/) or for VoIP calls in Jitsi Desktop (this project)?

**Comment by jibe-b** [comment]
I think it could be for both but you're right that I thought of Jitsi Meet first.

**Comment by ibauersachs** [comment]
I don't think there's enough use cases in regular VoIP calls to keep this open (and definitely no developer resources). If someone is interested to build this though, pull requests are welcome.
