### ISSUE TITLE
[Question] TCP for VoIP transport  supported?

### ISSUE THREAD

**Issue by HulaHoopWhonix** [jitsi/jitsi#450]
Hi I was wondering if Jitsi can use TCP as a VoIP transport and not just for signalling with SIP. Does the Jingle implementation cover this? 

I am working on Whonix, an anonymity OS that tunnels all traffic over Tor. Tor only supports TCP traffic and so severely limits VoIP choices. 

/cc @adrelanos

**Comment by ibauersachs** [comment]
No, this isn't possible. TCP is in general not the best choice for real-time data. But even if it were possible to use (S)RTP over TCP (with [lib]jitsi), I think the latency added by Tor would make a call completely unusable.

**Comment by jitsi-developers** [comment]
Just informational,

**Comment by bgrozev** [comment]
Just informational: ice/tcp should be easy to add with recent ice4j
versions. But it won't just work with tor.

Boris

Ps disregard the last email, I misclicked and sent early
