### ISSUE TITLE
Supported hardware?

### ISSUE THREAD

**Issue by JosefWN** [jitsi/jitsi#456]
Is there a list of supported hardware somewhere? We are planning on migrating our current solution to a self hosted Jitsi-setup and we have some fairly pricy Cisco SX10 web conference systems which we would ideally like to keep.

**Comment by traud** [comment]
This repository is about ‘Jitsi Desktop’, a desktop app for the operating systems Microsoft Windows, Apple macOS, and Linux (Debian, Ubuntu). It is very much like a client. Are you about another product, camera hardware, or interoperability with a specific product?
