### ISSUE TITLE
Evaluate Salsify for video transport

### ISSUE THREAD

**Issue by thekyriarchy** [jitsi/jitsi#470]
It outperforms the rest: https://snr.stanford.edu/salsify/

**Comment by ibauersachs** [comment]
GPL licensed and thus useless.

**Comment by thekyriarchy** [comment]
Uh, it's not meant to be used as-is but to have the design implemented in other projects.

> The implementation is only for Linux and doesn't have audio. The value is mostly in demonstrating the benefit of Salsify’s design and in allowing other researchers (and industry) to replicate our results, with the intent that Salsify’s ideas will be incorporated by others and improve the quality of real-time video in many applications.

**Comment by ibauersachs** [comment]
I'm unable to even maintain the current implementation of protocols/codecs properly, let alone adding a new one.
