### ISSUE TITLE
Event variables ?

### ISSUE THREAD

**Issue by schmurtzm** [jitsi/jitsi#476]
Hi,

I'm trying to send a notification on my phone when kitsi (on Windows) is ringing.
I don't know it there's a better way but I choose to create a script that I run with an event on incoming call.

Is there any variable that I can variable that I can pass into the script to get the incoming number for example ?

Thanks

**Comment by ibauersachs** [comment]
Yes, you can use the pattern `${variable}`, where variable is one of:
- caller.uri
- caller.address
- caller.name
- caller.id
