### ISSUE TITLE
git install: jitsi/sc-bundles/os-specific/linux does not exist

### ISSUE THREAD

**Issue by Af0x** [jitsi/jitsi#488]
Hello,
when I try to install as following:
> git clone https://github.com/jitsi/jitsi.git

and then run 

> ant run

It gives me: 

> deploy-os-specific-bundles:
> BUILD FAILED
> /folder/to/jitsi/build.xml:901: /folder/to/jitsi/sc-bundles/os-specific/linux does not exist.

Regards,

Af0x

**Comment by damencho** [comment]
First do, ant rebuild.

**Comment by Af0x** [comment]
running ant rebuild didn´t change the problem for me.

**Comment by Af0x** [comment]
I have to correct myself. It did work after I deleted the whole folder and cloned again. Thank you!

**Comment by Af0x** [comment]
I have an additional question: is it possible to have a shortcut to run jitsi without the need of an open terminal window?
