### ISSUE TITLE
Systray notifications on Windows

### ISSUE THREAD

**Issue by nickaein** [jitsi/jitsi#507]
Does Jitsi support showing notification count on systray icon?  (Windows 10)

That could be useful as I have the habit of minimizing not-so-frequently-used applications to Systray. 

If the answer is no, will a pull-request for implementing this feature be accepted?

**Comment by ibauersachs** [comment]
Yes, this is supported. Feel free to open a pull request if you think there's room for improvement.

**Comment by nickaein** [comment]
Hi Ingo,

But it doesn't work for me on Windows 10.

While I get the notification icon in the Taskbar, the icon in system tray doesn't have any indication for a missed call.

OS: Windows 10 Version 1803
Jitsi: Version 2.10.5550

**Comment by ibauersachs** [comment]
Sorry, I didn't read your question properly. The tray icon doesn't show the number of missed calls. I'd rather not touch this code since it is brittle enough as it is.
If you really want to work on this (e.g. with a PR), it must properly work on Linux as well.

**Comment by nickaein** [comment]
> Sorry, I didn't read your question properly. 

No problem. Being always quick to response and prompt has its perks ;)

> The tray icon doesn't show the number of missed calls.

It would be great if it indicates there was some missed call at least (e.g. just a red dot above the regular icon). I'll try my chances to see if I can get it working.

> it must properly work on Linux as well.

Do you mean such feature must be implemented for all supported platforms (Windows, Linux and macOS?)? Can a PR implement this feature on Windows for now and leave the behavior on other platforms unaffected?

**Comment by lozaria** [comment]
I'm interested in systray icon for missed calls also. I can't believe it doesn't have such a feature. Now I can't find out if there are missed calls at all.
