### ISSUE TITLE
REQUEST: Slack-Like Skin

### ISSUE THREAD

**Issue by exabrial** [jitsi/jitsi#516]
I think Jitsi could really take off in the enterprise space if a slack-like skin could be applied to the UI. Essentially, when the user first boots the app, a predefined list of chat rooms appears they can select from, and contacts appear in different section.

**Comment by ibauersachs** [comment]
Creating a new skin would currently be too much work. But please feel free to submit a pull request for some improvements.

A user can already join a list of chatrooms automatically if he elects to do so. XMPP servers can also provide a list of chat rooms to choose from (via File -> Add Chat Room).
