### ISSUE TITLE
Dont want to display jitsi page after call hangup

### ISSUE THREAD

**Issue by rohiniuk** [jitsi/jitsi#544]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
When i hang up any call , it displays default blue colored page (Close/Welcome page) with **" Start New Meeting "** Option.
Setting up different config variables but still no luck.
 

## Current behavior
---

## Expected Behavior
I Dont want that page to display.

## Possible Solution
---

## Steps to reproduce
---

# Environment details
*Application is in **Angular 6**

` config : {  
                   startWithAudioMuted : false,
                   startWithVideoMuted : false ,
                   enableWelcomePage: true,
                   enableClosePage: true,
                   url:""
                  },
      isUserInteractionEnabled : true,
      interfaceConfigOverwrite: {
        DEFAULT_REMOTE_DISPLAY_NAME :this.fromdisplay,
        DEFAULT_LOCAL_DISPLAY_NAME : this.ologgedInUser.entity.display,
        DISPLAY_WELCOME_PAGE_CONTENT: false,
        GENERATE_ROOMNAMES_ON_WELCOME_PAGE: false,
        APP_NAME: 'Test Meet',
        NATIVE_APP_NAME: 'Test Meet',
        SHOW_WATERMARK_FOR_GUESTS: false,
        SHOW_JITSI_WATERMARK: false,
        CLOSE_PAGE_GUEST_HINT: false,
        RECENT_LIST_ENABLED: false
      },`

**Comment by damencho** [comment]
Please for problems and question use the community forum before opening an issue.

You need to enable in the config: enableClosePage: true,
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L237
This will redirect you to a static close page.

**Comment by damencho** [comment]
There is no such option, it is in the code https://github.com/jitsi/jitsi-meet/blob/b7b43e8d9c582910aa043a522fbe1b19500c2b44/conference.js#L226
It is always static/close.html
