### ISSUE TITLE
Special characters are HTML encoded in chat

### ISSUE THREAD

**Issue by jsooter** [jitsi/jitsi#559]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Special characters are HTML encoded in chat

## Current behavior
---
After submitting chat text special characters appear in the chat pane HTML encoded

## Expected Behavior
---
Special characters should display correctly and not as html encoded strings

## Possible Solution
---
It may be that the text is being encoded twice

## Steps to reproduce
---
Enter a special character (<> or newline) into the chat input box and hit enter. The text will display as `&lt;` `&gt;` or `<br>`

# Environment details
---
Server: Unknown
Client: Chrome browser , MacOS Mojavi 10.14.1

**Comment by ibauersachs** [comment]
Since you mention Chrome, I assume you're referring to [Jitsi Meet](https://github.com/jitsi/jitsi-meet). Please report it there.
