### ISSUE TITLE
Information Regarding Audio codec

### ISSUE THREAD

**Issue by humabajwa** [jitsi/jitsi#561]
Hi,

I need information regarding the audio codec being used by jitsi. Moreover, i need the EXACT point in the code where the audio stream enters the codec. Can you please help me? Thanks

**Comment by ibauersachs** [comment]
You can open the call information window to look up the chosen codec. The actual codec for e.g. ulaw is in libjitsi, where data is converted to ulaw at https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/codec/audio/ulaw/JavaEncoder.java#L204

**Comment by humabajwa** [comment]
Thank you for your reply. This was really helpful. Can you also please indicate in the code, where is the actual codec negotiation taking place and from which file/line of jitsi is the chosen codec called from libjitsi?

Thank you for your help.
