### ISSUE TITLE
Bouncy Castle 1.70 (2021-11-29) instead of 1.54 (CVEs)

### ISSUE THREAD

**Issue by Neustradamus** [jitsi/jitsi#562]
@emcho, @damencho, @ibauersachs, @saghul: Urgently, can you update Bouncy Castle 1.54 to 1.70 (2021-11-29)?

PR for Jitsi: https://github.com/jitsi/jitsi/pull/564

- https://github.com/jitsi/jitsi-universe-public/blob/master/pom.xml#L37 (archived)

- https://github.com/jitsi/jitsi/blob/master/build.xml#L989
- https://github.com/jitsi/jitsi/blob/master/m2/pom.xml#L13

- https://github.com/jitsi/jitsi/blob/master/m2/jitsi-certificate/pom.xml#L21

- https://github.com/jitsi/webrtc/blob/master/DEPS#L230 (linked to Chromium)

- http://www.bouncycastle.org/latest_releases.html
- http://www.bouncycastle.org/releasenotes.html

CVEs:
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

Linked to: https://github.com/jitsi/jitsi-universe-public/issues/1

**Comment by saghul** [comment]
Aare we affected by the issues described in the CVEs? At least one of them mentions that it only affects a certain low-level API usage.

Just trying to gauge the urgency here.

**Comment by Neustradamus** [comment]
@saghul: There are a lot because there are very old Bouncy Castle versions in code...
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

And you can look on Jitsi community, problems and solutions:
- https://community.jitsi.org/search?q=bouncycastle%20order%3Alatest

After the little version updates in files, maybe good to see all other tickets about XMPP ^^

Thanks in advance!

**Comment by Neustradamus** [comment]
Linked to https://github.com/jitsi/libjitsi/pull/461.

**Comment by Neustradamus** [comment]
Updated to 1.61.

**Comment by Neustradamus** [comment]
Updated to 1.63.
cc: @GNUDimarik.

**Comment by Neustradamus** [comment]
@emcho, @damencho, @ibauersachs, @saghul: Last version is 1.64.
cc: @GNUDimarik, @JonathanLennox.
- http://www.bouncycastle.org/latest_releases.html
- http://www.bouncycastle.org/releasenotes.html

**Comment by Neustradamus** [comment]
@emcho, @damencho, @ibauersachs, @saghul: Last version is 1.65.
cc: @GNUDimarik, @JonathanLennox.

- http://www.bouncycastle.org/latest_releases.html
- http://www.bouncycastle.org/releasenotes.html

CVE: https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
A lot of other tickets about Bouncy Castle and Jitsi:
- https://github.com/jitsi/jitsi/issues/562
- https://github.com/jitsi/jitsi/pull/564
- https://github.com/jitsi/bccontrib/pull/3
- https://github.com/jitsi/jitsi-srtp/pull/13
- https://github.com/jitsi/libjitsi/pull/522
- https://github.com/jitsi/jitsi-hammer/issues/36
- https://github.com/jitsi/jitsi-media-transform/pull/253
- https://github.com/jitsi/jigasi/pull/259
- https://github.com/jitsi/otr4j/pull/32
- https://github.com/jitsi/zrtp4j/pull/3

- https://github.com/search?p=1&q=org%3Ajitsi+Bouncy+Castle&type=Issues

**Comment by ibauersachs** [comment]
I'm working on migrating the entire Jitsi Desktop build to Gradle. After that is done all the dependencies can and will be updated.

**Comment by Neustradamus** [comment]
@ibauersachs: In a few time, very soon?
Because this problem is not new... :/
Thanks in advance.

**Comment by Neustradamus** [comment]
Currently, the last Bouncy Castle version is:
- 1.69 (2021-06-07)

**Comment by Neustradamus** [comment]
Currently, the last Bouncy Castle version is:
- 1.70 (2021-11-29)

**Comment by Neustradamus** [comment]
The current BouncyCastle version used in this Jitsi repository is 1.75, I can now close this ticket.

Links:
- https://github.com/jitsi/jitsi
- https://github.com/jitsi/jitsi/blob/master/pom.xml
- https://github.com/jitsi/jitsi/pull/803
- https://github.com/jitsi/jitsi/issues/745
- https://github.com/jitsi/jitsi/pull/741
- https://github.com/jitsi/jitsi/pull/564
- https://github.com/jitsi/jitsi/issues/562
- https://github.com/jitsi/jitsi/pull/43
