### ISSUE TITLE
Jitsi 1.0 snapshot compile errors

### ISSUE THREAD

**Issue by mcacker** [jitsi/jitsi#579]
Hi,

i've just started getting compile errors when compiled against the 1.0 snapshot hosted here (at https://github.com/jitsi/jitsi-maven-repository/raw/master/snapshots/):

cannot find symbol
  symbol:   class MediaType
  location: package org.jitsi.service.neomedia

Has something changed with the repo?

It started sometime yesterday afternoon, and I can no longer build my application due to this.  

thanks, Mitchell

**Comment by bgrozev** [comment]
Hey, we moved `MediaType` to the [jitsi-utils](https://github.com/jitsi/jitsi-utils) package (as `org.jitsi.utils.MediaType`). You'll need to update your app if you want to follow the snapshots.

Heads up: more changes to come as we extract more classes to jitsi-utils.

**Comment by mcacker** [comment]
Thanks for the prompt reply.

Is there a 1.0 release prior to these changes that I can use?  In looking through the releases repo (https://github.com/jitsi/jitsi-maven-repository/raw/master/releases), I only see versions of 2.13...

**Comment by bgrozev** [comment]
I'm not sure. @damencho do we have maven packages of the previous Jitsi release somewhere?

**Comment by damencho** [comment]
I don't get it, what 1.0 version is needed? All maven packages are there in the repo, latest are in release, there are some also some 2.13 and 2.9 in snapshots.

**Comment by mcacker** [comment]
What I need is a release of libjitsi that I can build against that was equivalent to 1.0-SNAPSHOT from before the above mentioned refactoring.  I do not see that in the repo - in fact I see no libjitsi artifact.  

I've worked around by specifying in my POM

  		<dependency>
			<groupId>org.jitsi</groupId>
			<artifactId>libjitsi</artifactId>
			
			<version>1.0-20190209.114241-378</version>
		</dependency>

but, obviously, this is less than ideal.  Before today I was specifying 1.0-SNAPSHOT.  It's hard to remember, but maybe because I couldn't find a suitable release before.

**Comment by damencho** [comment]
Here are all libjitsi artefacts: https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/org/jitsi/libjitsi/1.0-SNAPSHOT
Version ...-379 is the last one without jitsi-utils.

**Comment by mcacker** [comment]
right, but all these are snapshots, I was wanting a release that I could base my build on

**Comment by damencho** [comment]
We are using timestamped snapshots, we do not do releases. Every version of a library is in snapshots.

**Comment by mcacker** [comment]
ok, thanks

**Comment by Neustradamus** [comment]
It is possible to update the Jitsi sourcecode to resolve several vulns?
Thanks in advance.
