### ISSUE TITLE
Can jitsi compile and run in mac environment?

### ISSUE THREAD

**Issue by GZJayson** [jitsi/jitsi#589]
Can jitsi compile and run in mac environment? I get error java.lang.UnsatisfiedLinkError after launching in idea: net.java.sip.communicator.util.launchutils.AEGetURLEventHandler.setAEGetURLListener

**Comment by damencho** [comment]
Yes it can. This is an jvm agent binary that needs to be in special path when running and that is taken care of the info.plist file when dmg is created and used.

Please use the community forum before opening new issues.
