### ISSUE TITLE
Jitsi apt repo - Problem with certificate

### ISSUE THREAD

**Issue by pizzadude** [jitsi/jitsi#591]
## Description
Today I did an apt update, and I get this error:

Err:34 https://download.jitsi.org stable/ Release                                                                                                                       
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 130.79.200.22 443]

Same with unstable repo.

Reading package lists... Done                      
E: The repository 'https://download.jitsi.org stable/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://download.jitsi.org unstable/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

## Current behavior
Certificate seems to be expired

## Expected Behavior
The certificate to work

## Possible Solution
Updating the cert

## Steps to reproduce
install ubuntu or another distro that uses apt, add jitsi apt repo, notice that the cert is expired

# Environment details
tested on linux mint 19.1

**Comment by adamreed90** [comment]
Any core developers alive?

**Comment by damencho** [comment]
This is known issue anb we are wokring on fixing it.

**Comment by ibauersachs** [comment]
@damencho Why don't you leave the issue open until it's fixed? People will find it instead of creating new ones.

**Comment by damencho** [comment]
Sorry, trying to fix a million things.
And when you open an issue it forwards you to community.jitsi.org where this had been posted a hundred times... so it is the same.

**Comment by damencho** [comment]
All issues had been fixed and download.jitsi.org is back.

**Comment by tabacha** [comment]
Does not work here:
```
apt-get update
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://ftp.debian.org/debian buster InRelease                                                                                                                                                                  
Hit:3 https://repos.influxdata.com/debian buster InRelease                                                                                                                                                           
Hit:4 http://ftp.debian.org/debian buster-updates InRelease                                                                                  
Ign:5 https://download.jitsi.org stable/ InRelease                                                                                          
Err:6 https://download.jitsi.org stable/ Release                                                                      
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2001:660:2402::22 443]
Hit:7 http://cdn-fastly.deb.debian.org/debian buster-backports InRelease      
Reading package lists... Done
E: The repository 'https://download.jitsi.org stable/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by tabacha** [comment]
How do I reopen this ticket?
```
wget  -v -O - https://download.jitsi.org/jitsi-key.gpg.key
--2020-05-30 13:04:23--  https://download.jitsi.org/jitsi-key.gpg.key
Resolving download.jitsi.org (download.jitsi.org)... 2001:660:2402::22, 130.79.200.22
Connecting to download.jitsi.org (download.jitsi.org)|2001:660:2402::22|:443... connected.
ERROR: The certificate of 'download.jitsi.org' is not trusted.
ERROR: The certificate of 'download.jitsi.org' has expired.
root@meet:~# date
Sat May 30 13:05:08 UTC 2020
root@meet:~# wget -4 -v -O - https://download.jitsi.org/jitsi-key.gpg.key
--2020-05-30 13:05:14--  https://download.jitsi.org/jitsi-key.gpg.key
Resolving download.jitsi.org (download.jitsi.org)... 130.79.200.22
Connecting to download.jitsi.org (download.jitsi.org)|130.79.200.22|:443... connected.
ERROR: The certificate of 'download.jitsi.org' is not trusted.
ERROR: The certificate of 'download.jitsi.org' has expired.

```

**Comment by briannyagol** [comment]
Getting the same issue, again:

`Ign:11 https://download.jitsi.org stable/ Translation-en
Err:10 https://download.jitsi.org stable/ Packages
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 130.79.200.22 443]
Ign:11 https://download.jitsi.org stable/ Translation-en
Reading package lists... Done
E: Failed to fetch https://download.jitsi.org/stable/Packages  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 130.79.200.22 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by briannyagol** [comment]
@damencho  Is it possible to help with this issue?

**Comment by gcortina77** [comment]
error in update due to expired certificate : 

Ignorato:6 https://download.jitsi.org stable/ InRelease                                                       
Errore:7 https://download.jitsi.org stable/ Release                                                                                                                                 
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 130.79.200.22 443]

**Comment by gcortina77** [comment]
Error, iexpired certificate:

Ignorato:6 https://download.jitsi.org stable/ InRelease                                                       
Errore:7 https://download.jitsi.org stable/ Release                                                                                                                                 
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 130.79.200.22 443]

**Comment by gcortina77** [comment]
Error, iexpired certificate:

Ignorato:6 https://download.jitsi.org stable/ InRelease
Errore:7 https://download.jitsi.org stable/ Release
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate. Could not handshake: Error in the certificate verification. [IP: 130.79.200.22 443]
