### ISSUE TITLE
download.jitsi.org down

### ISSUE THREAD

**Issue by MatteoManzoni** [jitsi/jitsi#594]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
[Jitsi Download Page](https://download.jitsi.org/jitsi/) in down since yesterday 

[Is it down right now](https://www.isitdownrightnow.com/download.jitsi.org.html)

## Current behavior
---
Download page and repos can't be reached

## Expected Behavior
---
Download page and repos reachable as usual

## Steps to reproduce
---
Go to [https://download.jitsi.org/jitsi/](https://download.jitsi.org/jitsi/)

**Comment by damencho** [comment]
This is known and the certificate had expired. We are working on it. And will let you know once it is fixed.

**Comment by damencho** [comment]
All issues had been fixed and download.jitsi.org is back.

**Comment by drummer73** [comment]
Seems to be down again.
