### ISSUE TITLE
Jitsi not in default App List / Not registering tel urls

### ISSUE THREAD

**Issue by bitboy85** [jitsi/jitsi#596]
I've installed the latest jitsi on Win 10 x64.
1. I noticed thats not possible to associate jitsi wirth tel links. It is not in the list of possible programs if you select tel in the setting "default apps".
2. I think most user would expect that jitsi is associated with tel urls during installation (but maybe this fails because of 1.)

Looks same as https://github.com/jitsi/jitsi/issues/252 but its not fixed for Win 10

**Comment by ibauersachs** [comment]
1) has been fixed in #252, I have no idea why it doesn't show up four you. On a Windows 10 install here it looks like in the screenshot. 
![image](https://user-images.githubusercontent.com/949783/58173107-c09f8b80-7c9a-11e9-98a3-789aa28e96dc.png)

2) is not possible, Windows prevents changes to the default apps. The user must select it.

**Comment by bitboy85** [comment]
Found and fixed, i think.
according to this document https://docs.microsoft.com/en-us/windows/desktop/shell/default-programs
there must be two entries in the registry and one of them was missing:

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\RegisteredApplications
Name: jitsi
Type: REG_SZ
Value: SOFTWARE\WOW6432Node\Jitsi\Capabilities

after adding this it showed up in the application list.

**Comment by ibauersachs** [comment]
It might not work if you install 32bit Jitsi on Windows x64. But that combination is nonsense.

**Comment by bitboy85** [comment]
In stable build line on the webpage the link "Microsoft Windows installers" is linked to only an x86 version, thats why i thought there is only this one.

**Comment by ibauersachs** [comment]
@damencho Can you please add an x64 link to the downloads page?

**Comment by damencho** [comment]
Should I change it to x64 only? Are there any x86 available around ... ?

**Comment by damencho** [comment]
Changed it to x64 and added a linkn to the 32bit one

**Comment by ibauersachs** [comment]
Still needs to be done for the nightlies section, and what about the new download site https://jitsi.org/downloads/ (stable & nightly)?

**Comment by damencho** [comment]
Oh, I just edited old website, I will do it on the new. Nightlies there is no need to, as they are just links to the folder ....

**Comment by damencho** [comment]
Second round and should be fixed all now.

**Comment by RussH** [comment]
I just installed x86_64 jitsi today (jitsi-2.10.5550-x64.exe) on Win10 64 and this registry key was not created (had to manually add it)

**Comment by jnettels** [comment]
I also had to manually add the registry key mentioned above, in order to make jitsi show up in the "choose default app" dialog for "tel" links. (Jitsi 2.10.5550, Windows 11 64bit)
Now clicking a link to start a call works great! But I guess this issue should be reopened.

**Comment by NEBf** [comment]
Just installed jitsi desktop newly per download on Win 10. Still had to repair registry according to th am instructions.
