### ISSUE TITLE
Jabber to XMPP progress

### ISSUE THREAD

**Issue by Neustradamus** [jitsi/jitsi#601]
Since several months, I have seen improvements about it, thanks.

But in the code, there are always Jabber references in code, my question is, it is planned to move all?

Thanks in advance for have a perfect XMPP client.

**Comment by damencho** [comment]
Nope there are no such plans, as changing for example the package name is a big hassle and involves touching 10 more projects maybe. We have more priority tasks than this. 

Please use the community forum fir questions before opening new issues.

**Comment by Neustradamus** [comment]
What are the steps in progress right now?

**Comment by damencho** [comment]
This is a very low priority task so there is no progress on it, sorry.

**Comment by Neustradamus** [comment]
Have you progressed?

**Comment by damencho** [comment]
There is no progress on this, if you want to help and contribute you can create PRs in various projects.

**Comment by Neustradamus** [comment]
You can see my PRs: https://github.com/jitsi/jitsi/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3ANeustradamus ;)

**Comment by Neustradamus** [comment]
@damencho: Any news one year after this problem?

Can you reopen this ticket, it is not closed.

**Comment by Neustradamus** [comment]
@damencho: Have you progressed?

**Comment by damencho** [comment]
I don't see this to happen in the following years, looking at my more priority tasks.
