### ISSUE TITLE
WebRTC usage problem ? 

### ISSUE THREAD

**Issue by jaumard** [jitsi/jitsi#619]
Hello,

I'm interested in using Jitsi in an entreprise environment but I'm a bit worried about the usage of WebRTC, that not something I know so sorry if my questions are stupid but I read a lot that webrtc is a big pain because it's blocked by firewall, doesn't work well with entreprise proxies.

So I would like to know your opinion about those points :)

Thanks !

**Comment by damencho** [comment]
Please use the community forum for questions before opening new issues.

For example, you had posted your question as an issue in the project which is Jitsi Desktop app and has nothing to do with webrtc. 

There are many products using Webrtc in enterprise environments, there are options and resolutions to all the problems. You can test meet.jit.si and report whether it works in the environment you want to use it in.
