### ISSUE TITLE
Documentation/website issue: bug reporting instructions no longer valid

### ISSUE THREAD

**Issue by keunes** [jitsi/jitsi#623]
I checked on the [Jitsi Desktop website](https://desktop.jitsi.org/Development/BugsAndIssues) how to report bugs. On that page it says I should use the `users` mailinglist, but the link to it doesn't work. Under *Filing a new issue* I get sent to [the FAQ where I find this](https://desktop.jitsi.org/Documentation/FAQ#bug-report), and then go to the [How to report bugs](https://desktop.jitsi.org/Documentation/ReportingBugs) page (which is kind of a detour in itself, via the FAQ). There I'm told I should report to the `dev` list, but that one also doesn't work.

** I just discovered on the main jitsi site that the mailing lists are depricated and that I should use the forum instead. But it would be good if the site were updated.

**Comment by damencho** [comment]
I just updated all the mentioned places. Thanks for the report.

**Comment by keunes** [comment]
Thanks!
