### ISSUE TITLE
Screen sharing fail on Firefox whith config startScreenSharing = true

### ISSUE THREAD

**Issue by Arzar** [jitsi/jitsi#647]
## Description
Screen sharing fails to start when doing a call from Firefox with startScreenSharing = true in the config

## Current behavior

The call is establish, but the screen sharing doesn't start. (browser doesn't even ask for permission). Video doesn't start either, only the mic is on.
Error message from the console:  

```
2020-03-05T10:36:38.338Z [modules/RTC/RTCUtils.js] : Using the new gUM flow Logger.js:154:22

2020-03-05T10:36:38.338Z [modules/RTC/ScreenObtainer.js] : Using getDisplayMedia for screen sharing Logger.js:154:22

2020-03-05T10:36:38.339Z [features/base/tracks] <E/</<>: Failed to create local tracks

Array [ “desktop” ]

Object { name: “gum.chrome_extension_user_canceled”, message: “User canceled Chrome’s screen sharing prompt”, stack: “a@https://jitsi.-----------.com/libs/lib-jitsi-meet.min.js?v=3863:6:114711\nobtainScreenFromGetDisplayMedia/<@https://jitsi.-----------.com/libs/lib-jitsi-meet.min.js?v=3863:6:175762\n” }

Logger.js:154:22

2020-03-05T10:36:38.342Z [conference.js] : Failed to switch to screensharingObject { name: “gum.chrome_extension_user_canceled”, message: “User canceled Chrome’s screen sharing prompt”, stack: “a@https://jitsi.-----------.com/libs/lib-jitsi-meet.min.js?v=3863:6:114711\nobtainScreenFromGetDisplayMedia/<@https://jitsi.-----------.com/libs/lib-jitsi-meet.min.js?v=3863:6:175762\n” }

```

Note : Almost the same bug can be reproduce without starting with screen sharingstartScreenSharing = true. Start a normal call, with video by default. Wait for the call to be establish, and just give permission for the webcam to start to the browser, but don't click anywhere in the iframe. Then send a command api.executeCommand('toggleShareScreen'). If no interaction took place with the iframe until now (no click, no tab into), then the screen sharing fail with exactly the same error message as above.

## Expected Behavior
Screen sharing starts properly when the call start.

## Possible Solution
---

## Steps to reproduce
Toggle startScreenSharing = true in the config and start a call on Firefox, using external api

```
const options = {
        roomName: `${support_id}${myInfo.jroom_pw}`,
        parentNode: document.querySelector('#panelarea'),
    };
    api = new JitsiMeetExternalAPI(myInfo.server, options);
```

# Environment details
Jitsi-meet trunk with external api and custom server Ubuntu 18.04.4 LTS. 
Firefox 73.0.1 (64-bit)

**Comment by damencho** [comment]
Use the community forum, please. Wrong repo.

**Comment by Arzar** [comment]
I did already, and one of the dev recommended me to open a issue:
https://community.jitsi.org/t/screen-sharing-fail-on-firefox-desktop-until-user-click-at-least-once-on-the-jitsi-iframe/22384/2
But yes, it's the wrong repo, should be in jitsi-meet, sorry about that.
