### ISSUE TITLE
Accessibility of main site

### ISSUE THREAD

**Issue by mgifford** [jitsi/jitsi#651]
I'd love to know what work has been done to evaluate this product's accessibility. Just ran the main site through https://wave.webaim.org/ and there are a few:

<img width="1107" alt="Screenshot of Wave Toolbar Accessibility Errors" src="https://user-images.githubusercontent.com/116832/77170891-1519c000-6a92-11ea-965e-989ade8cdfa9.png">

Where is the best place to report these?  What is being done to eliminate them from other areas of the interface?

**Comment by damencho** [comment]
The correct project is https://github.com/jitsi/jitsi-meet. Thanks for the report. At this point creating a PR there is most welcome. 
The best will be if there is an automated way to check this, so once we fix them to not allow new code to miss those. Is there are open-source free access to the API of this webaim.org?

**Comment by mgifford** [comment]
Hey @damencho I added an issue in the correct queue. 

There are definitely free, automated ways to check this. Microsoft has good open source one that works with Android, Windows & Web tools - https://accessibilityinsights.io/

That's based on https://github.com/dequelabs/axe-core/

Which is now being leveraged by Google Lighthouse and a tonne of other products. 

Webaim doesn't have an open source solution, but fortunately the two above are.
