### ISSUE TITLE
NPE in NetworkUtils.determineAnyAddress

### ISSUE THREAD

**Issue by ascheman** [jitsi/jitsi#654]
Was told by a friend that he sees an NPE in his setup (details to follow):

```
20200321-185106.688 18:51:06.681 [org.jitsi.impl.osgi.framework.AsyncExecutor] ERROR org.jitsi.impl.osgi.framework.BundleImpl - Error starting bundle: net.java.sip.communicator.impl.netaddr.NetaddrActivator@fd79e60
20200321-185106.688 java.lang.ExceptionInInitializerError: null
20200321-185106.688     at net.java.sip.communicator.util.NetworkUtils.determineAnyAddress(NetworkUtils.java:1149) ~[jitsi-util-2.13.f6042d3.jar!/:?]	<--!!!!!!!!!!!!!!!!!!!
20200321-185106.688     at net.java.sip.communicator.util.NetworkUtils.<clinit>(NetworkUtils.java:62) ~[jitsi-util-2.13.f6042d3.jar!/:?]
20200321-185106.688     at net.java.sip.communicator.impl.netaddr.NetworkAddressManagerServiceImpl.initRandomPortSocket(NetworkAddressManagerServiceImpl.java:433) ~[jitsi-netaddr-2.13.f6042d3.jar!/:?]
20200321-185106.689     at net.java.sip.communicator.impl.netaddr.NetworkAddressManagerServiceImpl.start(NetworkAddressManagerServiceImpl.java:107) ~[jitsi-netaddr-2.13.f6042d3.jar!/:?]
20200321-185106.689     at net.java.sip.communicator.impl.netaddr.NetaddrActivator.start(NetaddrActivator.java:89) ~[jitsi-netaddr-2.13.f6042d3.jar!/:?]
20200321-185106.689     at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
20200321-185106.689     at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
20200321-185106.689     at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
20200321-185106.689     at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
20200321-185106.689     at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
20200321-185106.689     at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
20200321-185106.689 Caused by: java.lang.NullPointerException
20200321-185106.690     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847) ~[?:1.8.0_242]
20200321-185106.690     at java.lang.Runtime.loadLibrary0(Runtime.java:871) ~[?:1.8.0_242]
20200321-185106.690     at java.lang.System.loadLibrary(System.java:1124) ~[?:1.8.0_242]
20200321-185106.690     at java.net.NetworkInterface$1.run(NetworkInterface.java:59) ~[?:1.8.0_242]
20200321-185106.690     at java.net.NetworkInterface$1.run(NetworkInterface.java:57) ~[?:1.8.0_242]
20200321-185106.690     at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_242]
20200321-185106.690     at java.net.NetworkInterface.<clinit>(NetworkInterface.java:56) ~[?:1.8.0_242]
20200321-185106.690     ... 11 more
20200321-185106.693 18:51:06.692 [org.jitsi.impl.osgi.framework.AsyncExecutor] ERROR org.jitsi.impl.osgi.framework.launch.FrameworkImpl - Error changin
```

**Comment by gjaekel** [comment]
* This issue is concerning an installation of  jitsi-meet on openfire-4.5.1 and the openmeet-0.9.6 plugin.
* It **appear** when using AdoptOpenJDK8u242 as JVM
* It **vanish** when using OracleJDK8u202 or OracleJDK8u241

**Comment by gjaekel** [comment]
Here the complete logs of the startup using both JDKs: [logs.20200409.zip](https://github.com/jitsi/jitsi/files/4455020/logs.20200409.zip)

**Comment by ibauersachs** [comment]
Huh, I don't think there's much we can do here, and I don't think your "quick fix" helps much either. It looks like the JVM cannot load the `net` native library, see https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/net/NetworkInterface.java#L59

No idea why, but this is bizarre.

**Comment by gjaekel** [comment]
Dear Ingo,
this "quick fix" was just a try because we though that it was may related to some strange IPv6 detection (; we don't use it yet). But with this patch applied, just the next Exception pops up concerning something like finding a random port.

**Comment by ibauersachs** [comment]
The net library is actually part of the JVM itself, so it should be in JVM_HOME/bin. It almost certainly is there, otherwise the hosting Openfire instance wouldn't be able to connect to any network either.

Are the Jitsi/Ofmeet libraries loaded in Openfire for the correct architecture of the JVM, i.e. x86 for x86? I'm not sure how you guys bundle that stuff.

**Comment by gjaekel** [comment]
I just located it in the `.../jre/lib/rt.jar`:
```
root@evalfire0 ~ # cd /opt/oracle-jdk-bin-1.8.0.241/jre/lib/                                                                                  20200409-141700
root@evalfire0 /opt/oracle-jdk-bin-1.8.0.241/jre/lib # unzip -l rt.jar | grep "java/net/N"
     1831  12-11-2019 02:26   java/net/NetworkInterface$1checkedAddresses.class
     1086  12-11-2019 02:26   java/net/NetworkInterface$1subIFs.class
     1005  12-11-2019 02:26   java/net/NetworkInterface$2.class
      667  12-11-2019 02:26   java/net/NetworkInterface$1.class
     6664  12-11-2019 02:26   java/net/NetworkInterface.class
      381  12-11-2019 02:26   java/net/NoRouteToHostException.class
      410  12-11-2019 02:26   java/net/NetPermission.class                                                                                    20200409-141703

root@evalfire0 ~ # cd /opt/openjdk-bin-8.242_p08/jre/lib/                                                                                     20200409-141722
root@evalfire0 /opt/openjdk-bin-8.242_p08/jre/lib # unzip -l rt.jar | grep "java/net/N"
     1831  01-19-2020 14:50   java/net/NetworkInterface$1checkedAddresses.class
     1086  01-19-2020 14:50   java/net/NetworkInterface$1subIFs.class
     1005  01-19-2020 14:50   java/net/NetworkInterface$2.class
      667  01-19-2020 14:50   java/net/NetworkInterface$1.class
     6664  01-19-2020 14:50   java/net/NetworkInterface.class
      381  01-19-2020 14:50   java/net/NoRouteToHostException.class
      410  01-19-2020 14:50   java/net/NetPermission.class     
```
No differences!

**Comment by gjaekel** [comment]
> Are the Jitsi/Ofmeet libraries loaded in Openfire for the correct architecture of the JVM, i.e. x86 for x86? I'm not sure how you guys bundle that stuff.
How to check this, please?

**Comment by gjaekel** [comment]
Hey, in the exceptions, there is a line
```
at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
```
Is this a hint that it is thinking about Android as a plattform?

**Comment by ibauersachs** [comment]
> Hey, in the exceptions, there is a line
> 
> ```
> at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231) [jitsi-android-osgi-1.0-20180322.162617-2.jar!/:?]
> ```
> 
> Is this a hint that it is thinking about Android as a plattform?

No, this library is just a very lightweight OSGi implementation (well, it actually isn't one, but that shouldn't matter here).

**Comment by ibauersachs** [comment]
> > Are the Jitsi/Ofmeet libraries loaded in Openfire for the correct architecture of the JVM, i.e. x86 for x86? I'm not sure how you guys bundle that stuff.
> > How to check this, please?

I don't know, I'm not affiliated with Ofmeet. @guusdk ?

**Comment by ibauersachs** [comment]
> I just located it in the `.../jre/lib/rt.jar`:
> 
> ```
> root@evalfire0 ~ # cd /opt/oracle-jdk-bin-1.8.0.241/jre/lib/                                                                                  20200409-141700
> root@evalfire0 /opt/oracle-jdk-bin-1.8.0.241/jre/lib # unzip -l rt.jar | grep "java/net/N"
>      1831  12-11-2019 02:26   java/net/NetworkInterface$1checkedAddresses.class
>      1086  12-11-2019 02:26   java/net/NetworkInterface$1subIFs.class
>      1005  12-11-2019 02:26   java/net/NetworkInterface$2.class
>       667  12-11-2019 02:26   java/net/NetworkInterface$1.class
>      6664  12-11-2019 02:26   java/net/NetworkInterface.class
>       381  12-11-2019 02:26   java/net/NoRouteToHostException.class
>       410  12-11-2019 02:26   java/net/NetPermission.class                                                                                    20200409-141703
> 
> root@evalfire0 ~ # cd /opt/openjdk-bin-8.242_p08/jre/lib/                                                                                     20200409-141722
> root@evalfire0 /opt/openjdk-bin-8.242_p08/jre/lib # unzip -l rt.jar | grep "java/net/N"
>      1831  01-19-2020 14:50   java/net/NetworkInterface$1checkedAddresses.class
>      1086  01-19-2020 14:50   java/net/NetworkInterface$1subIFs.class
>      1005  01-19-2020 14:50   java/net/NetworkInterface$2.class
>       667  01-19-2020 14:50   java/net/NetworkInterface$1.class
>      6664  01-19-2020 14:50   java/net/NetworkInterface.class
>       381  01-19-2020 14:50   java/net/NoRouteToHostException.class
>       410  01-19-2020 14:50   java/net/NetPermission.class     
> ```
> 
> No differences!

I'm talking about libnet.so, the native sockets implementation, not classes in rt.jar.

**Comment by gjaekel** [comment]
Guus pointed to Jitsi because OFMeet just use it :)

**Comment by gjaekel** [comment]
> I'm talking about libnet.so, the native sockets implementation, not classes in rt.jar.
Oh, i see. Will look for this.

**Comment by ibauersachs** [comment]
Well AFAIK "just use" isn't quite right, there must be some wrapping going on. JVB, Jigasi, Jicoco etc. were never meant to be run as a plugin in the same JVM.

**Comment by guusdk** [comment]
Note that this problem is specific to AdoptOpenJDK.

**Comment by gjaekel** [comment]
```
root@evalfire0 /opt # ll oracle-jdk-bin-1.8.0.241/jre/lib/amd64/libnet.so 
-rwxr-xr-x 1 root root 111K Dec 11 11:35 oracle-jdk-bin-1.8.0.241/jre/lib/amd64/libnet.so*                                                    20200409-143143
root@evalfire0 /opt # ll openjdk-bin-8.242_p08/jre/lib/amd64/libnet.so 
-rwxr-xr-x 1 root root 116K Jan 19 15:53 openjdk-bin-8.242_p08/jre/lib/amd64/libnet.so*                                                       20200409-143159
root@evalfire0 /opt # lld openjdk-bin-8.242_p08/jre/lib/amd64/libnet.so 
```

**Comment by gjaekel** [comment]
> Note that this problem is specific to AdoptOpenJDK.
At least to my installation of AdoptOpenJDK. ;) 
Please also note, that this is **exactly** the same installation of the application - I'm just switching the JVM provider around.

**Comment by gjaekel** [comment]
I may run a jar with a "minimal testcase", if you like. I'm not at home between 15:15 and about 17:30 (UTC+1)

**Comment by ibauersachs** [comment]
I couldn't repro this so far. Did you already try the [RedHat provided JDK](https://adoptopenjdk.net/upstream.html) (or is this the one you're referring to as Oracle)?

**Comment by ibauersachs** [comment]
Okay, so this is probably caused by illegal reflection somwhere in Ofmeet. See e.g. these bug reports for 8u242:
- https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-January/011026.html
- https://bugzilla.redhat.com/show_bug.cgi?id=1805105

I see the same JDK-internal field being accessed by multiple Igniterealtime libs:
https://github.com/search?q=org%3Aigniterealtime+sys_paths&type=Code
(some of this code is 15 years old)

This is not a Jitsi issue. Please report this to the respective projects at igniterealtime, @guusdk might point to the right people.

**Comment by gjaekel** [comment]
Using the testcase (`https://bugzilla.redhat.com/attachment.cgi?id=1664564`) provided in `https://bugzilla.redhat.com/show_bug.cgi?id=1805105` , I' able to confirm this:
```
root@evalfire0 ~/Demo/target/Demo-0.0.1-SNAPSHOT-cri # eselect java-vm set system 2                                                           20200410-212716
root@evalfire0 ~/Demo/target/Demo-0.0.1-SNAPSHOT-cri # java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)                                                                              20200410-212719
root@evalfire0 ~/Demo/target/Demo-0.0.1-SNAPSHOT-cri # java -jar Demo-0.0.1-SNAPSHOT.jar 
10.04.2020-21:27:26 INFO  - Application                              - Initializing application
10.04.2020-21:27:26 INFO  - Application                              - Setting java.library.path to: ./lib
10.04.2020-21:27:26 INFO  - Application                              - Launching Application.
10.04.2020-21:27:26 INFO  - Application                              - Host: evalfire0 (10.69.59.142)                                         20200410-212726
root@evalfire0 ~/Demo/target/Demo-0.0.1-SNAPSHOT-cri # eselect java-vm set system 1                                                           20200410-212738
root@evalfire0 ~/Demo/target/Demo-0.0.1-SNAPSHOT-cri # java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)                                                                         20200410-212740
root@evalfire0 ~/Demo/target/Demo-0.0.1-SNAPSHOT-cri # java -jar Demo-0.0.1-SNAPSHOT.jar 
10.04.2020-21:27:43 INFO  - Application                              - Initializing application
10.04.2020-21:27:43 INFO  - Application                              - Setting java.library.path to: ./lib
10.04.2020-21:27:43 INFO  - Application                              - Launching Application.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at app.client.Application.getLocalHost(Application.java:35)
	at app.client.Application.main(Application.java:44)
Caused by: java.lang.NullPointerException
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at java.net.InetAddress$1.run(InetAddress.java:295)
	at java.net.InetAddress$1.run(InetAddress.java:293)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.InetAddress.<clinit>(InetAddress.java:292)
	... 2 more                              
```
But IMHO, as described in that issue, this is because bad code relying on internals of the JVM-specific classloader. This may also hold for the hits of the search over the IgniteRealtime-Code you pointed out.

But, also IMHO, this can't be the reason why the `libnet.so` isn't found by the `rt.jar`

**Comment by gjaekel** [comment]
I also confirm, that the testcase will run on `OpenJDK8u232`. So it's realy seems to be an regression introduced with `OpenJDK8u242`
```
root@evalfire0 ~/Demo # java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)                                                                         20200410-221312
root@evalfire0 ~/Demo # java -jar target/Demo-0.0.1-SNAPSHOT-cri/Demo-0.0.1-SNAPSHOT.jar 
10.04.2020-22:13:18 INFO  - Application                              - Initializing application
10.04.2020-22:13:18 INFO  - Application                              - Setting java.library.path to: ./lib
10.04.2020-22:13:18 INFO  - Application                              - Launching Application.
10.04.2020-22:13:18 INFO  - Application                              - Host: evalfire0 (10.69.59.142) ```

**Comment by gjaekel** [comment]
I also confirm, that my installation of OpenFire/OpenMeeting will **start** using **OpenJDK8u232**!

Summary:
* This issue is concerning an installation of jitsi-meet on openfire-4.5.1 and the openmeet-0.9.6 plugin.
*  It appear when using AdoptOpenJDK8u242 as JVM
* It vanish when using OracleJDK8u202 or OracleJDK8u241
* **It also vanish when using AdoptOpenJDK8u232**

Therefore, it hits the regression described in [https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-January/011026.html](https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-January/011026.html)

Thank you all for clarification!

**Comment by ibauersachs** [comment]
> But IMHO, as described in that issue, this is because bad code relying on internals of the JVM-specific classloader. This may also hold for the hits of the search over the IgniteRealtime-Code you pointed out.
> 
> But, also IMHO, this can't be the reason why the `libnet.so` isn't found by the `rt.jar`

Yes it can, quite easily actually. The reflection code in Openfire (and lots of other systems, e.g. JetBrains' YouTrack too) sets the JDK internal variable `sys_paths` to `null`. Now JDKs before 8u242 renitialized `sys_paths` from the system property `java.native.library` if it was null during _any_ `System.loadLibrary` call. Now it doesn't anymore as it is initialized differently.
And it doesn't stop there, JDKs >= 15 get rid of the field entirely. So everyone attempting to 'fix' this by further fiddling with it will run into troubles again.

It's unclear to me why this doesn't happen on Oracles JDK 8. But since the commits in AdoptOpenJDK show Azul copyright headers, I assume this is a backport from a newer JDK. I'm speculating now, but Oracle probably didn't backport this (or at least not identical) because some of their systems rely on the same behaviour. I would assume that this change breaks almost any system that has plugins relying on dynamically loading native code and not using JNA.

**Comment by gjaekel** [comment]
I also confirm, that my installation of OpenFire/OpenMeeting will **start** using **OpenJDK8u232**!

Summary:
* This issue is concerning an installation of jitsi-meet on openfire-4.5.1 and the openmeet-0.9.6 plugin.
*  It appear when using AdoptOpenJDK8u242 as JVM
* It vanish when using OracleJDK8u202 or OracleJDK8u241
* **It also vanish when using AdoptOpenJDK8u232**

Therefore, it hits the regression described in [https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-January/011026.html](https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-January/011026.html)

Thank you all for clarification!

**Comment by gjaekel** [comment]
I actually was able to use the installation of Openfire **successfully** with the new release of `AdoptOpenJDK8u252`
```
root@evalfire2 /opt # java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

**Comment by ibauersachs** [comment]
Seems they reverted the backport due to widespread issues.
https://bugs.openjdk.java.net/browse/JDK-8240521

**Comment by gjaekel** [comment]
Damn!

I just was supporting some OpenFire user who installed this application on a fresh VM using Ubuntu20. Currently this provide OpenJDK11.0.9+11, and here the same regression occurs!

```
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode)
```

This user switched to Java8u272 and try some Jav14, also. With both, the problem vanish!
