### ISSUE TITLE
Screen Sharing on Wayland not Possible

### ISSUE THREAD

**Issue by philschenker** [jitsi/jitsi#656]
## Description
I can't share any windows running with Wayland or the whole screen when I started a session on meet.jit.si. I'm running on sway (i3 alternative running Wayland only). I can select XWayland windows and sharing of those works.

## Current behavior
I can only share XWayland windows.

## Expected Behavior
I would like to share all windows also those running on Wayland

## Possible Solution
---

## Steps to reproduce
---

# Environment details
Running latest Manjaro with 5.5.8 kernel on Sway

**Comment by piegamesde** [comment]
Is your browser running under Wayland or XWayland? If it's the latter, there's no chance the browser will be able to capture the screen from Wayland windows.

**Comment by kflak** [comment]
I can confirm this. Running Sway on Arch Linux, I can't share wayland-native applications from 1. firefox (wayland-enabled), 2. jitsi-meet-desktop (as far as I can tell running wayland-natively). When trying to share the entire screen I get a black screen only. Trying to share fx Firefox or Audacity (both wayland-native) doesn't work. Changing desktop to i3 solves the problem, but I'd rather not do that...

**Comment by philschenker** [comment]
> Is your browser running under Wayland or XWayland? If it's the latter, there's no chance the browser will be able to capture the screen from Wayland windows.

Browser (Firefox) is running on Wayland. The same behaviour (also with black screen) is present with the application Slack.

**Comment by ibauersachs** [comment]
This repository is for Jitsi Desktop, the legacy chat and VoIP client.
In general, please discuss issues in the [community forums](https://community.jitsi.org/) first before opening bugs on GitHub. If it is confirmed there, the proper repository for Jitsi Meet is here: https://github.com/jitsi/jitsi-meet

**Comment by piegamesde** [comment]
@ibauersachs I think it would be better to move the issue to the correct repo instead of closing it.
