### ISSUE TITLE
Relation to jitsi-meet

### ISSUE THREAD

**Issue by Turakar** [jitsi/jitsi#657]
I am almost sure somebody already asked this, but I could not find a corresponding issue or readme. So here is my question:

Can jitsi/jitsi be used as a client for jitsi/jitsi-meet or what is the relation between those two projects?

Looking at the wrongly posted issues on this repo some clarification in the readme would be helpful.

**Comment by alexanderadam** [comment]
> I am almost sure somebody already asked this

Indeed, for example [here](https://community.jitsi.org/t/jitsi-users-confused-with-jitsi-products/12873/2) and [here](https://community.jitsi.org/t/jitsi-users-jitsi-meet-vs-jitsi-desktop/12829/2).

**Comment by damencho** [comment]
Thanks @alexanderadam for the links
