### ISSUE TITLE
Allow moderator to define user names

### ISSUE THREAD

**Issue by eogut** [jitsi/jitsi#663]
Hi, I'd like to provide a suggestion to Jitsi: I'm convincing people to use Jitsi for secure video conferences, but most of these folks are quite tech illiterate. I suggest that the session initiator (moderator) should have the ability to set users names, which can be overridden by the user themselves. This would make it easier to understand who wants to speak.

Thanks and great work so far!

**Comment by damencho** [comment]
Please use the community forum when you have questions, problems or suggestions before opening new issues.

Wrong repo. There are already options that will force users to write displayname the first time they join, which can be enabled on self hosted deployments.
