### ISSUE TITLE
Jitsi SIP stops receiving calls after ~ 10 minutes

### ISSUE THREAD

**Issue by truelai** [jitsi/jitsi#664]
## Description
Jitsi 2.11.5624
Linux Bionic 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

## Current behavior
After about 10 minutes, Jitsi cannot receive or make calls. When it stops working, no errors appear in syslog or jitsi0.log. This bug affects all of my users (all are on Ubuntu).

Though, from startup of jitsi, we see this warning repeat:
2020-04-01 11:17:51.581 WARNING: [119] org.jitsi.impl.neomedia.MediaStreamStatsImpl.log() invalid_rtt,stream=1372464047 ssrc=4206176817,rtt=-33151943,now=1585754271581,lsr=2963046399,dlsr=198246

This warning is documented in issue [#643](https://github.com/jitsi/jitsi/issues/643).

## Expected Behavior

I would expect:
- jitsi continues to be able to accept calls
- If jitsi stops working, logs should produce an error

## Possible Solution
unsure

## Steps to reproduce
- Install on 18.04 5.3.0-45-generic with openjdk 11 from Jitsi's unstable ppa.
- Make a call using jitsi client.
- Wait 10.5 minutes.
- Use another phone to call the jitsi user on their extension.
- Note that it does not ring on the client
- Try to make a call with the client
- Note that you are still able to make calls from the client -  just not receive them

# Environment details
---
Jitsi 2.11.5624
Linux Bionic 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

**Comment by systemcrash** [comment]
Do any of the keepalive methods help in this situation?

Under the SIP account, there are: OPTIONS, REGISTER, CRLF. Some NAT/firewall might be closing, especially since SIP by default uses UDP. Transport used is not evident in your report.

**Comment by damencho** [comment]
OPTIONS are a lightweight way to keep NATs open. REGISTER will normally trigger database queries and such to check users.
