### ISSUE TITLE
xmpp server on localhost

### ISSUE THREAD

**Issue by jbguerraz** [jitsi/jitsi#669]
Having the `net.java.sip.communicator.impl.protocol.jabber.acc1.SERVER_ADDRESS` set to `localhost` get jigasi to complain `initializeConnectAndLogin().779 No server addresses found`

network capture shows it tries to resolve `localhost.{{ search domain }}` and gets no result.

setting it to 127.0.0.1 works.

related to https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/impl/protocol/jabber/ProtocolProviderServiceJabberImpl.java#L761

**Comment by damencho** [comment]
This is how it is intended to work.
