### ISSUE TITLE
Sharing Entire Window is Malfunctioning

### ISSUE THREAD

**Issue by genialkartik** [jitsi/jitsi#673]
## Description
The sharing screen of other windows is working fine. But when I switch back and forth to close or reopen the screen sharing snippet, it gets broken and PC gets hanged.

## Current behavior
Unable to share window (or the tab) in which the meeting tab (link) is opened in the browser.
![meet.jit.si/testkartik](https://user-images.githubusercontent.com/32240906/80119714-af948400-85a7-11ea-8ca0-0c0cabcd9f80.jpg)

## Expected Behavior-
Should share the screen of itself (same tab in which it is opened) without getting broke. It should share entire windows.

## Possible Solution
should stop sharing itself (or calling itself) like console.log(console) in JS.

## Steps to reproduce

# Environment details
Debian 4.19.67-2  x86_64 GNU/Linux
Mozilla Firefox 75.0

**Comment by ibauersachs** [comment]
This repository is for Jitsi Desktop, the legacy chat and VoIP client.
In general, please discuss issues in the [community forums](https://community.jitsi.org/) first before opening bugs on GitHub. If it is confirmed there, the proper repository for Jitsi Meet is here: https://github.com/jitsi/jitsi-meet
