### ISSUE TITLE
Volume error with Chrome on Android

### ISSUE THREAD

**Issue by foolishgrunt** [jitsi/jitsi#674]
## Preamble
My apologies for the cross post: I just reported this bug for Jitsi Meet [here](https://github.com/jitsi/jitsi-meet/issues/6373), but it now occurs to me that it may instead be a backend issue, so I'm also posting it here. Please let me know if I should close one of these issues.

## Description
Per the instructions [here](https://github.com/jitsi/jitsi-meet/pull/3518#issuecomment-611396665), I have three times over the past two weeks attempted to join a Jitsi Meet meeting using Chrome on Android by opening a url as following:
'https://meet.jit.si/[MeetingName]#config.disableDeepLinking=true'
...but the volume suddenly drops to an unusably quiet level.

## Current behavior
It starts out working perfectly fine, no error messages or anything, for several minutes. But I've tested this three times over the past two weeks, and after some number of minutes (the precise length has varied in each instance), the volume on the call suddenly drops precipitously. I can barely hear any of the other speakers, and during at least one of the occurrences the other callers said they could also barely hear me. In each occurrence I was able to complete the call without further issue by switching over to the app.

## Expected Behavior
The volume level should remain constant throughout the conference.

## Steps to reproduce
1. In Chrome for Android, open the meeting room with `#config.disableDeepLinking=true` appended to the url.
2. Proceed with meeting for some length of time (my experiences ranged from ~5 minutes into the chat to ~25 minutes) and wait for the volume to drop suddenly.

# Environment details
Moto X4, Android 9, March 1 security patch

**Comment by ibauersachs** [comment]
This repository is for Jitsi Desktop, the legacy chat and VoIP client.
In general, please discuss issues in the [community forums](https://community.jitsi.org/) first before opening bugs on GitHub. If it is confirmed there, the proper repository for Jitsi Meet is here: https://github.com/jitsi/jitsi-meet
