### ISSUE TITLE
How can I integrate Cisco Equipements (Camera for example) into JITSI configuration ? 

### ISSUE THREAD

**Issue by chi-maker** [jitsi/jitsi#678]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
https://github.com/jitsi/jibri/blob/master/doc/sip_gateway.md
