### ISSUE TITLE
What is the difference between jitsi meet, jitsi, jitsi video bridge?

### ISSUE THREAD

**Issue by godpit** [jitsi/jitsi#694]
Now, the xmpp server is tigase, I want to add audio and video call functions for single chat and group chat. What service components do I need to start?

Please explain the details to me, thank you！

**Comment by damencho** [comment]
Please when you have questions use the community forum before opening new issues.

This repo is Jitsi Desktop the legacy desktop client (XMPP and SIP). If you are searching for a videoconferencing solution you need to use jitsi-meet. That comes by default with prosody installed and configured. You better start there a clean install with prosody that works and then start moving that to connect to your xmpp server as you will stumble on a lot of config problems which are hard for newcomers ... 
jitsi-videobridge is the media server used by jitsi-meet to do videoconferencing, it is SFU, smart network router.

My recommendation is to use a separate deployment with jitsi-meet and prosody and use the iframe API in your app to use it. So you can easily upgrade and keep up to date. 
Or you can directly start using the meet.jit.si one and host one yourself if you need to and do not want to use meet.jit.si. https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe

**Comment by godpit** [comment]
I currently use tigase as XMPP server. From your description, I should just need jitsi-meet and jitsi-videobridge. Does jitsi-meet support a group chat and a single chat voice and video calls？

**Comment by damencho** [comment]
jitsi-meet is a video conferencing tool. I advise deploying it on a separate machine with prosody. You can check jitsi-meet on meet.jit.si. There is no calling or chatting outside the room functionality. 
Jitsi-meet deployment consist of Nginx, jitsi-meet, prosody, jicofo and jvb.

**Comment by damencho** [comment]
If you are looking for pure xmpp desktop client you are looking for [Jitsi Desktop client](https://github.com/jitsi/jitsi/releases/latest).
