### ISSUE TITLE
No pre-built packages

### ISSUE THREAD

**Issue by co5dt** [jitsi/jitsi#697]
## Description
---
There is not a single pre-built package to be found anywhere. Neither here, nor at https://download.jitsi.org/ where this repo's readme is pointing to.

## Current behavior
---
Google and try find any working link to a binary for JITSI. Not Meet, Mofo, Confbridge, WhatNot, just the cient. Impossible.
## Expected Behavior
---
https://download.jitsi.org/stable/ should list something like jitsi_2.1....deb or tar.gz
## Possible Solution
Host binaries directly here within this repo.

## Steps to reproduce
---
/

# Environment details
---
/

**Comment by damencho** [comment]
This is already the case.
https://github.com/jitsi/jitsi/releases/latest

![image](https://user-images.githubusercontent.com/3263098/86784821-912b1a00-c027-11ea-8cbe-bbafa1505646.png)
