### ISSUE TITLE
Jitsi on port 443

### ISSUE THREAD

**Issue by lynxium69** [jitsi/jitsi#710]
Hello,

We installed multiple jisti version, but we have been mandatory to install last version.
We want to all data go thru port 443, not on port 10000.
Our old jitsi version worked fine on port 443.
But all last version use port 10000.

Can someone help or explain us, how to force all jitsi flow on port 443 ?

Debian 10.6 x64
Jitsi 1.0.44.66

Thanks a lot in advance
Any help will be appreciate

**Comment by damencho** [comment]
Use the community forum when you have questions or problems before opening new issues, thank you. 
And this is the wrong repo.
