### ISSUE TITLE
[Question] Share video from local source file or remote url instead of youtube?

### ISSUE THREAD

**Issue by pwFoo** [jitsi/jitsi#722]
Hi,
I use jitsi to talk and share screen, but I would need to share a non public video. Video could be placed at a private server or local client and should be streamed to members in the room.
Tried to do it with screensharing but chrome browser @ windows 10 died... 
Second try video runs really slow.

Is it possible to stream a video by url  or from disk instead of youtube?

**Comment by damencho** [comment]
Please when you have problems or questions use the community forum before opening new issue.

The repository you used is the legacy Desktop client and has nothing to do with jitsi-meet.

You can open the file to be played in one chrome tabs by dropping it there and share that tab with audio.
