### ISSUE TITLE
Optimized view in iFrame is broken

### ISSUE THREAD

**Issue by timowevel03** [jitsi/jitsi#725]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Using an old version I got an optimized view with mute and camera toggle only, see here: https://prnt.sc/11gl46z

## Current behavior
Now I got such one: https://prnt.sc/11gl66x

## Expected Behavior
https://prnt.sc/11gl46z

## Possible Solution
---

## Steps to reproduce
Use newest build DEB package

# Environment details

Any idea how to fix that?

**Comment by damencho** [comment]
Wrong repo and use the community forum for questions as stated in the remplate.

**Comment by timowevel03** [comment]
Okay, wrote it into the forum. Really hoping for help.
