### ISSUE TITLE
unable to download stable/nightly

### ISSUE THREAD

**Issue by blshkv** [jitsi/jitsi#726]
There are links to download source code from the following URL:
https://desktop.jitsi.org/Development/VersionControl.html

"DOWNLOAD A SOURCE SNAPSHOT FROM STABLE RELEASE
(OR A NIGHTLY SNAPSHOT)"

Both links are broken. Perhaps, you want to tag these release here, at github and make them available?

https://github.com/pentoo/pentoo-overlay/issues/720

**Comment by damencho** [comment]
Dropped broken links.

**Comment by Neustradamus** [comment]
There is a problem, files do not exist!

Example:
- http://download.sip-communicator.org/jitsi/nightly/src/
