### ISSUE TITLE
Feature request: Customize screen layout

### ISSUE THREAD

**Issue by gwessels** [jitsi/jitsi#737]
Is it possible to create a option to place participants in the order you want to see them?
e.g. some participants use two sessions in one meeting. One for sharing the video and one for microphone. 
It would be nice if you can move the participant to the bottom of the meeting that share's only the microphone.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues. Thank you.

Wrong repository. This is the legacy Desktop app repository and has nothing to do with jitsi-meet.
