### ISSUE TITLE
SIP Communicator and Jitsi hosted files problem

### ISSUE THREAD

**Issue by Neustradamus** [jitsi/jitsi#744]
Can you move all in one secure place?

Currently:
- NOT SECURE: http://download.sip-communicator.org/jitsi/
- SECURE BUT NOT COMPLETE: https://download.jitsi.org/jitsi/

https://download.jitsi.org/jitsi/
https://download.jitsi.org/jitsi/macosx/
https://download.jitsi.org/jitsi/nightly/
https://download.jitsi.org/jitsi/windows/

http://download.sip-communicator.org/jitsi/
http://download.sip-communicator.org/jitsi/windows/
http://download.sip-communicator.org/jitsi/msi/
http://download.sip-communicator.org/jitsi/debian/
http://download.sip-communicator.org/jitsi/rpm/
http://download.sip-communicator.org/jitsi/linux/
http://download.sip-communicator.org/jitsi/macosx/
http://download.sip-communicator.org/jitsi/macosx-no-jre/
http://download.sip-communicator.org/jitsi/generic/
http://download.sip-communicator.org/jitsi/src/
http://download.sip-communicator.org/jitsi/nightly/

cc: @emcho, @yanas.

Linked to:
- @blshkv: https://github.com/jitsi/jitsi/issues/726

**Comment by damencho** [comment]
forwarded sip-communicator.org to download jitsi.org

versions can be downloaded from https://github.com/jitsi/jitsi/releases/tag/Jitsi-2.10
I will add that to desktop.jitsi.org in a bit

**Comment by Neustradamus** [comment]
@damencho: Please close ONLY this ticket when all folders/files have been migrated.
- jitsi
- jitsi/windows
- jitsi/msi
- jitsi/debian
- jitsi/rpm
- jitsi/linux
- jitsi/macosx
- jitsi/macosx-no-jre
- jitsi/generic
- jitsi/src
- jitsi/nightly

After it, please add in the SSL cert:
- sip-communicator.org
- download.sip-communicator.org
- www.sip-communicator.org

Please redirect http(s)://sip-communicator.org/ and http(s)://www.sip-communicator.org/ to https://desktop.jitsi.org/
Please redirect http(s)://download.sip-communicator.org to https://download.jitsi.org/jitsi/

**Comment by Neustradamus** [comment]
@damencho, @emcho: There are problems!

Migration has not done:
- jitsi
- jitsi/windows
- jitsi/msi
- jitsi/debian
- jitsi/rpm
- jitsi/linux
- jitsi/macosx
- jitsi/macosx-no-jre
- jitsi/generic
- jitsi/src
- jitsi/nightly

And certificates are not good:
- https://sip-communicator.org/
- https://www.sip-communicator.org/
- https://download.sip-communicator.org/

And redirections are not good:
- Please redirect http(s)://sip-communicator.org/ and http(s)://www.sip-communicator.org/ to https://desktop.jitsi.org/
- Please redirect http(s)://download.sip-communicator.org to https://download.jitsi.org/jitsi/

**Comment by Neustradamus** [comment]
@damencho, @emcho: For example, it is linked to:
- https://github.com/pentoo/pentoo-overlay/issues/720
- https://github.com/pentoo/pentoo-overlay/commit/466e2aa25bdbdcbeb7fe80038bc37d7dedcb9766

**Comment by damencho** [comment]
> Migration has not done:
> 
> * jitsi
> * jitsi/windows
> * jitsi/msi
> * jitsi/debian
> * jitsi/rpm
> * jitsi/linux
> * jitsi/macosx
> * jitsi/macosx-no-jre
> * jitsi/generic
> * jitsi/src
> * jitsi/nightly

This will not happen for the time being. You need to use links from https://github.com/jitsi/jitsi/releases

I will make sure tomorrow the sip-communicator forwards to desktop jitsi org ... those certificates will not be renewed.
