### ISSUE TITLE
Cannot enter room in Chrome

### ISSUE THREAD

**Issue by Riccardo1966** [jitsi/jitsi#759]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I cannot enter any JITSI room with Chrome (OK with Firefox)
I can reach meet.jit.si, enter the name of the room I want to join, get to the next page, enter my name but when I press the button to actually enter the room nothing happens. After a few seconds a label informs me that I am no more connected and will be reconnected in 30,29,28,27... seconds.
Same version of Chrome works on different PC (i5 second generation)
Some libraries missing for Chrome but ok for Firefox?
Some javascript problem?
No help googling....

## Current behavior
The blue button to enter room is dead.

## Expected Behavior
Press the button and enter the room

## Possible Solution
---

## Steps to reproduce
Open Chrome and try to enter any JITSI room

# Environment details
Acer Aspire 5, Ryzen 7, 16 Gb ram, SSD HD
Mageia Linux 8
Kernel desktop 5.15.23
Plasma 5.75
GCC 10.3.0-2.mga8
Chrome 98.0.4758.102 (but bug present in earlier versions too...)

Thanks in advance.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.


Check for errors in the js console.

Try in incognito.
