### ISSUE TITLE
build script errors (fix-installers branch)

### ISSUE THREAD

**Issue by Af0x** [jitsi/jitsi#770]
Hello,

following the instructions of the `fix-installers` [building.md](https://github.com/jitsi/jitsi/blob/fix-installers/docs/building.md) on Debian bullseye I encountered the following issues:

- deb-prepare.sh [tries to install 2 packages from debian-backports](https://github.com/jitsi/jitsi/blob/bd51d75528694f2d0c240d48edd8da5ee3f70914/resources/deb-prepare.sh#L11-L12) that don´t exist.
- [deb-gen-source.sh](https://github.com/jitsi/jitsi/blob/fix-installers/resources/deb-gen-source.sh) returns the following error:
`dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision`

**Comment by ibauersachs** [comment]
There's a reason #764 is still a draft...

- deb-prepare is meant to run on Ubuntu. Maybe I should name the scripts ubuntu-*
- deb-gen-source: not sure how you called the script

I'm closing this issue, if you have other comments or ideas for improvements (specifically, building on Debian instead of Ubuntu) please comment them in #764. However, please note that the build scripts are already complicated enough. I'd rather not want to make them even more complicated when I can build packages for Debian from Ubuntu.

Also, I know that it would be best to have a package build which could run on e.g. Launchpad. But it's simply futile to attempt to package several dozen dependencies. Even if some are already packaged, they are sometimes not the version needed or incorrectly packaged (e.g. missing OSGi metadata).

**Comment by Af0x** [comment]
> * not sure how you called the script
as root I called `./deb-gen-source.sh 2.14.0 bullseye`

**Comment by ibauersachs** [comment]
Well, the PR doesn't seem to run anymore either, but for a different reason. The Action generates 2.14.681.20220929164115+g8aa7be585 as version, try using either 2.14 or add a plus so that it doesn't detect a revision.

**Comment by Af0x** [comment]
I set 2.14 but still unchanged result:
```
./deb-gen-source.sh 2.14 bullseye
+ '[' 2 -ne 2 ']'
+++ dirname ./deb-gen-source.sh
++ realpath ./../
+ cd /path/to/jitsi
+ VERSION=2.14
+ DIST=bullseye
++ git describe --match 'Jitsi-[0-9\.]*' --abbrev=0
+ SINCE=Jitsi-2.10
+ debian-distro-info --all
+ grep -Fqxi bullseye
++ debian-distro-info --series=bullseye -r
+ DIST_VERSION=11
+ FULL_VERSION=2.14-11~bullseye
+ rm -rf debian/javah
+ cp -r target/native/javah debian/
+ export 'DEBFULLNAME= via GitHub Actions'
+ DEBFULLNAME=' via GitHub Actions'
+ export DEBEMAIL=dev@jitsi.org
+ DEBEMAIL=dev@jitsi.org
+ git config --local user.name ' via GitHub Actions'
+ git config --local user.email dev@jitsi.org
+ gbp dch --ignore-branch --since Jitsi-2.10 --meta --release --distribution=bullseye --force-distribution --spawn-editor=never --new-version=2.14-11~bullseye
+ dpkg-source -b .
dpkg-source: info: using options from jitsi/debian/source/options: --tar-ignore=.git --tar-ignore=.github --tar-ignore=.idea --tar-ignore=lib --tar-ignore=target --tar-ignore=resources/install/gradle --tar-ignore=resources/install/mac --tar-ignore=resources/install/main/mac --tar-ignore=resources/install/main/windows --tar-ignore=resources/install/windows --tar-ignore=resources/install/gradle* --tar-ignore=resources/install/settings.gradle
dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision
```

**Comment by Af0x** [comment]
I fixed this issue by editing the FULL_VERSION, see https://github.com/jitsi/jitsi/pull/772

Next issue is with the [deb-build.sh](https://github.com/jitsi/jitsi/blob/fix-installers/resources/deb-build.sh). I get the following output:

```
I: Base system installed successfully.
W: line 11 [bullseye-amd64] union-type: Configuration key name 'union-type' is not a permitted name.
E: 10mount: mount: /run/schroot/mount/bullseye-amd64-cf87972f-98b3-4284-b113-2c898bc4ecb0/var/cache/m2-sbuild: special device /var/cache/m2-sbuild does not exist.
E: bullseye-amd64-cf87972f-98b3-4284-b113-2c898bc4ecb0: Chroot setup failed: stage=setup-start
+ true
+ sudo sbuild-update -ud bullseye-amd64
W: line 11 [bullseye-amd64] union-type: Configuration key name 'union-type' is not a permitted name.
W: line 11 [bullseye-amd64] union-type: Configuration key name 'union-type' is not a permitted name.
E: 10mount: mount: /run/schroot/mount/bullseye-amd64-25b88b2b-43cf-4b2b-8ea2-4cf3e1bc5ffd/var/cache/m2-sbuild: special device /var/cache/m2-sbuild does not exist.
E: bullseye-amd64-25b88b2b-43cf-4b2b-8ea2-4cf3e1bc5ffd: Chroot setup failed: stage=setup-start
Chroot setup failed
Error setting up bullseye-amd64 chroot
Chroot setup failed at /usr/bin/sbuild-update line 145.
```

**Comment by ibauersachs** [comment]
Create the folder /var/cache/m2-sbuild on your build host.

This is mounted into the chroot to cache the downloaded Maven dependencies.
