### ISSUE TITLE
upgrading fails on buntu 20.04.6 LTS due to prosody version not available

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/jitsi#783]
jitsi-meet-prosody : Depends: prosody (>= 0.11.7) but 0.11.4-1 is to be installed or
                               prosody-trunk but it is not installable or
                               prosody-0.12 but it is not installable or
                               prosody-0.11 but it is not installable

Maybe this is dependency is just set to high in the package?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/#add-the-prosody-package-repository
