### ISSUE TITLE
Debian/Ubuntu: Java Classpath misses /usr/share/jitsi

### ISSUE THREAD

**Issue by traud** [jitsi/jitsi#794]
In Ubuntu 20.04 LTS, after installing Jitsi Desktop as described [here](https://github.com/jitsi/jitsi/issues/793#issuecomment-1534666983), I try to
```
$ jitsi
```
from the Terminal. This gives me
```
exec /usr/bin/java -cp 'lib/*:config/' --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -splash:/usr/share/jitsi/splash.gif net.java.sip.communicator.launcher.Jitsi
Error: Could not find or load main class net.java.sip.communicator.launcher.Jitsi
Caused by: java.lang.ClassNotFoundException: net.java.sip.communicator.launcher.Jitsi
```
If I start the Java Runtime Environment directly and append ``/usr/share/jitsi``to the parameter ``cp`` like
```
$ java -cp '/usr/share/jitsi/lib/*:/usr/share/jitsi/config/' --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -splash:/usr/share/jitsi/splash.gif net.java.sip.communicator.launcher.Jitsi
```
everything works.

**Comment by ibauersachs** [comment]
Hm, yes. I think I wrote the script to execute within the working directory and not from /usr/bin, which naturally doesn't make sense once installed. The source is here: https://github.com/jitsi/jitsi/blob/master/resources/install/debian/jitsi. Would you mind creating a PR?

**Comment by traud** [comment]
Thanks, yes, saw that. However, although I used the branch ``new-build`` three years ago already, building Jitsi Desktop has changed since then again. I have to research how it works now. Easy for you, hours, even days for me. Furthermore, I am working at two different areas right now (libjitsi, …) and Jitsi Desktop itself works for me. In other words, right now, I can only report issues in Jitsi Desktop. In other words, when I create a Pull Request, it was tested at least once. I cannot do that right now because I do not have a build system. So, whoever is faster, please, take over this issue.

**Comment by traud** [comment]
That file is not compiled, it is used verbatim. Therefore, I can test it right now. Therefore, I created a Pull Request.
