### ISSUE TITLE
The problem with emoticons in the chat window and font when choosing a language

### ISSUE THREAD

**Issue by lMorpheil** [jitsi/jitsi#824]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Emoticons in the chat are displayed incorrectly on some machines and Asian languages are displayed incorrectly in the language selection settings. I have not found a solution to this problem

## Current behavior
![image](https://github.com/user-attachments/assets/59cea02b-6455-4064-ac23-42e5000caee1)
![image](https://github.com/user-attachments/assets/a60ada1b-b4c9-412a-9de0-12a66ea519a3)

## Expected Behavior
It is expected that the emoticons will be rendered
## Possible Solution
I have noto sans installed on my system and it is used on emoticons, but in a system where there is no display, libre is used

## Steps to reproduce
plants in chat and settings language selection

# Environment details
OS Debian bullseye browser chromium ghost

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Wrong repo.
